# frozen_string_literal: true

require "set"

module RQG
  # A generated case: the self-contained setup (CREATE/INSERT) + one query, its sortmode, and the
  # capabilities it uses. Rendered to a sqllogictest `.test` once the driver fills the expected output
  # from the PG oracle. The shape_key is a literal/identifier-erased skeleton used to dedup the
  # curated corpus by STRUCTURE (so two cases differing only in values/column-names collapse to one).
  Case = Struct.new(:seed, :shape, :setup, :query, :sortmode, :caps, keyword_init: true) do
    def shape_key = RQG.skeleton(query)
  end

  module_function

  # Canonical structural skeleton of a query: lowercase, string literals -> S, double-quoted names
  # (e.g. COLLATE "C") -> Q, numbers -> N, non-keyword identifiers -> I, whitespace collapsed.
  KEYWORDS = %w[
    select distinct from where and or not is null between in like ilike order by asc desc nulls
    first last limit offset true false collate as group having count sum min max avg join inner
    cross on union intersect except all exists case when then else end with
  ].to_set

  def skeleton(sql)
    s = sql.dup.downcase
    s = s.gsub(/'(?:[^']|'')*'/, "S")        # single-quoted string literals
    s = s.gsub(/"(?:[^"]|"")*"/, "Q")         # double-quoted identifiers (collation names)
    s = s.gsub(/\b\d+(?:\.\d+)?\b/, "N")      # numeric literals
    s = s.gsub(/[a-z_][a-z0-9_]*/) { |w| KEYWORDS.include?(w) ? w : "I" }
    s.gsub(/\s+/, " ").strip
  end

  # The header comment lines for a generated `.test` (no `# requires:` — callers add that, since the
  # committed per-shape file's requires is the UNION over its blocks).
  def case_banner(shape, seed)
    ["# RQG #{shape} (seed #{seed}) — GENERATED by scripts/rqg_gen.rb.",
     "# Random query differential vs the live PostgreSQL oracle; expected rows are PG's.",
     "# Deliberate jed-vs-PG divergences are avoided by construction (COLLATE \"C\" on text",
     "# ordering, no float/overflow, rowsort without ORDER BY) — see .scratch/testing-ideas.md."]
  end

  # The records portion (setup + the filled query) WITHOUT a file header — appended into the shared
  # per-shape corpus file. A block leads with a `# --- seed N ---` marker (the corpus accumulator
  # splits on it), then blank-line-separated records, ending at the last expected value (no trailing
  # blank). `expected` is the flat rendered value list (already rowsorted if sortmode is rowsort).
  def case_block(kase, coltypes, expected)
    recs = kase.setup.map { |sql| "statement ok\n#{sql}" }
    query = "query #{coltypes} #{kase.sortmode}\n#{kase.query}\n----"
    query += "\n#{expected.join("\n")}" unless expected.empty?
    recs << query
    "# --- seed #{kase.seed} ---\n#{recs.join("\n\n")}"
  end

  # A standalone candidate `.test` (its own header + requires) for the _rqg_tmp batch harness run.
  def candidate_file(kase, coltypes, expected)
    [*case_banner(kase.shape, kase.seed),
     "# requires: #{kase.caps.to_a.sort.join(', ')}",
     "",
     case_block(kase, coltypes, expected)].join("\n") + "\n"
  end
end
