// Table metadata: column definitions and lookups. Data-shaped (a type + free
// functions) to match the boring/explicit style (CLAUDE.md §10).

import type { Expr } from "./ast.ts";
import { type DecimalTypmod, type ScalarType, type Type, scalarTypeFromName } from "./types.ts";
import type { Value } from "./value.ts";

// Column is a column definition: name, declared type, nullability, primary-key flag, default.
// notNull is implied true for a PRIMARY KEY column.
export type Column = {
  name: string;
  // The column's declared type — a built-in scalar or a user-defined composite
  // (spec/design/composite.md). The open `Type` wrapper (CLAUDE.md §4): scalar-only call sites
  // read `typeScalar(col.type)`; the value codec / resolver branch on isCompositeType.
  type: Type;
  // The numeric(p,s) typmod for a decimal column, or null for a non-decimal column OR an
  // unconstrained numeric (spec/design/decimal.md §2). A constrained decimal column coerces
  // stored values to this precision/scale.
  decimal: DecimalTypmod | null;
  // The varchar(n) max-length typmod for a text column, or null for a non-text column OR an
  // unbounded text (spec/design/types.md §15). n counts code points; an over-length assignment
  // traps 22001. Persisted as a u32 in the typmod slot (type_code 4, format_version 22).
  varcharLen: number | null;
  primaryKey: boolean;
  notNull: boolean;
  // The column's CONSTANT DEFAULT value, pre-evaluated and type-coerced at CREATE TABLE, or
  // null if it has no default or an EXPRESSION default (defaultExpr). A `{ kind: "null" }`
  // value is an explicit DEFAULT NULL. Applied for an omitted column or a DEFAULT keyword at
  // INSERT (spec/design/constraints.md §2).
  default: Value | null;
  // The column's EXPRESSION DEFAULT (a non-constant default like uuidv7() or 1 + 1), or null if
  // it has no default or a constant default (default). Mutually exclusive with default. Stored
  // as expression text (re-rendered verbatim at every commit, like a CHECK —
  // spec/fileformat/format.md) plus the parsed expression the write paths resolve and evaluate
  // per row (spec/design/constraints.md §2).
  defaultExpr: DefaultExpr | null;
  // Whether the column is a GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY column, and which kind
  // (spec/design/sequences.md §13). null is a non-identity column. An identity column also carries
  // notNull + a defaultExpr (nextval of its owned sequence); the kind gates whether an explicit
  // INSERT/UPDATE value is accepted (428C9). Persisted as two column flag bits (format_version 15:
  // bit4 is_identity, bit5 identity_always).
  identity: IdentityKind | null;
  // The column's EFFECTIVE collation — null is C (byte / code-point order, the unchanged fast path),
  // a non-empty name a loaded non-C collation (spec/design/collation.md §1). Frozen at CREATE TABLE:
  // an explicit COLLATE "name", else the per-database default as of creation (PG-matching). Only a
  // text column carries one. A column reference's IMPLICIT collation in the derivation (42P22);
  // persisted as column flag bit6 + a trailing name (format_version 17).
  collation: string | null;
};

// IdentityKind is the kind of an IDENTITY column (spec/design/sequences.md §13). "always"
// (GENERATED ALWAYS) rejects an explicit INSERT/UPDATE value (428C9) unless overridden; "byDefault"
// (GENERATED BY DEFAULT) accepts one, behaving like serial. Persisted as flag bit5 identity_always
// (set ⇒ "always", clear ⇒ "byDefault"), meaningful only with bit4 is_identity.
export type IdentityKind = "always" | "byDefault";

// DefaultExpr is a column's EXPRESSION DEFAULT (spec/design/constraints.md §2): its persisted
// expression text — written back verbatim at every commit so the catalog bytes are stable
// (spec/fileformat/format.md "Check-expression text") — and the parsed expression the write
// paths resolve (against an empty scope, no columns) and evaluate per inserted row. Modeled on
// CheckConstraint.
export type DefaultExpr = { exprText: string; expr: Expr };

// Table is a table definition.
export type Table = {
  name: string;
  columns: Column[];
  // The primary-key member column ordinals in KEY order (which may differ from
  // declaration order — constraints.md §3; the v5 catalog persists this list). Empty =
  // no primary key (synthetic rowid keys). The per-column primaryKey flag is derived
  // membership convenience; this list is the authority for order.
  pk: number[];
  // The table's CHECK constraints in EVALUATION ORDER — ascending byte order of the
  // lowercased name (spec/design/constraints.md §4.4); the on-disk catalog stores them in
  // this same order. Empty for an unchecked table.
  checks: CheckConstraint[];
  // The table's secondary indexes in ascending lowercased-name order (the catalog's
  // on-disk order and the planner's tie-break order — spec/design/indexes.md).
  indexes: IndexDef[];
  // The table's FOREIGN KEY constraints in ascending lowercased-name order (the catalog's
  // on-disk order and the child-side evaluation order — spec/design/constraints.md §6.9).
  // Empty for a table with none.
  fks: ForeignKey[];
  // The table's EXCLUDE constraints in ascending lowercased-name order (the catalog's on-disk
  // order — spec/design/gist.md §7/§8). Each is backed by a GiST index in `indexes`. Empty for a
  // table with none.
  exclusions: ExclusionConstraint[];
};

// ExclusionOp is one element's operator in an EXCLUDE constraint (spec/design/gist.md §7) — the WITH
// operator of a (column WITH op) pair. "overlaps" is && (a range column, range_ops); "equal" is = (a
// fixed-width keyable scalar, the in-core btree_gist). Both are SYMMETRIC, the property an exclusion
// operator must have. Persisted as the v21 per-element strategy byte (&& = 0, = 1; format.md).
export type ExclusionOp = "overlaps" | "equal";

// ExclusionElement is one (column, operator) element of an EXCLUDE constraint — a member column
// ordinal into the owning table and its WITH operator. The element order matches the backing GiST
// index's column order (spec/design/gist.md §7/§8).
export type ExclusionElement = { column: number; op: ExclusionOp };

// ExclusionConstraint is one EXCLUDE constraint (spec/design/gist.md §7): its (relation-namespace)
// name, the backing GiST index that enforces it (by name — the constraint IS its index, the
// UNIQUE-is-its-index model generalized to an explicit operator list), and the (column, operator)
// element vector the conjunction probe needs. The NULL rule (§7) is enforced at probe time: a row
// with a NULL in any excluded column never conflicts.
export type ExclusionConstraint = {
  name: string;
  // The backing GiST index's name (equal to `name` for a GX3 constraint — it owns the index).
  index: string;
  elements: ExclusionElement[];
};

// FkAction is the persisted referential action for a foreign key's `ON DELETE` / `ON UPDATE`
// (spec/design/constraints.md §6.6). Only "noAction" (the default) and "restrict" are supported —
// they are identical in jed (no deferrable constraints). The write-actions (CASCADE / SET NULL /
// SET DEFAULT) are rejected 0A000 at CREATE TABLE, so never reach here; the on-disk encoding
// reserves codes for them (format.md).
export type FkAction = "noAction" | "restrict";

// ForeignKey is one resolved FOREIGN KEY constraint of a table (spec/design/constraints.md §6):
// its (per-table constraint-namespace) name, the referencing column ordinals into THIS table in
// list order, the referenced (parent) table name, the referenced column ordinals into the PARENT
// in list order (same length as columns), and the referential actions. An FK owns no B-tree;
// enforcement probes the parent's PK store or a unique index (§6.4). Held in ascending
// lowercased-name order on the table (the catalog's on-disk order and the child-side evaluation
// order — §6.9).
export type ForeignKey = {
  name: string;
  columns: number[];
  refTable: string;
  refColumns: number[];
  onDelete: FkAction;
  onUpdate: FkAction;
};

// IndexKey is one index key element (spec/design/indexes.md §1): a bare column (by ordinal into the
// table's columns) or an expression over the table's columns (`lower(email)`), carrying its persisted
// canonical text and the re-parsed (unresolved) AST — the write/plan paths re-resolve it against the
// table per statement, exactly as a CHECK is re-resolved. Only a B-tree index may carry an expression
// element (GIN/GiST are single column, this slice).
export type IndexKey =
  | { kind: "column"; column: number }
  | { kind: "expr"; exprText: string; expr: Expr };

// IndexDef is one secondary index of a table (spec/design/indexes.md): its
// (relation-namespace) name and its key elements in index-key order (columns and/or
// expressions, duplicates allowed — PG). The index's B-tree lives in the snapshot's
// index-store map, keyed by the lowercased name. A unique index enforces uniqueness over
// its key tuple (NULLS DISTINCT — spec/design/indexes.md §8); it is what backs a UNIQUE
// constraint (spec/design/constraints.md §5).
export type IndexDef = {
  name: string;
  keys: IndexKey[];
  unique: boolean;
  // kind selects an ordered B-tree (the default), a GIN inverted index (spec/design/gin.md), or a
  // GiST R-tree (spec/design/gist.md). Persisted as the per-index index_kind byte (v13 GIN, v20
  // GiST); a GIN/GiST index is never unique.
  kind: "btree" | "gin" | "gist";
  // predicate is a PARTIAL index's WHERE predicate (spec/design/indexes.md §9): only rows whose
  // predicate is TRUE are indexed / constrained. undefined for an ordinary (full) index. Carries the
  // persisted canonical text + the re-parsed (unresolved) AST — re-resolved against the table per
  // statement, like an expression key. Partial indexes are B-tree only (format_version 27).
  predicate?: { exprText: string; expr: Expr };
};

// indexKeyColumn is the column ordinal of a plain column key element, else null (an expression key).
export function indexKeyColumn(k: IndexKey): number | null {
  return k.kind === "column" ? k.column : null;
}

// indexAllColumns reports whether every key element is a plain column (no expression key) — the
// common case, and the GIN/GiST invariant. Lets column-only code paths fast-check.
export function indexAllColumns(def: IndexDef): boolean {
  return def.keys.every((k) => k.kind === "column");
}

// indexColumnOrdinals returns the key elements' column ordinals if every element is a plain column,
// else null (the index has at least one expression key). The many column-only consumers — the
// GIN/GiST entry builders, FK-target matching, introspection — use this; an expression key makes the
// index ineligible for those (an FK cannot target an expression index, etc.).
export function indexColumnOrdinals(def: IndexDef): number[] | null {
  const out: number[] = [];
  for (const k of def.keys) {
    if (k.kind !== "column") return null;
    out.push(k.column);
  }
  return out;
}

// indexFirstColumn is the column ordinal of the first key element, assuming a single-column index —
// used by the GIN/GiST paths, which are always single-column plain-column indexes (this slice).
export function indexFirstColumn(def: IndexDef): number {
  const c = indexKeyColumn(def.keys[0]!);
  if (c === null) throw new Error("GIN/GiST index key is a plain column");
  return c;
}

// CheckConstraint is one CHECK constraint: its (resolved, unique-per-table) name, its
// persisted expression text — written back verbatim at every commit so the catalog bytes
// are stable (spec/fileformat/format.md "Check-expression text") — and the parsed
// expression the write paths resolve and evaluate per candidate row (constraints.md §4).
export type CheckConstraint = { name: string; exprText: string; expr: Expr };

// CompositeType is a user-defined COMPOSITE (row) type (spec/design/composite.md): a named,
// ordered list of typed fields, living in the database's type catalog (a database-level object,
// not per-table). Created by `CREATE TYPE name AS (field type, …)`, referenced by name from a
// column's Type. Recursive — a field's type may itself be a composite (a nested composite,
// persisted by name; spec/fileformat/format.md *Composite-type entry*).
export type CompositeType = {
  // The type name (original case — round-trips what the user typed); looked up case-insensitively.
  name: string;
  // The fields in declaration order (>= 1).
  fields: CompositeField[];
};

// CompositeField is one field of a composite type: its name, type, decimal typmod, and declared
// nullability (mirrors Column).
export type CompositeField = {
  name: string;
  type: Type;
  // The decimal numeric(p,s) typmod when type is decimal, else null (mirrors Column).
  decimal: DecimalTypmod | null;
  // The varchar(n) max-length typmod when type is text, else null (mirrors Column —
  // spec/design/types.md §15).
  varcharLen: number | null;
  // Whether the field was declared NOT NULL.
  notNull: boolean;
};

// SequenceDef is a SEQUENCE (spec/design/sequences.md): a named, persisted, monotonic i64
// generator — the third database-level catalog-object kind (after tables and composite types). The
// definition fields (increment/minValue/maxValue/start/cache/cycle) are immutable; lastValue +
// isCalled are the mutable counter state a nextval advances. The whole struct lives in the snapshot
// catalog, so the counter is transactional by construction (sequences.md §5). The i64 fields are
// bigint (the TS core's exact-i64 representation).
export type SequenceDef = {
  // The sequence name (original case; looked up case-insensitively).
  name: string;
  // The step per nextval (non-zero). Positive = ascending, negative = descending.
  increment: bigint;
  // The inclusive lower bound.
  minValue: bigint;
  // The inclusive upper bound.
  maxValue: bigint;
  // The first value nextval returns (on a fresh sequence, lastValue === start).
  start: bigint;
  // The PostgreSQL CACHE size — stored for fidelity but behaves as 1 (sequences.md §7).
  cache: bigint;
  // Whether nextval wraps at a bound (CYCLE) instead of raising 2200H.
  cycle: boolean;
  // The mutable counter: the most recent value produced (or start before the first call).
  lastValue: bigint;
  // Whether nextval has been called: false ⇒ the next call returns lastValue (= start) without
  // incrementing; true ⇒ it adds increment (PostgreSQL's is_called).
  isCalled: boolean;
  // The OWNED BY link for a sequence created by a serial column (spec/design/sequences.md §12) —
  // present records the owning table + column ordinal, undefined for a plain CREATE SEQUENCE.
  // Persisted (format_version 13, the has_owner flag bit): it drives DROP TABLE auto-drop and the
  // DROP SEQUENCE 2BP01. A plain DEFAULT nextval('s') creates no owner link (PG — sequences.md §10
  // decision 4).
  ownedBy?: SeqOwner;
};

// SeqOwner is the OWNED BY reference of a serial-created sequence (spec/design/sequences.md §12):
// the owning table (original case) and the owning column's 0-based ordinal. Persisted on the
// sequence catalog entry (format.ts / format.md *Sequence entry*, v13).
export type SeqOwner = {
  table: string;
  column: number;
};

// I64_MAX is the i64 maximum (2^63-1), the default ascending MAXVALUE for an AS bigint sequence.
export const I64_MAX = 9223372036854775807n;

// SeqDataType is a sequence's value data type (`AS smallint | integer | bigint`,
// spec/design/sequences.md §14). Its only effect is on the bounds: it sets the default + validated
// MINVALUE/MAXVALUE. The counter is always an i64 (bigint here), and the type is not persisted (it
// is reducible to the bounds), so this is a parse/build-time concept only. Modeled as a
// string-literal union with free functions, matching ScalarType's style (CLAUDE.md §10).
export type SeqDataType = "smallint" | "integer" | "bigint";

// seqDataTypeRange returns the inclusive value range [T_min, T_max] of the type (the natural
// i16/i32/i64 range).
export function seqDataTypeRange(t: SeqDataType): [bigint, bigint] {
  switch (t) {
    case "smallint":
      return [-32768n, 32767n];
    case "integer":
      return [-2147483648n, 2147483647n];
    case "bigint":
      return [-9223372036854775808n, 9223372036854775807n];
  }
}

// seqDataTypePgName returns the PostgreSQL type name used in error messages (smallint / integer /
// bigint). The union member is already that name; kept as a function to mirror the Go/Rust API.
export function seqDataTypePgName(t: SeqDataType): string {
  return t;
}

// seqDataTypeDefaultBounds returns the type defaults for an ascending (increment > 0) vs descending
// sequence, before any explicit MIN/MAX/START override (PostgreSQL init_params): ascending ⇒
// [1, T_max], start = MIN; descending ⇒ [T_min, -1], start = MAX. Returns [min, max].
export function seqDataTypeDefaultBounds(t: SeqDataType, increment: bigint): [bigint, bigint] {
  const [lo, hi] = seqDataTypeRange(t);
  if (increment < 0n) return [lo, -1n];
  return [1n, hi];
}

// seqDataTypeFromName resolves an `AS <name>` type to a sequence data type, or undefined if the name
// is not an integer type (caller raises 22023 "sequence type must be smallint, integer, or bigint").
export function seqDataTypeFromName(name: string): SeqDataType | undefined {
  const s = scalarTypeFromName(name);
  if (s === undefined) return undefined;
  return seqDataTypeForScalar(s);
}

// seqDataTypeForScalar returns the sequence data type matching a column's integer scalar
// (serial/identity auto-wiring): an i16/i32/i64 column maps to smallint/integer/bigint; any other
// scalar → undefined.
export function seqDataTypeForScalar(s: ScalarType): SeqDataType | undefined {
  switch (s) {
    case "i16":
      return "smallint";
    case "i32":
      return "integer";
    case "i64":
      return "bigint";
    default:
      return undefined;
  }
}

// ColType is a fully-resolved storage/codec column type (spec/design/composite.md §4): a scalar,
// or a composite resolved to the codec/coercion tree of its fields. Built ONCE from a catalog
// Type against the snapshot's composite-type definitions (resolveColType) and held by the
// TableStore, so the value codec and store-coercion never re-walk the type catalog on every row.
// Recursive — a composite field may itself be composite. The codec reads only the scalar / field
// structure; the field typmod / notNull are consulted by store-coercion (executor). Modeled as a
// discriminated union (keyed on `kind`, like Type/Value), with free-function helpers — never
// methods on the union (CLAUDE.md §10).
export type ColType =
  | { kind: "scalar"; scalar: ScalarType }
  // A composite type's resolved fields, in declaration order. `name` is the (original-case) type
  // name, used in store-coercion error messages.
  | { kind: "composite"; name: string; fields: ColField[] }
  // An array's resolved element type (spec/design/array.md §3). Structural — the element type is
  // carried inline, recursively; v1 element types are scalars.
  | { kind: "array"; elem: ColType }
  // A range's resolved element type (spec/design/ranges.md §3). Structural like array — the element
  // is carried inline, but is always one of the six scalar subtypes (i32/i64/decimal/timestamp/
  // timestamptz/date), never composite/array/nested-range. The codec reads the element scalar for
  // the bound bodies; the descriptor (discreteness) is re-derived from the element via
  // rangeForElement.
  | { kind: "range"; elem: ColType };

// ColField is one resolved field of a composite ColType — its name, recursively-resolved type, the
// decimal typmod (when the field is decimal), and declared nullability (mirrors CompositeField, but
// with the type fully resolved for the codec/coercion path).
export type ColField = {
  name: string;
  type: ColType;
  typmod: DecimalTypmod | null;
  // The varchar(n) max-length typmod when type is text (spec/design/types.md §15).
  varcharLen: number | null;
  notNull: boolean;
};

// resolveColType resolves a catalog Type into a self-contained ColType against the database's
// composite definitions (keyed by lowercased name, the Snapshot.types map). A composite reference
// is looked up case-insensitively and recursively resolved; the lookup is guaranteed to succeed
// because validateCompositeTypes (the two-pass load / CREATE TYPE gate) proved every reference
// exists and the graph is acyclic before any store is built (spec/design/composite.md §3).
export function resolveColType(ty: Type, types: Map<string, CompositeType>): ColType {
  if (ty.kind === "scalar") return { kind: "scalar", scalar: ty.scalar };
  if (ty.kind === "array") return { kind: "array", elem: resolveColType(ty.elem, types) };
  if (ty.kind === "range") {
    // A range column (spec/design/ranges.md §3): structural like array, the element resolved inline.
    // The element is always one of the six scalar subtypes, so the recursion bottoms out at a
    // scalar ColType immediately.
    return { kind: "range", elem: resolveColType(ty.elem, types) };
  }
  const def = types.get(ty.name.toLowerCase());
  if (def === undefined) {
    throw new Error("composite type reference resolved by validateCompositeTypes");
  }
  return {
    kind: "composite",
    name: def.name,
    fields: def.fields.map((f) => ({
      name: f.name,
      type: resolveColType(f.type, types),
      typmod: f.decimal,
      varcharLen: f.varcharLen,
      notNull: f.notNull,
    })),
  };
}

// columnIndex returns the index of the named column (case-insensitive), or -1.
export function columnIndex(t: Table, name: string): number {
  const lower = name.toLowerCase();
  for (let i = 0; i < t.columns.length; i++) {
    if (t.columns[i]!.name.toLowerCase() === lower) return i;
  }
  return -1;
}

// pkIndices returns the primary-key member columns' indices in KEY order (the explicit
// pk list — the v5 catalog persists key order independent of declaration order). Empty =
// the table has no primary key (synthetic rowid keys).
export function pkIndices(t: Table): number[] {
  return t.pk;
}

// primaryKeyIndex returns the primary-key column's index iff the key is SINGLE-column, else -1.
// Callers that genuinely require one member (notably OR/IN point sets) use this helper; tuple bounds
// iterate pkIndices directly.
export function primaryKeyIndex(t: Table): number {
  const idxs = pkIndices(t);
  return idxs.length === 1 ? idxs[0]! : -1;
}
