// @generated by scripts/gen_costs.rb from spec/cost/schedule.toml — DO NOT EDIT.
//
// Cost unit schedule (CLAUDE.md §5, §13: the codegen "middle path"). DATA only — the
// accrual sites that CONSUME these weights (executor / evaluator / storage reads) are
// hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
// `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/cost.md.

// The deterministic cost-unit weights, mirroring spec/cost/schedule.toml. Weights are
// bigint for i64 parity with the Rust/Go cores (a number is f64 — CLAUDE.md §8).
export interface CostSchedule {
  storageRowRead: bigint;
  pageRead: bigint;
  valueCompress: bigint;
  valueDecompress: bigint;
  decimalWork: bigint;
  rowProduced: bigint;
  operatorEval: bigint;
  aggregateAccumulate: bigint;
  cteScanRow: bigint;
  generatedRow: bigint;
  sequenceAdvance: bigint;
  ginEntry: bigint;
  gistDescent: bigint;
  collate: bigint;
  timezone: bigint;
  regexCompile: bigint;
  regexStep: bigint;
  windowResult: bigint;
  varlenCompare: bigint;
  windowFrameStep: bigint;
}

// The canonical cost schedule — weights accrued per unit during query execution.
export const COSTS: CostSchedule = {
  storageRowRead: 1n,
  pageRead: 1n,
  valueCompress: 1n,
  valueDecompress: 1n,
  decimalWork: 1n,
  rowProduced: 1n,
  operatorEval: 1n,
  aggregateAccumulate: 1n,
  cteScanRow: 1n,
  generatedRow: 1n,
  sequenceAdvance: 1n,
  ginEntry: 1n,
  gistDescent: 1n,
  collate: 1n,
  timezone: 1n,
  regexCompile: 1n,
  regexStep: 1n,
  windowResult: 1n,
  varlenCompare: 1n,
  windowFrameStep: 1n,
};
