// @generated by scripts/gen_estimator.rb from spec/cost/{estimator,schedule}.toml — DO NOT EDIT.
// Mechanical constants only; estimator control flow remains hand-written in every core.

export type EstimatorFraction = { numerator: bigint; denominator: bigint };

export const MAX_ESTIMATE = 9223372036854775807n;
export const DEFAULT_DISTINCT_VALUES = 200n;
export const DEFAULT_SRF_ROWS = 1000n;
export const DEFAULT_VARIABLE_KEY_BYTES = 1n;
export const JOIN_DP_LIMIT = 8;
export const STATISTICS_TARGET = 100;
export const STATISTICS_SAMPLE_ROWS = 30000;
export const STATISTICS_KMV_HASHES = 4096;
export const STATISTICS_MCV_ENTRIES = 100;
export const STATISTICS_HISTOGRAM_BOUNDS = 101;
export const STATISTICS_MAX_VALUE_BYTES = 128;
export const STATISTICS_NDV_SCALE_NUMERATOR = 1n;
export const STATISTICS_NDV_SCALE_DENOMINATOR = 10n;

export const SELECTIVITY_EQUALITY: EstimatorFraction = { numerator: 1n, denominator: 200n };
export const SELECTIVITY_INEQUALITY: EstimatorFraction = { numerator: 1n, denominator: 3n };
export const SELECTIVITY_PAIRED_RANGE: EstimatorFraction = { numerator: 1n, denominator: 200n };
export const SELECTIVITY_NULL_TEST: EstimatorFraction = { numerator: 1n, denominator: 200n };
export const SELECTIVITY_MATCH: EstimatorFraction = { numerator: 1n, denominator: 200n };
export const SELECTIVITY_MATCHING: EstimatorFraction = { numerator: 1n, denominator: 100n };
export const SELECTIVITY_BOOLEAN: EstimatorFraction = { numerator: 1n, denominator: 2n };
export const SELECTIVITY_OPAQUE: EstimatorFraction = { numerator: 1n, denominator: 3n };

export const ACCESS_GIST_EQUAL = "equality";
export const ACCESS_GIST_RANGE = "matching";
export const ACCESS_GIN_CONTAINS = "matching";
export const ACCESS_GIN_OVERLAPS = "matching";
export const ACCESS_GIN_MEMBER = "matching";
export const ACCESS_GIN_EQUAL = "matching";
export const ACCESS_UNSUPPORTED = "opaque";

export const ESTIMATOR_ACCESS_PATH_ORDER = [
  "pk",
  "btree",
  "gist",
  "gin",
  "pk_interval",
  "index_interval",
  "full",
] as const;

export const ESTIMATOR_UNIT_COUNT = 24;
export const UNIT_STORAGE_ROW_READ = 0;
export const UNIT_STATISTICS_VALUE = 1;
export const UNIT_PAGE_READ = 2;
export const UNIT_CONSTRAINT_CHECK = 3;
export const UNIT_VALUE_COMPRESS = 4;
export const UNIT_VALUE_DECOMPRESS = 5;
export const UNIT_DECIMAL_WORK = 6;
export const UNIT_ROW_PRODUCED = 7;
export const UNIT_OPERATOR_EVAL = 8;
export const UNIT_HASH_BUILD = 9;
export const UNIT_HASH_PROBE = 10;
export const UNIT_AGGREGATE_ACCUMULATE = 11;
export const UNIT_CTE_SCAN_ROW = 12;
export const UNIT_GENERATED_ROW = 13;
export const UNIT_SEQUENCE_ADVANCE = 14;
export const UNIT_GIN_ENTRY = 15;
export const UNIT_GIST_DESCENT = 16;
export const UNIT_COLLATE = 17;
export const UNIT_TIMEZONE = 18;
export const UNIT_REGEX_COMPILE = 19;
export const UNIT_REGEX_STEP = 20;
export const UNIT_WINDOW_RESULT = 21;
export const UNIT_VARLEN_COMPARE = 22;
export const UNIT_WINDOW_FRAME_STEP = 23;
export const ESTIMATOR_UNIT_IDS = [
  "storage_row_read",
  "statistics_value",
  "page_read",
  "constraint_check",
  "value_compress",
  "value_decompress",
  "decimal_work",
  "row_produced",
  "operator_eval",
  "hash_build",
  "hash_probe",
  "aggregate_accumulate",
  "cte_scan_row",
  "generated_row",
  "sequence_advance",
  "gin_entry",
  "gist_descent",
  "collate",
  "timezone",
  "regex_compile",
  "regex_step",
  "window_result",
  "varlen_compare",
  "window_frame_step",
] as const;
export const ESTIMATOR_UNIT_WEIGHTS = [
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
  1n,
] as const;
