// @generated by scripts/gen_catalog.rb from spec/functions/catalog.toml — DO NOT EDIT.
//
// Operator descriptor table (CLAUDE.md §5: the codegen "middle path"). DATA only — the
// parser, executor, and the eq3/lt3 evaluation logic that CONSUME it are hand-written
// (§5 forbids codegenning those). Regenerate with `rake codegen`; `rake verify` fails
// if this file is stale. Reasoning: ../../../spec/design/codegen.md.

// One operator's metadata, mirroring a [[operator]] entry in catalog.toml. `symbol` is
// absent for operators with no infix symbol (the IS [NOT] NULL tests).
export interface OperatorDesc {
  name: string;
  symbol?: string;
  kind: string;
  arity: number;
  argFamilies: readonly string[];
  argResolution: string;
  result: string;
  null: string;
  errors: readonly string[];
}

// Every operator in the catalog, in catalog order.
export const OPERATORS: readonly OperatorDesc[] = [
  {
    name: "eq",
    symbol: "=",
    kind: "comparison",
    arity: 2,
    argFamilies: ["integer", "integer"],
    argResolution: "promote",
    result: "truth",
    null: "propagates",
    errors: [],
  },
  {
    name: "lt",
    symbol: "<",
    kind: "comparison",
    arity: 2,
    argFamilies: ["integer", "integer"],
    argResolution: "promote",
    result: "truth",
    null: "propagates",
    errors: [],
  },
  {
    name: "gt",
    symbol: ">",
    kind: "comparison",
    arity: 2,
    argFamilies: ["integer", "integer"],
    argResolution: "promote",
    result: "truth",
    null: "propagates",
    errors: [],
  },
  {
    name: "le",
    symbol: "<=",
    kind: "comparison",
    arity: 2,
    argFamilies: ["integer", "integer"],
    argResolution: "promote",
    result: "truth",
    null: "propagates",
    errors: [],
  },
  {
    name: "ge",
    symbol: ">=",
    kind: "comparison",
    arity: 2,
    argFamilies: ["integer", "integer"],
    argResolution: "promote",
    result: "truth",
    null: "propagates",
    errors: [],
  },
  {
    name: "is_null",
    kind: "null_test",
    arity: 1,
    argFamilies: ["any"],
    argResolution: "none",
    result: "truth",
    null: "detects",
    errors: [],
  },
  {
    name: "is_not_null",
    kind: "null_test",
    arity: 1,
    argFamilies: ["any"],
    argResolution: "none",
    result: "truth",
    null: "detects",
    errors: [],
  },
];
