// @generated by scripts/gen_catalog.rb from spec/types/ranges.toml — DO NOT EDIT.
//
// Range-type descriptor table (CLAUDE.md §4/§5): the six built-in PostgreSQL range
// types as DATA. The recursive value codec / comparator / text-I/O / canonicalize rule
// that CONSUME this are hand-written per core (§5 forbids codegenning them; derived from
// the element type, byte-identical by construction). Regenerate with `rake codegen`;
// `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/ranges.md.

// One range type's metadata, mirroring a [[range]] entry in spec/types/ranges.toml.
// `element` is a scalar id (the subtype the range is built over); `discrete` marks an
// integer/date subtype stored in canonical `[)` form.
export interface RangeDesc {
  id: string;
  element: string;
  aliases: readonly string[];
  discrete: boolean;
}

// Every built-in range type, in ranges.toml order.
export const RANGES: readonly RangeDesc[] = [
  {
    id: "i32range",
    element: "i32",
    aliases: ["int4range"],
    discrete: true,
  },
  {
    id: "i64range",
    element: "i64",
    aliases: ["int8range"],
    discrete: true,
  },
  {
    id: "numrange",
    element: "decimal",
    aliases: [],
    discrete: false,
  },
  {
    id: "tsrange",
    element: "timestamp",
    aliases: [],
    discrete: false,
  },
  {
    id: "tstzrange",
    element: "timestamptz",
    aliases: [],
    discrete: false,
  },
  {
    id: "daterange",
    element: "date",
    aliases: [],
    discrete: true,
  },
];
