// @generated by scripts/gen_errors.rb from spec/errors/registry.toml — DO NOT EDIT.
//
// SQLSTATE error codes (CLAUDE.md §5, §10: the codegen "middle path"). DATA only — the
// EngineError scaffolding that CONSUMES these (message assembly, the raise sites through the
// executor) is hand-written in errors.ts (§5 forbids codegenning those). Regenerate with
// `rake codegen`; `rake verify` fails if this file is stale. Each variant's message template +
// rationale live in spec/errors/registry.toml. Reasoning: ../../../spec/design/codegen.md.
//
// SqlState is a string-literal union (not a TS enum — the elidable subset forbids enums), and
// the union member IS the canonical snake_case name from the registry.

export type SqlState =
  | "cardinality_violation" // 21000 — more than one row returned by a subquery used as an expression
  | "data_exception" // 22000 — {detail}
  | "string_data_right_truncation" // 22001 — {detail}
  | "numeric_value_out_of_range" // 22003 — value out of range for type {type}
  | "null_value_not_allowed" // 22004 — {detail}
  | "invalid_datetime_format" // 22007 — invalid input syntax for type {type}: {detail}
  | "datetime_field_overflow" // 22008 — date/time field value out of range: {detail}
  | "division_by_zero" // 22012 — division by zero
  | "invalid_argument_for_ntile" // 22014 — argument of ntile must be greater than zero
  | "invalid_argument_for_nth_value" // 22016 — argument of nth_value must be greater than zero
  | "substring_error" // 22011 — negative substring length not allowed
  | "invalid_argument_for_width_bucket_function" // 2201G — {detail}
  | "invalid_argument_for_log" // 2201E — {detail}
  | "invalid_argument_for_power_function" // 2201F — {detail}
  | "invalid_preceding_or_following_size" // 22013 — frame starting or ending offset must not be negative
  | "sequence_generator_limit_exceeded" // 2200H — nextval: reached {bound} value of sequence {sequence}
  | "invalid_row_count_in_limit_clause" // 2201W — LIMIT must not be negative
  | "invalid_row_count_in_offset_clause" // 2201X — OFFSET must not be negative
  | "invalid_parameter_value" // 22023 — invalid parameter value: {detail}
  | "invalid_escape_sequence" // 22025 — LIKE pattern must not end with escape character
  | "invalid_regular_expression" // 2201B — invalid regular expression: {detail}
  | "array_subscript_error" // 2202E — {detail}
  | "duplicate_json_object_key_value" // 22030 — duplicate JSON object key value
  | "sql_json_item_cannot_be_cast_to_target_type" // 2203A — {detail}
  | "sql_json_object_not_found" // 2203C — {detail}
  | "sql_json_member_not_found" // 2203F — {detail}
  | "invalid_argument_for_sql_json_datetime_function" // 22031 — {detail}
  | "invalid_sql_json_subscript" // 22033 — {detail}
  | "more_than_one_sql_json_item" // 22034 — {detail}
  | "no_sql_json_item" // 22035 — {detail}
  | "non_numeric_sql_json_item" // 22036 — {detail}
  | "singleton_sql_json_item_required" // 22038 — {detail}
  | "invalid_text_representation" // 22P02 — invalid input syntax for type {type}: {detail}
  | "not_null_violation" // 23502 — null value in column {name} violates not-null constraint
  | "unique_violation" // 23505 — duplicate key value violates unique constraint: {name}
  | "check_violation" // 23514 — new row for relation {table} violates check constraint {name}
  | "foreign_key_violation" // 23503 — insert or update on table {table} violates foreign key constraint {name}
  | "exclusion_violation" // 23P01 — conflicting key value violates exclusion constraint: {name}
  | "active_sql_transaction" // 25001 — there is already a transaction in progress
  | "read_only_sql_transaction" // 25006 — cannot execute {statement} in a read-only transaction
  | "in_failed_sql_transaction" // 25P02 — current transaction is aborted, commands ignored until end of transaction block
  | "dependent_objects_still_exist" // 2BP01 — cannot drop type {name} because other objects depend on it: {detail}
  | "syntax_error" // 42601 — syntax error: {detail}
  | "undefined_table" // 42P01 — table does not exist: {name}
  | "undefined_column" // 42703 — column does not exist: {name}
  | "ambiguous_column" // 42702 — column reference {name} is ambiguous
  | "undefined_object" // 42704 — {kind} does not exist: {name}
  | "invalid_column_reference" // 42P10 — for SELECT DISTINCT, ORDER BY expressions must appear in select list
  | "datatype_mismatch" // 42804 — datatype mismatch: {detail}
  | "invalid_foreign_key" // 42830 — there is no unique constraint matching given keys for referenced table {name}
  | "duplicate_column" // 42701 — duplicate column name: {name}
  | "duplicate_alias" // 42712 — table name {name} specified more than once
  | "duplicate_table" // 42P07 — relation already exists: {name}
  | "invalid_table_definition" // 42P16 — invalid table definition: {detail}
  | "grouping_error" // 42803 — column {name} must appear in the GROUP BY clause or be used in an aggregate function
  | "undefined_function" // 42883 — function does not exist: {name}
  | "duplicate_function" // 42723 — duplicate function: {detail}
  | "indeterminate_datatype" // 42P18 — could not determine data type of parameter ${index}
  | "invalid_recursion" // 42P19 — {detail}
  | "undefined_parameter" // 42P02 — there is no parameter ${index}
  | "invalid_object_definition" // 42P17 — functions in index expression must be marked IMMUTABLE
  | "windowing_error" // 42P20 — {detail}
  | "collation_mismatch" // 42P21 — collation mismatch between explicit collations {left} and {right}
  | "indeterminate_collation" // 42P22 — could not determine which collation to use for string comparison
  | "duplicate_object" // 42710 — constraint {name} for relation {table} already exists
  | "reserved_name" // 42939 — {kind} name {name} is reserved (the jed_ prefix is reserved for system objects)
  | "wrong_object_type" // 42809 — {name} is not {kind}
  | "name_too_long" // 42622 — identifier exceeds the maximum length of {max} bytes
  | "generated_always" // 428C9 — {detail}
  | "insufficient_privilege" // 42501 — permission denied for {object}
  | "feature_not_supported" // 0A000 — feature not supported: {detail}
  | "program_limit_exceeded" // 54000 — SQL statement exceeds the maximum length of {max} bytes
  | "statement_too_complex" // 54001 — statement too complex: nesting depth exceeds the maximum of {max}
  | "cost_limit_exceeded" // 54P01 — query exceeded the cost limit of {limit} (accrued {cost})
  | "session_cost_limit_exceeded" // 54P02 — session exceeded the lifetime cost limit of {limit} (accrued {cost})
  | "temp_storage_limit_exceeded" // 54P03 — temporary table storage exceeded the limit of {limit} bytes
  | "object_not_in_prerequisite_state" // 55000 — {detail}
  | "object_in_use" // 55006 — {detail}
  | "lock_not_available" // 55P03 — could not obtain the database writer lock
  | "query_canceled" // 57014 — canceling statement due to user request
  | "io_error" // 58030 — I/O error: {detail}
  | "undefined_file" // 58P01 — database file does not exist: {path}
  | "duplicate_file" // 58P02 — database file already exists: {path}
  | "data_corrupted" // XX001 — on-disk database file is malformed: {detail}
  | "collation_version_mismatch"; // XX002 — collation version mismatch: {detail}

const CODES: Record<SqlState, string> = {
  cardinality_violation: "21000",
  data_exception: "22000",
  string_data_right_truncation: "22001",
  numeric_value_out_of_range: "22003",
  null_value_not_allowed: "22004",
  invalid_datetime_format: "22007",
  datetime_field_overflow: "22008",
  division_by_zero: "22012",
  invalid_argument_for_ntile: "22014",
  invalid_argument_for_nth_value: "22016",
  substring_error: "22011",
  invalid_argument_for_width_bucket_function: "2201G",
  invalid_argument_for_log: "2201E",
  invalid_argument_for_power_function: "2201F",
  invalid_preceding_or_following_size: "22013",
  sequence_generator_limit_exceeded: "2200H",
  invalid_row_count_in_limit_clause: "2201W",
  invalid_row_count_in_offset_clause: "2201X",
  invalid_parameter_value: "22023",
  invalid_escape_sequence: "22025",
  invalid_regular_expression: "2201B",
  array_subscript_error: "2202E",
  duplicate_json_object_key_value: "22030",
  sql_json_item_cannot_be_cast_to_target_type: "2203A",
  sql_json_object_not_found: "2203C",
  sql_json_member_not_found: "2203F",
  invalid_argument_for_sql_json_datetime_function: "22031",
  invalid_sql_json_subscript: "22033",
  more_than_one_sql_json_item: "22034",
  no_sql_json_item: "22035",
  non_numeric_sql_json_item: "22036",
  singleton_sql_json_item_required: "22038",
  invalid_text_representation: "22P02",
  not_null_violation: "23502",
  unique_violation: "23505",
  check_violation: "23514",
  foreign_key_violation: "23503",
  exclusion_violation: "23P01",
  active_sql_transaction: "25001",
  read_only_sql_transaction: "25006",
  in_failed_sql_transaction: "25P02",
  dependent_objects_still_exist: "2BP01",
  syntax_error: "42601",
  undefined_table: "42P01",
  undefined_column: "42703",
  ambiguous_column: "42702",
  undefined_object: "42704",
  invalid_column_reference: "42P10",
  datatype_mismatch: "42804",
  invalid_foreign_key: "42830",
  duplicate_column: "42701",
  duplicate_alias: "42712",
  duplicate_table: "42P07",
  invalid_table_definition: "42P16",
  grouping_error: "42803",
  undefined_function: "42883",
  duplicate_function: "42723",
  indeterminate_datatype: "42P18",
  invalid_recursion: "42P19",
  undefined_parameter: "42P02",
  invalid_object_definition: "42P17",
  windowing_error: "42P20",
  collation_mismatch: "42P21",
  indeterminate_collation: "42P22",
  duplicate_object: "42710",
  reserved_name: "42939",
  wrong_object_type: "42809",
  name_too_long: "42622",
  generated_always: "428C9",
  insufficient_privilege: "42501",
  feature_not_supported: "0A000",
  program_limit_exceeded: "54000",
  statement_too_complex: "54001",
  cost_limit_exceeded: "54P01",
  session_cost_limit_exceeded: "54P02",
  temp_storage_limit_exceeded: "54P03",
  object_not_in_prerequisite_state: "55000",
  object_in_use: "55006",
  lock_not_available: "55P03",
  query_canceled: "57014",
  io_error: "58030",
  undefined_file: "58P01",
  duplicate_file: "58P02",
  data_corrupted: "XX001",
  collation_version_mismatch: "XX002",
};

// sqlStateCode returns the canonical SQLSTATE string for a state.
export function sqlStateCode(state: SqlState): string {
  return CODES[state];
}

// One error's metadata, mirroring an [[error]] entry in registry.toml. The union above is
// the type-safe code (and CODES its O(1) lookup); ERRORS is the iterable data table the
// cross-check tests walk against the registry.
export interface ErrorDesc {
  code: string;
  name: string;
  class: string;
}

// Every error, in registry order.
export const ERRORS: readonly ErrorDesc[] = [
  { code: "21000", name: "cardinality_violation", class: "cardinality violation" },
  { code: "22000", name: "data_exception", class: "data exception" },
  { code: "22001", name: "string_data_right_truncation", class: "data exception" },
  { code: "22003", name: "numeric_value_out_of_range", class: "data exception" },
  { code: "22004", name: "null_value_not_allowed", class: "data exception" },
  { code: "22007", name: "invalid_datetime_format", class: "data exception" },
  { code: "22008", name: "datetime_field_overflow", class: "data exception" },
  { code: "22012", name: "division_by_zero", class: "data exception" },
  { code: "22014", name: "invalid_argument_for_ntile", class: "data exception" },
  { code: "22016", name: "invalid_argument_for_nth_value", class: "data exception" },
  { code: "22011", name: "substring_error", class: "data exception" },
  { code: "2201G", name: "invalid_argument_for_width_bucket_function", class: "data exception" },
  { code: "2201E", name: "invalid_argument_for_log", class: "data exception" },
  { code: "2201F", name: "invalid_argument_for_power_function", class: "data exception" },
  { code: "22013", name: "invalid_preceding_or_following_size", class: "data exception" },
  { code: "2200H", name: "sequence_generator_limit_exceeded", class: "data exception" },
  { code: "2201W", name: "invalid_row_count_in_limit_clause", class: "data exception" },
  { code: "2201X", name: "invalid_row_count_in_offset_clause", class: "data exception" },
  { code: "22023", name: "invalid_parameter_value", class: "data exception" },
  { code: "22025", name: "invalid_escape_sequence", class: "data exception" },
  { code: "2201B", name: "invalid_regular_expression", class: "data exception" },
  { code: "2202E", name: "array_subscript_error", class: "data exception" },
  { code: "22030", name: "duplicate_json_object_key_value", class: "data exception" },
  { code: "2203A", name: "sql_json_item_cannot_be_cast_to_target_type", class: "data exception" },
  { code: "2203C", name: "sql_json_object_not_found", class: "data exception" },
  { code: "2203F", name: "sql_json_member_not_found", class: "data exception" },
  { code: "22031", name: "invalid_argument_for_sql_json_datetime_function", class: "data exception" },
  { code: "22033", name: "invalid_sql_json_subscript", class: "data exception" },
  { code: "22034", name: "more_than_one_sql_json_item", class: "data exception" },
  { code: "22035", name: "no_sql_json_item", class: "data exception" },
  { code: "22036", name: "non_numeric_sql_json_item", class: "data exception" },
  { code: "22038", name: "singleton_sql_json_item_required", class: "data exception" },
  { code: "22P02", name: "invalid_text_representation", class: "data exception" },
  { code: "23502", name: "not_null_violation", class: "integrity constraint violation" },
  { code: "23505", name: "unique_violation", class: "integrity constraint violation" },
  { code: "23514", name: "check_violation", class: "integrity constraint violation" },
  { code: "23503", name: "foreign_key_violation", class: "integrity constraint violation" },
  { code: "23P01", name: "exclusion_violation", class: "integrity constraint violation" },
  { code: "25001", name: "active_sql_transaction", class: "invalid transaction state" },
  { code: "25006", name: "read_only_sql_transaction", class: "invalid transaction state" },
  { code: "25P02", name: "in_failed_sql_transaction", class: "invalid transaction state" },
  { code: "2BP01", name: "dependent_objects_still_exist", class: "dependent objects still exist" },
  { code: "42601", name: "syntax_error", class: "syntax error or access rule violation" },
  { code: "42P01", name: "undefined_table", class: "syntax error or access rule violation" },
  { code: "42703", name: "undefined_column", class: "syntax error or access rule violation" },
  { code: "42702", name: "ambiguous_column", class: "syntax error or access rule violation" },
  { code: "42704", name: "undefined_object", class: "syntax error or access rule violation" },
  { code: "42P10", name: "invalid_column_reference", class: "syntax error or access rule violation" },
  { code: "42804", name: "datatype_mismatch", class: "syntax error or access rule violation" },
  { code: "42830", name: "invalid_foreign_key", class: "syntax error or access rule violation" },
  { code: "42701", name: "duplicate_column", class: "syntax error or access rule violation" },
  { code: "42712", name: "duplicate_alias", class: "syntax error or access rule violation" },
  { code: "42P07", name: "duplicate_table", class: "syntax error or access rule violation" },
  { code: "42P16", name: "invalid_table_definition", class: "syntax error or access rule violation" },
  { code: "42803", name: "grouping_error", class: "syntax error or access rule violation" },
  { code: "42883", name: "undefined_function", class: "syntax error or access rule violation" },
  { code: "42723", name: "duplicate_function", class: "syntax error or access rule violation" },
  { code: "42P18", name: "indeterminate_datatype", class: "syntax error or access rule violation" },
  { code: "42P19", name: "invalid_recursion", class: "syntax error or access rule violation" },
  { code: "42P02", name: "undefined_parameter", class: "syntax error or access rule violation" },
  { code: "42P17", name: "invalid_object_definition", class: "syntax error or access rule violation" },
  { code: "42P20", name: "windowing_error", class: "syntax error or access rule violation" },
  { code: "42P21", name: "collation_mismatch", class: "syntax error or access rule violation" },
  { code: "42P22", name: "indeterminate_collation", class: "syntax error or access rule violation" },
  { code: "42710", name: "duplicate_object", class: "syntax error or access rule violation" },
  { code: "42939", name: "reserved_name", class: "syntax error or access rule violation" },
  { code: "42809", name: "wrong_object_type", class: "syntax error or access rule violation" },
  { code: "42622", name: "name_too_long", class: "syntax error or access rule violation" },
  { code: "428C9", name: "generated_always", class: "syntax error or access rule violation" },
  { code: "42501", name: "insufficient_privilege", class: "syntax error or access rule violation" },
  { code: "0A000", name: "feature_not_supported", class: "feature not supported" },
  { code: "54000", name: "program_limit_exceeded", class: "program limit exceeded" },
  { code: "54001", name: "statement_too_complex", class: "program limit exceeded" },
  { code: "54P01", name: "cost_limit_exceeded", class: "program limit exceeded" },
  { code: "54P02", name: "session_cost_limit_exceeded", class: "program limit exceeded" },
  { code: "54P03", name: "temp_storage_limit_exceeded", class: "program limit exceeded" },
  { code: "55000", name: "object_not_in_prerequisite_state", class: "object not in prerequisite state" },
  { code: "55006", name: "object_in_use", class: "object not in prerequisite state" },
  { code: "55P03", name: "lock_not_available", class: "object not in prerequisite state" },
  { code: "57014", name: "query_canceled", class: "operator intervention" },
  { code: "58030", name: "io_error", class: "system error" },
  { code: "58P01", name: "undefined_file", class: "system error" },
  { code: "58P02", name: "duplicate_file", class: "system error" },
  { code: "XX001", name: "data_corrupted", class: "internal error" },
  { code: "XX002", name: "collation_version_mismatch", class: "internal error" },
];
