// IDENTITY columns (spec/design/sequences.md §13) — the per-core unit tests for what the PG-clean
// oracle corpus cannot express (CLAUDE.md §10): the on-disk persistence of the ALWAYS/BY DEFAULT
// distinction (the 428C9 gate still fires after a close/open) and the auto-named owned-sequence
// auto-drop. The PG-agreeing behavior (auto-numbering, OVERRIDING SYSTEM/USER, 428C9, the 42601
// conflicts, the 22023 type gate, and — since S5, §14 — the owned sequence following the column
// type) lives in suites/ddl/identity.test + suites/ddl/sequence_as_type.test. Mirrors
// impl/rust/tests/identity.rs.

import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { close, commit, create, Database, EngineError, execute, open } from "../src/lib.ts";

// oneInt runs a single-column SELECT and returns its one int value, or null for a NULL value.
function oneInt(db: Database, sql: string): bigint | null {
  const o = execute(db, sql);
  if (o.kind !== "query") throw new Error(`expected a query, got ${o.kind}`);
  const v = o.rows[0]![0]!;
  if (v.kind === "int") return v.int;
  if (v.kind === "null") return null;
  throw new Error(`expected int/null, got ${v.kind}`);
}

// errCode runs sql and returns the SQLSTATE of the EngineError it throws.
function errCode(db: Database, sql: string): string {
  try {
    execute(db, sql);
  } catch (e) {
    if (e instanceof EngineError) return e.code();
    throw e;
  }
  throw new Error(`expected an EngineError from ${sql}`);
}

// queryRows runs sql and returns its rows' int cells (throwing on a NULL/non-int cell).
function queryRows(db: Database, sql: string): bigint[][] {
  const o = execute(db, sql);
  if (o.kind !== "query") throw new Error(`expected a query, got ${o.kind}`);
  return o.rows.map((r) =>
    r.map((v) => {
      if (v.kind !== "int") throw new Error(`expected int, got ${v.kind}`);
      return v.int;
    }),
  );
}

// An IDENTITY column desugars to an integer column, NOT NULL, with a nextval default backed by an
// auto-created OWNED sequence named <table>_<col>_seq (same machinery as serial, sequences.md §13).
// Two columns — one ALWAYS, one BY DEFAULT — each get their own owned sequence.
test("identity desugars to owned sequences", () => {
  const db = new Database();
  execute(
    db,
    "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, " +
      "n int GENERATED BY DEFAULT AS IDENTITY, v text)",
  );
  assert.deepEqual(queryRows(db, "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id, n"), [
    [1n, 1n],
    [2n, 2n],
  ]);
  // The owned sequences exist under PG's derived names and keep advancing.
  assert.equal(oneInt(db, "SELECT nextval('t_id_seq')"), 3n);
  assert.equal(oneInt(db, "SELECT nextval('t_n_seq')"), 3n);
});

// The ALWAYS/BY DEFAULT distinction persists (format_version 15, the two column flag bits): after
// create + commit + reopen, the ALWAYS column still rejects an explicit value (428C9) and the BY
// DEFAULT column still accepts one — proving the bits round-tripped through the catalog bytes.
test("identity kind survives reopen", () => {
  const dir = mkdtempSync(join(tmpdir(), "jed-identity-"));
  const path = join(dir, "identity_reopen.jed");
  try {
    const db = create(path);
    execute(
      db,
      "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, " +
        "n int GENERATED BY DEFAULT AS IDENTITY, v text)",
    );
    execute(db, "INSERT INTO t (v) VALUES ('a')");
    commit(db);
    close(db);

    const db2 = open(path);
    // ALWAYS still rejects an explicit value (the bit round-tripped).
    assert.equal(errCode(db2, "INSERT INTO t (id, v) VALUES (5, 'x')"), "428C9");
    // ...but OVERRIDING SYSTEM VALUE still lets it through.
    execute(db2, "INSERT INTO t (id, v) OVERRIDING SYSTEM VALUE VALUES (5, 'x')");
    // BY DEFAULT still accepts an explicit value with no override.
    execute(db2, "INSERT INTO t (n, v) VALUES (9, 'y')");
    // The owner link round-tripped too: still 2BP01 to drop the sequence directly.
    assert.equal(errCode(db2, "DROP SEQUENCE t_id_seq"), "2BP01");
    commit(db2);
    close(db2);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// DROP TABLE auto-drops every IDENTITY column's owned sequence (the OWNED BY link, sequences.md
// §13/§12.3), exactly as for serial.
test("identity owned sequences auto-drop", () => {
  const db = new Database();
  execute(
    db,
    "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, n bigint GENERATED BY DEFAULT AS IDENTITY)",
  );
  assert.equal(errCode(db, "DROP SEQUENCE t_id_seq"), "2BP01");
  execute(db, "DROP TABLE t");
  assert.equal(errCode(db, "SELECT nextval('t_id_seq')"), "42P01");
  assert.equal(errCode(db, "SELECT nextval('t_n_seq')"), "42P01");
});

// S5 (§14): an IDENTITY column's owned sequence follows the column type — a smallint GENERATED …
// AS IDENTITY gets an AS smallint sequence bounded to [1, 32767] (matching PG; the prior
// bigint-flavored divergence is closed). Introspects the auto-created sequence via its derived name:
// setval past 32767 is 22003, and nextval at the boundary traps 2200H — the sequence itself is now
// bounded (the corpus pins the boundary too, but the auto-name wiring stays a per-core check).
test("identity owned sequence follows column type", () => {
  const db = new Database();
  execute(db, "CREATE TABLE t (id smallint GENERATED ALWAYS AS IDENTITY, v text)");
  // The owned sequence is AS smallint: setval past the i16 max is out of bounds (22003).
  assert.equal(errCode(db, "SELECT setval('t_id_seq', 40000)"), "22003");
  // At the boundary, the next value overflows the sequence (2200H) — not the column (the i16
  // sequence stops here, exactly as PG).
  execute(db, "SELECT setval('t_id_seq', 32767)");
  assert.equal(errCode(db, "SELECT nextval('t_id_seq')"), "2200H");
});

// The identity sequence options ( … ) tune the owned sequence (a per-core check that the option set
// threads through the desugaring — the values themselves are PG-clean and also in the corpus).
test("identity with sequence options", () => {
  const db = new Database();
  execute(
    db,
    "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 5), v text)",
  );
  assert.deepEqual(queryRows(db, "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id"), [
    [100n],
    [105n],
  ]);
});
