// IDENTITY columns (spec/design/sequences.md §13) — the per-core unit tests for what the PG-clean
// oracle corpus cannot express (CLAUDE.md §10): the on-disk persistence of the ALWAYS/BY DEFAULT
// distinction (the 428C9 gate still fires after a close/open), the auto-named owned sequence
// introspection, and the bigint-flavored owned sequence divergence (decision 11). The PG-agreeing
// behavior (auto-numbering, OVERRIDING SYSTEM/USER, 428C9, the 42601 conflicts, the 22023 type
// gate) lives in suites/ddl/identity.test. Mirrors impl/rust/tests/identity.rs.

import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { close, commit, create, Database, EngineError, execute, open } from "../src/lib.ts";

// oneInt runs a single-column SELECT and returns its one int value, or null for a NULL value.
function oneInt(db: Database, sql: string): bigint | null {
  const o = execute(db, sql);
  if (o.kind !== "query") throw new Error(`expected a query, got ${o.kind}`);
  const v = o.rows[0]![0]!;
  if (v.kind === "int") return v.int;
  if (v.kind === "null") return null;
  throw new Error(`expected int/null, got ${v.kind}`);
}

// errCode runs sql and returns the SQLSTATE of the EngineError it throws.
function errCode(db: Database, sql: string): string {
  try {
    execute(db, sql);
  } catch (e) {
    if (e instanceof EngineError) return e.code();
    throw e;
  }
  throw new Error(`expected an EngineError from ${sql}`);
}

// queryRows runs sql and returns its rows' int cells (throwing on a NULL/non-int cell).
function queryRows(db: Database, sql: string): bigint[][] {
  const o = execute(db, sql);
  if (o.kind !== "query") throw new Error(`expected a query, got ${o.kind}`);
  return o.rows.map((r) =>
    r.map((v) => {
      if (v.kind !== "int") throw new Error(`expected int, got ${v.kind}`);
      return v.int;
    }),
  );
}

// An IDENTITY column desugars to an integer column, NOT NULL, with a nextval default backed by an
// auto-created OWNED sequence named <table>_<col>_seq (same machinery as serial, sequences.md §13).
// Two columns — one ALWAYS, one BY DEFAULT — each get their own owned sequence.
test("identity desugars to owned sequences", () => {
  const db = new Database();
  execute(
    db,
    "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, " +
      "n int GENERATED BY DEFAULT AS IDENTITY, v text)",
  );
  assert.deepEqual(queryRows(db, "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id, n"), [
    [1n, 1n],
    [2n, 2n],
  ]);
  // The owned sequences exist under PG's derived names and keep advancing.
  assert.equal(oneInt(db, "SELECT nextval('t_id_seq')"), 3n);
  assert.equal(oneInt(db, "SELECT nextval('t_n_seq')"), 3n);
});

// The ALWAYS/BY DEFAULT distinction persists (format_version 15, the two column flag bits): after
// create + commit + reopen, the ALWAYS column still rejects an explicit value (428C9) and the BY
// DEFAULT column still accepts one — proving the bits round-tripped through the catalog bytes.
test("identity kind survives reopen", () => {
  const dir = mkdtempSync(join(tmpdir(), "jed-identity-"));
  const path = join(dir, "identity_reopen.jed");
  try {
    const db = create(path);
    execute(
      db,
      "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, " +
        "n int GENERATED BY DEFAULT AS IDENTITY, v text)",
    );
    execute(db, "INSERT INTO t (v) VALUES ('a')");
    commit(db);
    close(db);

    const db2 = open(path);
    // ALWAYS still rejects an explicit value (the bit round-tripped).
    assert.equal(errCode(db2, "INSERT INTO t (id, v) VALUES (5, 'x')"), "428C9");
    // ...but OVERRIDING SYSTEM VALUE still lets it through.
    execute(db2, "INSERT INTO t (id, v) OVERRIDING SYSTEM VALUE VALUES (5, 'x')");
    // BY DEFAULT still accepts an explicit value with no override.
    execute(db2, "INSERT INTO t (n, v) VALUES (9, 'y')");
    // The owner link round-tripped too: still 2BP01 to drop the sequence directly.
    assert.equal(errCode(db2, "DROP SEQUENCE t_id_seq"), "2BP01");
    commit(db2);
    close(db2);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// DROP TABLE auto-drops every IDENTITY column's owned sequence (the OWNED BY link, sequences.md
// §13/§12.3), exactly as for serial.
test("identity owned sequences auto-drop", () => {
  const db = new Database();
  execute(
    db,
    "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, n bigint GENERATED BY DEFAULT AS IDENTITY)",
  );
  assert.equal(errCode(db, "DROP SEQUENCE t_id_seq"), "2BP01");
  execute(db, "DROP TABLE t");
  assert.equal(errCode(db, "SELECT nextval('t_id_seq')"), "42P01");
  assert.equal(errCode(db, "SELECT nextval('t_n_seq')"), "42P01");
});

// DIVERGENCE (decision 11): an IDENTITY column's owned sequence is bigint-flavored regardless of the
// column width — a smallint GENERATED … AS IDENTITY gets a default i64 sequence (MAXVALUE 2^63-1),
// not PG's smallint sequence (MAXVALUE 32767). Advancing the sequence past 32767 succeeds in jed
// where PG would raise 2200H; the narrower column type only bounds stored values (22003 at INSERT).
test("identity owned sequence is bigint-flavored", () => {
  const db = new Database();
  execute(db, "CREATE TABLE t (id smallint GENERATED ALWAYS AS IDENTITY, v text)");
  // Drive the owned sequence past the i16 max directly — jed allows it (bigint sequence); PG's
  // smallint identity sequence would 2200H here.
  execute(db, "SELECT setval('t_id_seq', 40000)");
  assert.equal(oneInt(db, "SELECT nextval('t_id_seq')"), 40001n);
  // The column type still bounds a stored value: an INSERT pulling 40001 traps 22003 (the column is
  // i16), the documented divergence point (PG's 2200H lives at the sequence instead).
  assert.equal(errCode(db, "INSERT INTO t (v) VALUES ('a')"), "22003");
});

// The identity sequence options ( … ) tune the owned sequence (a per-core check that the option set
// threads through the desugaring — the values themselves are PG-clean and also in the corpus).
test("identity with sequence options", () => {
  const db = new Database();
  execute(
    db,
    "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 5), v text)",
  );
  assert.deepEqual(queryRows(db, "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id"), [
    [100n],
    [105n],
  ]);
});
