// Code generated by scripts/vendor_collations.rb. DO NOT EDIT.
// The collation tables VENDORED into the TS core (spec/design/collation.md §9): the
// .coll artifacts inlined as base64 so the core stays browser-safe (no node:fs). Synced
// from spec/collation/fixtures; `rake verify` checks drift.

export const VENDORED_COLL: Record<string, string> = {
  "dev-root": "SkNPTEwAAAEACGRldi1yb290AAkwLjAuMC1kZXYAAAAADuPPFQAAAI8AAABnYgEAAAAKAAEA8w4gAQECCQAgAAIAAABBAQAcRwAgAAgAAABCAQAcYAwAU1oBAB4LDAATYSQAADAAE2IkAAAMABN6JAAADAAmxAJIACEAR1sAE+QTAAAfAAETALAB9gABAEAAACAAAg==",
  "dev-nordic": "SkNPTEwAAAEACmRldi1ub3JkaWMACTAuMC4wLWRldgAAAABVhxSVAAAAgQAAAGFiAQAAAAoAAQDzDiABAQIJACAAAgAAAEEBABxHACAACAAAAEIBABxgDABTWgEAHgsMABNhJAAAMAATYiQAAAwAE3okAAAMAFPEAQAvBTAAE+QMANACAAH2AAEAQAAAIAAC",
};
