package jed

import (
	"math"
	"strings"
)

// Column is a column definition: name, declared type, nullability, primary-key flag.
type catColumn struct {
	Name string
	// Type is the column's declared type — a built-in scalar or a user-defined composite
	// (spec/design/composite.md). The open Type wrapper (CLAUDE.md §4): scalar-only call sites
	// read Type.ScalarTy(); the value codec / resolver branch on Type.IsComposite() (S2+).
	Type dataType
	// Decimal is the numeric(p,s) typmod for a decimal column, or nil for a non-decimal column
	// OR an unconstrained numeric (spec/design/decimal.md §2). A constrained decimal column
	// coerces stored values to this precision/scale.
	Decimal *decimalTypmod
	// VarcharLen is the varchar(n) max-length typmod for a text column, or nil for a non-text
	// column OR an unbounded text (spec/design/types.md §15). n counts code points; an
	// over-length assignment traps 22001. Persisted as a u32 in the typmod slot (type_code 4,
	// format_version 22).
	VarcharLen *uint32
	PrimaryKey bool
	// NotNull is implied true for a PRIMARY KEY column.
	NotNull bool
	// Default is the column's CONSTANT DEFAULT value, pre-evaluated and type-coerced at CREATE
	// TABLE, or nil if it has no default or an EXPRESSION default (DefaultExpr). A non-nil
	// pointer to a ValNull value is an explicit DEFAULT NULL. Applied for an omitted column or a
	// DEFAULT keyword at INSERT (spec/design/constraints.md §2).
	Default *Value
	// DefaultExpr is the column's EXPRESSION DEFAULT (a non-constant default like uuidv7() or
	// 1 + 1), or nil if it has no default or a constant default (Default). Mutually exclusive
	// with Default. Stored as expression text (re-rendered verbatim at every commit, like a
	// CHECK — spec/fileformat/format.md) plus the parsed expression the write paths resolve and
	// evaluate per row (spec/design/constraints.md §2).
	DefaultExpr *defaultExprDef
	// Identity records whether the column is a GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY column,
	// and which kind (spec/design/sequences.md §13). nil is a non-identity column. An identity column
	// also carries NotNull + a DefaultExpr (nextval of its owned sequence); the kind gates whether an
	// explicit INSERT/UPDATE value is accepted (428C9). Persisted as two column flag bits
	// (format_version 15: bit4 is_identity, bit5 identity_always).
	Identity *identityKind
	// Collation is the column's EFFECTIVE collation — "" is C (byte / code-point order, the
	// unchanged fast path), a non-empty name a loaded non-C collation (spec/design/collation.md §1).
	// Frozen at CREATE TABLE: an explicit COLLATE "name", else the per-database default as of
	// creation (PG-matching). Only a text column carries one. A column reference's IMPLICIT collation
	// in the derivation (42P22); persisted as column flag bit6 + a trailing name (format_version 17).
	Collation string
}

// IdentityKind is the kind of an IDENTITY column (spec/design/sequences.md §13). IdentityAlways
// (GENERATED ALWAYS) rejects an explicit INSERT/UPDATE value (428C9) unless overridden;
// IdentityByDefault (GENERATED BY DEFAULT) accepts one, behaving like serial. Persisted as flag
// bit5 identity_always (set ⇒ Always, clear ⇒ ByDefault), meaningful only with bit4 is_identity.
type identityKind int

const (
	identityAlways identityKind = iota
	identityByDefault
)

// DefaultExpr is a column's EXPRESSION DEFAULT (spec/design/constraints.md §2): its persisted
// expression text — written back verbatim at every commit so the catalog bytes are stable
// (spec/fileformat/format.md "Check-expression text") — and the parsed expression the write
// paths resolve (against an empty scope, no columns) and evaluate per inserted row. Modeled on
// CheckConstraint.
type defaultExprDef struct {
	ExprText string
	Expr     exprNode
}

// Table is a table definition.
type catTable struct {
	Name    string
	Columns []catColumn
	// PK is the primary-key member column ordinals in KEY order (which may differ from
	// declaration order — constraints.md §3; the v5 catalog persists this list). Empty =
	// no primary key (synthetic rowid keys). The per-column PrimaryKey flag is derived
	// membership convenience; this list is the authority for order.
	PK []int
	// Checks is the table's CHECK constraints in EVALUATION ORDER — ascending byte order
	// of the lowercased name (spec/design/constraints.md §4.4); the on-disk catalog stores
	// them in this same order. Empty for an unchecked table.
	Checks []checkConstraint
	// Indexes is the table's secondary indexes in ascending lowercased-name order (the
	// catalog's on-disk order and the planner's tie-break order — spec/design/indexes.md).
	Indexes []indexDef
	// ForeignKeys is the table's FOREIGN KEY constraints in ascending lowercased-name order
	// (the catalog's on-disk order and the child-side evaluation order —
	// spec/design/constraints.md §6.9). Empty for a table with none.
	ForeignKeys []foreignKey
	// Exclusions is the table's EXCLUDE constraints in ascending lowercased-name order (the
	// catalog's on-disk order — spec/design/gist.md §7/§8). Each is backed by a GiST index in
	// Indexes. Empty for a table with none.
	Exclusions []exclusionConstraint
}

// ExclusionOp is one element's operator in an EXCLUDE constraint (spec/design/gist.md §7) — the
// WITH operator of a (column WITH op) pair. ExclOverlaps is && (a range column, range_ops);
// ExclEqual is = (a fixed-width keyable scalar, the in-core btree_gist). Both are SYMMETRIC, the
// property an exclusion operator must have. Persisted as the v21 per-element strategy byte (&& = 0,
// = 1; format.md).
type exclusionOp int

const (
	// ExclOverlaps is && (range overlap), on-disk code 0.
	exclOverlaps exclusionOp = iota
	// ExclEqual is = (scalar equality), on-disk code 1.
	exclEqual
)

// ExclusionElement is one (column, operator) element of an EXCLUDE constraint — a member column
// ordinal into the owning table and its WITH operator. The element order matches the backing GiST
// index's column order (spec/design/gist.md §7/§8).
type exclusionElement struct {
	Column int
	Op     exclusionOp
}

// ExclusionConstraint is one EXCLUDE constraint (spec/design/gist.md §7): its (relation-namespace)
// name, the backing GiST index that enforces it (by name — the constraint IS its index, the
// UNIQUE-is-its-index model generalized to an explicit operator list), and the (column, operator)
// element vector the conjunction probe needs. Held in ascending lowercased-name order on the table.
// The NULL rule (§7) is enforced at probe time: a row with a NULL in any excluded column never
// conflicts.
type exclusionConstraint struct {
	Name string
	// Index is the backing GiST index's name (equal to Name for a GX3 constraint — it owns the index).
	Index    string
	Elements []exclusionElement
}

// FkAction is the persisted referential action for a foreign key's `ON DELETE` / `ON UPDATE`
// (spec/design/constraints.md §6.6).
type fkAction int

const (
	// FkNoAction is NO ACTION (the default), on-disk code 0.
	fkNoAction fkAction = iota
	// FkRestrict is RESTRICT, on-disk code 1.
	fkRestrict
	// FkCascade is CASCADE, on-disk code 2.
	fkCascade
	// FkSetNull is SET NULL, on-disk code 3.
	fkSetNull
	// FkSetDefault is SET DEFAULT, on-disk code 4.
	fkSetDefault
)

// ForeignKey is one resolved FOREIGN KEY constraint of a table (spec/design/constraints.md §6):
// its (per-table constraint-namespace) name, the referencing column ordinals into THIS table in
// list order, the referenced (parent) table name, the referenced column ordinals into the PARENT
// in list order (same length as Columns), and the referential actions. An FK owns no B-tree;
// enforcement probes the parent's PK store or a unique index (§6.4). Held in ascending
// lowercased-name order on the table (the catalog's on-disk order and the child-side evaluation
// order — §6.9).
type foreignKey struct {
	Name       string
	Columns    []int
	RefTable   string
	RefColumns []int
	OnDelete   fkAction
	OnUpdate   fkAction
}

// hostFuncDep is a HOST-FUNCTION DEPENDENCY persisted with an index whose key/predicate expression
// calls a host scalar function (spec/design/extensibility.md §8.1, format_version 31, delivery step
// 4). One entry per DISTINCT host-function signature the index's expressions reference; it is the
// RESOLVED dependency the file records so a reopening binary can detect that the registry now supplies
// a DIFFERENT implementation (a mismatch makes the index unusable — skipped for reads, refused for
// writes — never a silent stale-key read). Sorted by (Name, ArgTypes) when stored so registration
// order never leaks (CLAUDE.md §8).
type hostFuncDep struct {
	// Name is the (lowercased) SQL function name — the correlation key to a re-resolved reHostFunc node.
	Name string
	// ArgTypes is the exact scalar argument signature — with Name, identifies which overload this pins.
	ArgTypes []scalarType
	// Result is the declared scalar result type at CREATE INDEX (recorded for completeness).
	Result scalarType
	// ComponentID is the host's stable component identity at CREATE INDEX. Required for an
	// index-backing function; a reopen whose registry supplies a different one makes the index unusable.
	ComponentID string
	// SemanticVersion is the host's semantic version at CREATE INDEX. A reopen whose registry bumped it
	// forces a rebuild (the index unusable meanwhile), never a silent stale-key read.
	SemanticVersion uint32
}

// IndexKey is one index key element (spec/design/indexes.md §1): a bare column (by ordinal into
// the table's columns) or an expression over the table's columns (`lower(email)`), carrying its
// persisted canonical text and the re-parsed (unresolved) AST — the write/plan paths re-resolve it
// against the table per statement, exactly as a CHECK is re-resolved. Go has no sum types: Expr ==
// nil discriminates a column key (read Col) from an expression key (read Expr). Only a B-tree index
// may carry an expression element (GIN/GiST are single column, this slice).
type indexKey struct {
	Col  int
	Expr *indexKeyExpr
}

// indexKeyExpr is an index expression key's persisted text + parsed AST (modeled on
// checkConstraint / defaultExprDef).
type indexKeyExpr struct {
	ExprText string
	Expr     exprNode
}

// columnKeys wraps a plain column-ordinal list as index key elements (the common case — a
// column-only index built from a UNIQUE / GiST / auto-derived column list).
func columnKeys(cols []int) []indexKey {
	keys := make([]indexKey, len(cols))
	for i, c := range cols {
		keys[i] = indexKey{Col: c}
	}
	return keys
}

// asColumn returns the column ordinal if this is a plain column key, else (0, false) for an
// expression key.
func (k indexKey) asColumn() (int, bool) {
	if k.Expr != nil {
		return 0, false
	}
	return k.Col, true
}

// IndexDef is one secondary index of a table (spec/design/indexes.md): its
// (relation-namespace) name and its key elements in index-key order (columns and/or
// expressions, duplicates allowed — PG). The index's B-tree lives in the snapshot's
// index-store map, keyed by the lowercased name. A Unique index enforces uniqueness over its
// key tuple (NULLS DISTINCT — spec/design/indexes.md §8); it is what backs a UNIQUE constraint
// (spec/design/constraints.md §5).
type indexDef struct {
	Name   string
	Keys   []indexKey
	Unique bool
	Kind   indexKind
	// Predicate is a PARTIAL index's WHERE predicate (spec/design/indexes.md §9): only rows whose
	// predicate is TRUE are indexed / constrained. nil for an ordinary (full) index. Carries the
	// persisted canonical text + the re-parsed (unresolved) AST — re-resolved against the table per
	// statement, like an expression key (indexKeyExpr). Partial indexes are B-tree only.
	Predicate *indexKeyExpr
	// HostDeps are persisted HOST-FUNCTION dependencies (spec/design/extensibility.md §8.1,
	// format_version 31): one entry per distinct host scalar function this index's key/predicate
	// expressions call, each pinning the component identity + semantic version the index was built
	// against. nil for the common index with no host-function key (byte-identical to v30 then). On
	// reopen the per-statement re-resolution (resolveIndexWithParams) compares each against the current
	// registry; a mismatch makes the index unusable. Sorted by (Name, ArgTypes).
	HostDeps []hostFuncDep
}

// allColumns reports whether every key element is a plain column (no expression key) — the common
// case, and the GIN/GiST invariant. Lets column-only code paths fast-check.
func (d *indexDef) allColumns() bool {
	for _, k := range d.Keys {
		if k.Expr != nil {
			return false
		}
	}
	return true
}

// columnOrdinals returns the key elements' column ordinals if every element is a plain column, else
// nil (the index has at least one expression key). The many column-only consumers — the GIN/GiST
// entry builders, FK-target matching, introspection — use this; an expression key makes the index
// ineligible for those (an FK cannot target an expression index, etc.).
func (d *indexDef) columnOrdinals() []int {
	out := make([]int, 0, len(d.Keys))
	for _, k := range d.Keys {
		c, ok := k.asColumn()
		if !ok {
			return nil
		}
		out = append(out, c)
	}
	return out
}

// firstColumn returns the column ordinal of the first key element, assuming a single-column index —
// used by the GIN/GiST paths, which are always single-column plain-column indexes (this slice).
func (d *indexDef) firstColumn() int {
	c, ok := d.Keys[0].asColumn()
	if !ok {
		panic("GIN/GiST index key is a plain column")
	}
	return c
}

// SequenceDef is a sequence (spec/design/sequences.md): a named, persisted, monotonic i64
// generator — the third database-level catalog-object kind (after tables and composite types).
// The definition fields (Increment/MinValue/MaxValue/Start/Cache/Cycle) are immutable; LastValue
// + IsCalled are the mutable counter state a nextval advances. The whole struct lives in the
// snapshot catalog, so the counter is transactional by construction (sequences.md §5).
type sequenceDef struct {
	// Name is the sequence name (original case; looked up case-insensitively).
	Name string
	// Increment is the step per nextval (non-zero). Positive = ascending, negative = descending.
	Increment int64
	// MinValue is the inclusive lower bound.
	MinValue int64
	// MaxValue is the inclusive upper bound.
	MaxValue int64
	// Start is the first value nextval returns (on a fresh sequence, LastValue == Start).
	Start int64
	// Cache is the PostgreSQL CACHE size — stored for fidelity but behaves as 1 (sequences.md §7).
	Cache int64
	// Cycle is whether nextval wraps at a bound (CYCLE) instead of raising 2200H.
	Cycle bool
	// LastValue is the mutable counter: the most recent value produced (or Start before the first
	// call).
	LastValue int64
	// IsCalled is whether nextval has been called: false ⇒ the next call returns LastValue (=
	// Start) without incrementing; true ⇒ it adds Increment (PostgreSQL's is_called).
	IsCalled bool
	// OwnedBy is the OWNED BY link for a sequence created by a serial column
	// (spec/design/sequences.md §12) — non-nil records the owning table + column ordinal, nil for a
	// plain CREATE SEQUENCE. Persisted (format_version 13, the has_owner flag bit): it drives
	// DROP TABLE auto-drop and the DROP SEQUENCE 2BP01. A plain DEFAULT nextval('s') creates no
	// owner link (PG — sequences.md §10 decision 4).
	OwnedBy *seqOwner
}

// SeqOwner is the OWNED BY reference of a serial-created sequence (spec/design/sequences.md §12):
// the owning table (original case) and the owning column's 0-based ordinal. Persisted on the
// sequence catalog entry (format.md *Sequence entry*, v13).
type seqOwner struct {
	Table  string
	Column uint16
}

// SeqDataType is a sequence's value data type (`AS smallint | integer | bigint`,
// spec/design/sequences.md §14). Its only effect is on the bounds: it sets the default + validated
// MINVALUE/MAXVALUE. The counter is always an i64, and the type is not persisted (it is reducible to
// the bounds), so this is a parse/build-time concept only.
type seqDataType int

const (
	seqSmallInt seqDataType = iota
	seqInteger
	seqBigInt
)

// Range returns the inclusive value range [T_min, T_max] of the type (the natural i16/i32/i64 range).
func (t seqDataType) Range() (int64, int64) {
	switch t {
	case seqSmallInt:
		return math.MinInt16, math.MaxInt16
	case seqInteger:
		return math.MinInt32, math.MaxInt32
	default: // SeqBigInt
		return math.MinInt64, math.MaxInt64
	}
}

// PgName returns the PostgreSQL type name used in error messages (smallint / integer / bigint).
func (t seqDataType) PgName() string {
	switch t {
	case seqSmallInt:
		return "smallint"
	case seqInteger:
		return "integer"
	default: // SeqBigInt
		return "bigint"
	}
}

// DefaultBounds returns the type defaults for an ascending (increment > 0) vs descending sequence,
// before any explicit MIN/MAX/START override (PostgreSQL init_params): ascending ⇒ [1, T_max],
// start = MIN; descending ⇒ [T_min, -1], start = MAX.
func (t seqDataType) DefaultBounds(increment int64) (int64, int64) {
	lo, hi := t.Range()
	if increment < 0 {
		return lo, -1
	}
	return 1, hi
}

// SeqDataTypeFromName resolves an `AS <name>` type to a sequence data type. ok is false if the name
// is not an integer type (caller raises 22023 "sequence type must be smallint, integer, or bigint").
func seqDataTypeFromName(name string) (seqDataType, bool) {
	s, ok := scalarTypeFromName(name)
	if !ok {
		return 0, false
	}
	return seqDataTypeForScalar(s)
}

// SeqDataTypeForScalar returns the sequence data type matching a column's integer scalar
// (serial/identity auto-wiring): an i16/i32/i64 column maps to smallint/integer/bigint; any other
// scalar → ok false.
func seqDataTypeForScalar(s scalarType) (seqDataType, bool) {
	switch s {
	case scalarInt16:
		return seqSmallInt, true
	case scalarInt32:
		return seqInteger, true
	case scalarInt64:
		return seqBigInt, true
	default:
		return 0, false
	}
}

// IndexKind selects an ordered B-tree (the default), a GIN inverted index (spec/design/gin.md),
// or a GiST R-tree (spec/design/gist.md). Persisted as the per-index index_kind byte (v13: GIN;
// v20: GiST).
type indexKind byte

const (
	indexBtree indexKind = 0
	indexGin   indexKind = 1
	indexGist  indexKind = 2
)

// CompositeType is a user-defined composite (row) type (spec/design/composite.md): a named,
// ordered list of typed fields, living in the database's type catalog (a database-level object,
// not per-table). Created by CREATE TYPE name AS (field type, …), referenced by name from a
// column's Type. Recursive — a field's Type may itself be a composite (a nested composite,
// persisted by name; spec/fileformat/format.md *Composite-type entry*).
type compositeType struct {
	// Name is the type name (original case — round-trips what the user typed); looked up
	// case-insensitively.
	Name string
	// Fields are the fields in declaration order (≥ 1).
	Fields []compositeField
}

// CompositeField is one field of a composite type: its name, type, and declared nullability.
type compositeField struct {
	Name string
	Type dataType
	// Decimal is the decimal numeric(p,s) typmod when Type is decimal, else nil (mirrors Column).
	Decimal *decimalTypmod
	// VarcharLen is the varchar(n) max-length typmod when Type is text, else nil (mirrors Column,
	// spec/design/types.md §15).
	VarcharLen *uint32
	// NotNull is whether the field was declared NOT NULL.
	NotNull bool
}

// ColType is a fully-resolved storage/codec column type (spec/design/composite.md §4): a scalar,
// or a composite resolved to the codec/coercion tree of its fields. Built ONCE from a catalog Type
// against the snapshot's composite-type definitions (ResolveColType) and held by the TableStore, so
// the value codec and store-coercion never re-walk the type catalog on every row. Recursive — a
// composite field may itself be composite. Go has no sum types, so the composite arm is a non-nil
// Fields slice discriminant: Composite == false means scalar (read Scalar); Composite == true means
// a resolved composite (read Name/Fields). The codec reads only the scalar / field structure; the
// field Typmod / NotNull are consulted by store-coercion (executor).
type colType struct {
	// Composite discriminates: false ⇒ a scalar (Scalar is meaningful); true ⇒ a composite
	// (Name/Fields are meaningful).
	Composite bool
	// Scalar is the inner scalar type when Composite == false && Elem == nil.
	Scalar scalarType
	// Name is the (original-case) composite type name when Composite == true, used in
	// store-coercion error messages.
	Name string
	// Fields is the composite type's resolved fields in declaration order when Composite == true.
	Fields []colField
	// Elem is the resolved element type when this is an array ColType (spec/design/array.md §3),
	// else nil. Structural — the element type is carried inline, recursively.
	Elem *colType
	// RangeElem is the resolved element type when this is a range ColType (spec/design/ranges.md §3),
	// else nil. Structural like array — the element is carried inline, but is always one of the six
	// scalar subtypes (i32/i64/decimal/timestamp/timestamptz/date), never composite/array/nested-range.
	// The codec reads the element scalar for the bound bodies; the range descriptor (discreteness) is
	// re-derived from the element via rangeForElement.
	RangeElem *colType
}

// ColField is one resolved field of a composite ColType — its name, recursively-resolved type, the
// decimal typmod (when the field is decimal), and declared nullability (mirrors CompositeField, but
// with the type fully resolved for the codec/coercion path).
type colField struct {
	Name   string
	Type   colType
	Typmod *decimalTypmod
	// VarcharLen is the varchar(n) max-length typmod when Type is text (spec/design/types.md §15).
	VarcharLen *uint32
	NotNull    bool
}

// ScalarColType wraps a scalar type as a (scalar) ColType.
func scalarColType(s scalarType) colType { return colType{Scalar: s} }

// keyable reports whether this resolved type is key-encodable (encoding.md §2.15, composite.md §6):
// every scalar (except json/jsonb/jsonpath), every range, and every scalar-element array is keyable;
// a composite is keyable iff EVERY field is (recursive). The one non-keyable inner type is an array
// whose element is itself a composite — the array key admits only scalar elements (§2.14) — so an
// array-of-composite (column or composite field) stays a deferred 0A000 key even now that the bare
// composite container is keyable. Terminates: the composite type graph is proven acyclic and
// depth-bounded (MAX_COMPOSITE_DEPTH) at CREATE TYPE (spec/design/composite.md §3).
func (ct colType) keyable() bool {
	switch {
	case ct.Composite:
		for _, f := range ct.Fields {
			if !f.Type.keyable() {
				return false
			}
		}
		return true
	case ct.RangeElem != nil:
		// A range's element is always a keyable scalar subtype (spec/design/ranges.md §2).
		return true
	case ct.Elem != nil:
		// A scalar-element array is keyable (float included); an array-of-composite is not.
		return ct.Elem.Composite == false && ct.Elem.RangeElem == nil && ct.Elem.Elem == nil &&
			ct.Elem.Scalar.IsKeyable()
	default:
		return ct.Scalar.IsKeyable()
	}
}

// ResolveColType resolves a catalog Type into a self-contained ColType against the database's
// composite definitions (keyed by lowercased name, the Snapshot.types map). A composite reference is
// looked up case-insensitively and recursively resolved; the lookup is guaranteed to succeed because
// validateCompositeTypes (the two-pass load / CREATE TYPE gate) proved every reference exists and the
// graph is acyclic before any store is built (spec/design/composite.md §3).
func resolveColType(ty dataType, types map[string]*compositeType) colType {
	if ty.Array != nil {
		elem := resolveColType(*ty.Array, types)
		return colType{Elem: &elem}
	}
	if ty.Range != nil {
		// A range column (spec/design/ranges.md §3): structural like array, the element resolved
		// inline. The element is always one of the six scalar subtypes, so the recursion bottoms out
		// at a scalar ColType immediately.
		elem := resolveColType(*ty.Range, types)
		return colType{RangeElem: &elem}
	}
	if ty.Comp == nil {
		return colType{Scalar: ty.Scalar}
	}
	def := types[strings.ToLower(ty.Comp.Name)]
	fields := make([]colField, len(def.Fields))
	for i, f := range def.Fields {
		fields[i] = colField{
			Name:       f.Name,
			Type:       resolveColType(f.Type, types),
			Typmod:     f.Decimal,
			VarcharLen: f.VarcharLen,
			NotNull:    f.NotNull,
		}
	}
	return colType{Composite: true, Name: def.Name, Fields: fields}
}

// CheckConstraint is one CHECK constraint: its (resolved, unique-per-table) name, its
// persisted expression text — written back verbatim at every commit so the catalog bytes
// are stable (spec/fileformat/format.md "Check-expression text") — and the parsed
// expression the write paths resolve and evaluate per candidate row (constraints.md §4).
type checkConstraint struct {
	Name     string
	ExprText string
	Expr     exprNode
}

// ColumnIndex returns the index of the named column (case-insensitive), or -1.
func (t *catTable) ColumnIndex(name string) int {
	for i, c := range t.Columns {
		if strings.EqualFold(c.Name, name) {
			return i
		}
	}
	return -1
}

// PKIndices returns the primary-key member columns' indices in KEY order (the explicit
// PK list — the v5 catalog persists key order independent of declaration order). Empty =
// the table has no primary key (synthetic rowid keys).
func (t *catTable) PKIndices() []int {
	return t.PK
}

// PrimaryKeyIndex returns the primary-key column's index iff the key is SINGLE-column, else -1.
// Callers that genuinely require one member (notably the OR/IN interval-set path) use this helper;
// tuple-aware PK bounds iterate PKIndices directly.
func (t *catTable) PrimaryKeyIndex() int {
	idxs := t.PKIndices()
	if len(idxs) == 1 {
		return idxs[0]
	}
	return -1
}
