// Code generated by scripts/gen_costs.rb from spec/cost/schedule.toml. DO NOT EDIT.
//
// Cost unit schedule (CLAUDE.md §5, §13: the codegen "middle path"). DATA only — the
// accrual sites that CONSUME these weights (executor / evaluator / storage reads) are
// hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
// `rake verify` fails if this file is stale. Reasoning: ../../spec/design/cost.md.

package jed

// CostSchedule holds the deterministic cost-unit weights, mirroring spec/cost/schedule.toml.
type costSchedule struct {
	StorageRowRead      int64
	StatisticsValue     int64
	PageRead            int64
	ConstraintCheck     int64
	ValueCompress       int64
	ValueDecompress     int64
	DecimalWork         int64
	RowProduced         int64
	OperatorEval        int64
	HashBuild           int64
	HashProbe           int64
	AggregateAccumulate int64
	CteScanRow          int64
	GeneratedRow        int64
	SequenceAdvance     int64
	GinEntry            int64
	GistDescent         int64
	Collate             int64
	Timezone            int64
	RegexCompile        int64
	RegexStep           int64
	WindowResult        int64
	VarlenCompare       int64
	WindowFrameStep     int64
}

// Costs is the canonical cost schedule — weights accrued per unit during query execution.
var costs = costSchedule{
	StorageRowRead:      1,
	StatisticsValue:     1,
	PageRead:            1,
	ConstraintCheck:     1,
	ValueCompress:       1,
	ValueDecompress:     1,
	DecimalWork:         1,
	RowProduced:         1,
	OperatorEval:        1,
	HashBuild:           1,
	HashProbe:           1,
	AggregateAccumulate: 1,
	CteScanRow:          1,
	GeneratedRow:        1,
	SequenceAdvance:     1,
	GinEntry:            1,
	GistDescent:         1,
	Collate:             1,
	Timezone:            1,
	RegexCompile:        1,
	RegexStep:           1,
	WindowResult:        1,
	VarlenCompare:       1,
	WindowFrameStep:     1,
}
