// Code generated by scripts/gen_estimator.rb from spec/cost/{estimator,schedule}.toml. DO NOT EDIT.
// Mechanical constants only; estimator control flow remains hand-written in every core.

package jed

type estimatorFraction struct {
	numerator   int64
	denominator int64
}

const (
	maxEstimate                   int64 = 9223372036854775807
	defaultDistinctValues         int64 = 200
	defaultSRFRows                int64 = 1000
	defaultVariableKeyBytes       int64 = 1
	joinDPLimit                         = 8
	statisticsTarget                    = 100
	statisticsSampleRows                = 30000
	statisticsKMVHashes                 = 4096
	statisticsMCVEntries                = 100
	statisticsHistogramBounds           = 101
	statisticsMaxValueBytes             = 128
	statisticsNDVScaleNumerator         = 1
	statisticsNDVScaleDenominator       = 10
)

var (
	selectivityEquality    = estimatorFraction{numerator: 1, denominator: 200}
	selectivityInequality  = estimatorFraction{numerator: 1, denominator: 3}
	selectivityPairedRange = estimatorFraction{numerator: 1, denominator: 200}
	selectivityNullTest    = estimatorFraction{numerator: 1, denominator: 200}
	selectivityMatch       = estimatorFraction{numerator: 1, denominator: 200}
	selectivityMatching    = estimatorFraction{numerator: 1, denominator: 100}
	selectivityBoolean     = estimatorFraction{numerator: 1, denominator: 2}
	selectivityOpaque      = estimatorFraction{numerator: 1, denominator: 3}
)

const (
	accessGistEqual   = "equality"
	accessGistRange   = "matching"
	accessGinContains = "matching"
	accessGinOverlaps = "matching"
	accessGinMember   = "matching"
	accessGinEqual    = "matching"
	accessUnsupported = "opaque"
)

var estimatorAccessPathOrder = [...]string{
	"pk",
	"btree",
	"gist",
	"gin",
	"pk_interval",
	"index_interval",
	"full",
}

const estimatorUnitCount = 24
const (
	estimatorUnitStorageRowRead      = 0
	estimatorUnitStatisticsValue     = 1
	estimatorUnitPageRead            = 2
	estimatorUnitConstraintCheck     = 3
	estimatorUnitValueCompress       = 4
	estimatorUnitValueDecompress     = 5
	estimatorUnitDecimalWork         = 6
	estimatorUnitRowProduced         = 7
	estimatorUnitOperatorEval        = 8
	estimatorUnitHashBuild           = 9
	estimatorUnitHashProbe           = 10
	estimatorUnitAggregateAccumulate = 11
	estimatorUnitCteScanRow          = 12
	estimatorUnitGeneratedRow        = 13
	estimatorUnitSequenceAdvance     = 14
	estimatorUnitGinEntry            = 15
	estimatorUnitGistDescent         = 16
	estimatorUnitCollate             = 17
	estimatorUnitTimezone            = 18
	estimatorUnitRegexCompile        = 19
	estimatorUnitRegexStep           = 20
	estimatorUnitWindowResult        = 21
	estimatorUnitVarlenCompare       = 22
	estimatorUnitWindowFrameStep     = 23
)

var estimatorUnitIDs = [...]string{
	"storage_row_read",
	"statistics_value",
	"page_read",
	"constraint_check",
	"value_compress",
	"value_decompress",
	"decimal_work",
	"row_produced",
	"operator_eval",
	"hash_build",
	"hash_probe",
	"aggregate_accumulate",
	"cte_scan_row",
	"generated_row",
	"sequence_advance",
	"gin_entry",
	"gist_descent",
	"collate",
	"timezone",
	"regex_compile",
	"regex_step",
	"window_result",
	"varlen_compare",
	"window_frame_step",
}

var estimatorUnitWeights = [...]int64{
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
}
