// Code generated by scripts/gen_estimator.rb from spec/cost/{estimator,schedule}.toml. DO NOT EDIT.
// Mechanical constants only; estimator control flow remains hand-written in every core.

package jed

type estimatorFraction struct {
	numerator   int64
	denominator int64
}

const (
	maxEstimate             int64 = 9223372036854775807
	defaultDistinctValues   int64 = 200
	defaultSRFRows          int64 = 1000
	defaultVariableKeyBytes int64 = 1
	joinDPLimit                   = 8
)

var (
	selectivityEquality    = estimatorFraction{numerator: 1, denominator: 200}
	selectivityInequality  = estimatorFraction{numerator: 1, denominator: 3}
	selectivityPairedRange = estimatorFraction{numerator: 1, denominator: 200}
	selectivityNullTest    = estimatorFraction{numerator: 1, denominator: 200}
	selectivityMatch       = estimatorFraction{numerator: 1, denominator: 200}
	selectivityMatching    = estimatorFraction{numerator: 1, denominator: 100}
	selectivityBoolean     = estimatorFraction{numerator: 1, denominator: 2}
	selectivityOpaque      = estimatorFraction{numerator: 1, denominator: 3}
)

const (
	accessGistEqual   = "equality"
	accessGistRange   = "matching"
	accessGinContains = "matching"
	accessGinOverlaps = "matching"
	accessGinMember   = "matching"
	accessGinEqual    = "matching"
	accessUnsupported = "opaque"
)

var estimatorAccessPathOrder = [...]string{
	"pk",
	"btree",
	"gist",
	"gin",
	"pk_interval",
	"index_interval",
	"full",
}

const estimatorUnitCount = 23
const (
	estimatorUnitStorageRowRead      = 0
	estimatorUnitPageRead            = 1
	estimatorUnitConstraintCheck     = 2
	estimatorUnitValueCompress       = 3
	estimatorUnitValueDecompress     = 4
	estimatorUnitDecimalWork         = 5
	estimatorUnitRowProduced         = 6
	estimatorUnitOperatorEval        = 7
	estimatorUnitHashBuild           = 8
	estimatorUnitHashProbe           = 9
	estimatorUnitAggregateAccumulate = 10
	estimatorUnitCteScanRow          = 11
	estimatorUnitGeneratedRow        = 12
	estimatorUnitSequenceAdvance     = 13
	estimatorUnitGinEntry            = 14
	estimatorUnitGistDescent         = 15
	estimatorUnitCollate             = 16
	estimatorUnitTimezone            = 17
	estimatorUnitRegexCompile        = 18
	estimatorUnitRegexStep           = 19
	estimatorUnitWindowResult        = 20
	estimatorUnitVarlenCompare       = 21
	estimatorUnitWindowFrameStep     = 22
)

var estimatorUnitIDs = [...]string{
	"storage_row_read",
	"page_read",
	"constraint_check",
	"value_compress",
	"value_decompress",
	"decimal_work",
	"row_produced",
	"operator_eval",
	"hash_build",
	"hash_probe",
	"aggregate_accumulate",
	"cte_scan_row",
	"generated_row",
	"sequence_advance",
	"gin_entry",
	"gist_descent",
	"collate",
	"timezone",
	"regex_compile",
	"regex_step",
	"window_result",
	"varlen_compare",
	"window_frame_step",
}

var estimatorUnitWeights = [...]int64{
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
}
