package jed

// IDENTITY columns (spec/design/sequences.md §13) — the per-core unit tests for what the PG-clean
// oracle corpus cannot express (CLAUDE.md §10): the on-disk persistence of the ALWAYS/BY DEFAULT
// distinction (the 428C9 gate still fires after a close/open) and the auto-named owned-sequence
// auto-drop. The PG-agreeing behavior (auto-numbering, OVERRIDING SYSTEM/USER, 428C9, the 42601
// conflicts, the 22023 type gate, and — since S5, §14 — the owned sequence following the column
// type) lives in suites/ddl/identity.test + suites/ddl/sequence_as_type.test. Mirrors
// impl/rust/tests/identity.rs.

import (
	"path/filepath"
	"testing"
)

// An IDENTITY column desugars to an integer column, NOT NULL, with a nextval default backed by an
// auto-created OWNED sequence named <table>_<col>_seq (same machinery as serial, sequences.md §13).
// Two columns — one ALWAYS, one BY DEFAULT — each get their own owned sequence.
func TestIdentityDesugarsToOwnedSequences(t *testing.T) {
	db := memDB().Session(SessionOptions{})
	mustExec(t, db, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, "+
		"n int GENERATED BY DEFAULT AS IDENTITY, v text)")
	out, err := db.Execute("INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id, n", nil)
	if err != nil {
		t.Fatalf("insert: %v", err)
	}
	if out.Kind != OutcomeQuery {
		t.Fatalf("expected a query, got kind %v", out.Kind)
	}
	want := [][2]int64{{1, 1}, {2, 2}}
	for i, w := range want {
		r := out.Rows[i]
		if r[0].Kind != ValInt || r[1].Kind != ValInt || r[0].Int != w[0] || r[1].Int != w[1] {
			t.Fatalf("row %d: got %v, want %v", i, r, w)
		}
	}
	// The owned sequences exist under PG's derived names and keep advancing.
	seqMustInt(t, db, "SELECT nextval('t_id_seq')", 3)
	seqMustInt(t, db, "SELECT nextval('t_n_seq')", 3)
}

// The ALWAYS/BY DEFAULT distinction persists (format_version 15, the two column flag bits): after
// create + commit + reopen, the ALWAYS column still rejects an explicit value (428C9) and the BY
// DEFAULT column still accepts one — proving the bits round-tripped through the catalog bytes.
func TestIdentityKindSurvivesReopen(t *testing.T) {
	path := filepath.Join(t.TempDir(), "identity_reopen.jed")
	db, err := create(path, databaseOptions{PageSize: 4096})
	if err != nil {
		t.Fatal(err)
	}
	mustExec(t, db, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, "+
		"n int GENERATED BY DEFAULT AS IDENTITY, v text)")
	mustExec(t, db, "INSERT INTO t (v) VALUES ('a')")
	if err := db.Commit(); err != nil {
		t.Fatal(err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}

	db, err = open(path)
	if err != nil {
		t.Fatal(err)
	}
	// ALWAYS still rejects an explicit value (the bit round-tripped).
	if code := seqErrCode(t, db, "INSERT INTO t (id, v) VALUES (5, 'x')"); code != "428C9" {
		t.Fatalf("expected 428C9 after reopen, got %s", code)
	}
	// ...but OVERRIDING SYSTEM VALUE still lets it through.
	mustExec(t, db, "INSERT INTO t (id, v) OVERRIDING SYSTEM VALUE VALUES (5, 'x')")
	// BY DEFAULT still accepts an explicit value with no override.
	mustExec(t, db, "INSERT INTO t (n, v) VALUES (9, 'y')")
	// The owner link round-tripped too: still 2BP01 to drop the sequence directly.
	if code := seqErrCode(t, db, "DROP SEQUENCE t_id_seq"); code != "2BP01" {
		t.Fatalf("expected 2BP01 after reopen, got %s", code)
	}
}

// DROP TABLE auto-drops every IDENTITY column's owned sequence (the OWNED BY link, sequences.md
// §13/§12.3), exactly as for serial.
func TestIdentityOwnedSequencesAutoDrop(t *testing.T) {
	db := memDB().Session(SessionOptions{})
	mustExec(t, db, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, n bigint GENERATED BY DEFAULT AS IDENTITY)")
	if code := seqErrCode(t, db, "DROP SEQUENCE t_id_seq"); code != "2BP01" {
		t.Fatalf("expected 2BP01, got %s", code)
	}
	mustExec(t, db, "DROP TABLE t")
	if code := seqErrCode(t, db, "SELECT nextval('t_id_seq')"); code != "42P01" {
		t.Fatalf("expected 42P01 after auto-drop, got %s", code)
	}
	if code := seqErrCode(t, db, "SELECT nextval('t_n_seq')"); code != "42P01" {
		t.Fatalf("expected 42P01 after auto-drop, got %s", code)
	}
}

// S5 (§14): an IDENTITY column's owned sequence follows the column type — a `smallint GENERATED …
// AS IDENTITY` gets an `AS smallint` sequence bounded to [1, 32767] (matching PG; the prior
// bigint-flavored divergence is closed). Introspects the auto-created sequence via its derived name:
// setval past 32767 is 22003, and nextval at the boundary traps 2200H — the sequence itself is now
// bounded (the corpus pins the boundary too, but the auto-name wiring stays a per-core check).
func TestIdentityOwnedSequenceFollowsColumnType(t *testing.T) {
	db := memDB().Session(SessionOptions{})
	mustExec(t, db, "CREATE TABLE t (id smallint GENERATED ALWAYS AS IDENTITY, v text)")
	// The owned sequence is AS smallint: setval past the i16 max is out of bounds (22003).
	if code := seqErrCode(t, db, "SELECT setval('t_id_seq', 40000)"); code != "22003" {
		t.Fatalf("expected 22003, got %s", code)
	}
	// At the boundary, the next value overflows the sequence (2200H) — not the column (the i16
	// sequence stops here, exactly as PG).
	mustExec(t, db, "SELECT setval('t_id_seq', 32767)")
	if code := seqErrCode(t, db, "SELECT nextval('t_id_seq')"); code != "2200H" {
		t.Fatalf("expected 2200H, got %s", code)
	}
}

// The identity sequence options `( … )` tune the owned sequence (a per-core check that the option
// set threads through the desugaring — the values themselves are PG-clean and also in the corpus).
func TestIdentityWithSequenceOptions(t *testing.T) {
	db := memDB().Session(SessionOptions{})
	mustExec(t, db, "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 5), v text)")
	out, err := db.Execute("INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id", nil)
	if err != nil {
		t.Fatalf("insert: %v", err)
	}
	if out.Kind != OutcomeQuery {
		t.Fatalf("expected a query, got kind %v", out.Kind)
	}
	if out.Rows[0][0].Kind != ValInt || out.Rows[0][0].Int != 100 {
		t.Fatalf("row 0: got %v, want 100", out.Rows[0][0])
	}
	if out.Rows[1][0].Kind != ValInt || out.Rows[1][0].Int != 105 {
		t.Fatalf("row 1: got %v, want 105", out.Rows[1][0])
	}
}
