// Code generated by scripts/gen_catalog.rb from spec/functions/catalog.toml. DO NOT EDIT.
//
// Operator descriptor table (CLAUDE.md §5: the codegen "middle path"). DATA only — the
// parser, executor, and the Eq3/Lt3 evaluation logic that CONSUME it are hand-written
// (§5 forbids codegenning those). Regenerate with `rake codegen`; `rake verify` fails
// if this file is stale. Reasoning: ../../spec/design/codegen.md.

package abide

// OperatorDesc is one operator's metadata, mirroring a [[operator]] entry in catalog.toml.
// Symbol is "" for operators with no infix symbol (the IS [NOT] NULL tests).
type OperatorDesc struct {
	Name          string
	Symbol        string
	Kind          string
	Arity         int
	ArgFamilies   []string
	ArgResolution string
	Result        string
	Null          string
	Errors        []string
}

// Operators lists every operator in the catalog, in catalog order.
var Operators = []OperatorDesc{
	{
		Name:          "eq",
		Symbol:        "=",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "truth",
		Null:          "propagates",
		Errors:        []string{},
	},
	{
		Name:          "lt",
		Symbol:        "<",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "truth",
		Null:          "propagates",
		Errors:        []string{},
	},
	{
		Name:          "gt",
		Symbol:        ">",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "truth",
		Null:          "propagates",
		Errors:        []string{},
	},
	{
		Name:          "le",
		Symbol:        "<=",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "truth",
		Null:          "propagates",
		Errors:        []string{},
	},
	{
		Name:          "ge",
		Symbol:        ">=",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "truth",
		Null:          "propagates",
		Errors:        []string{},
	},
	{
		Name:          "is_null",
		Symbol:        "",
		Kind:          "null_test",
		Arity:         1,
		ArgFamilies:   []string{"any"},
		ArgResolution: "none",
		Result:        "truth",
		Null:          "detects",
		Errors:        []string{},
	},
	{
		Name:          "is_not_null",
		Symbol:        "",
		Kind:          "null_test",
		Arity:         1,
		ArgFamilies:   []string{"any"},
		ArgResolution: "none",
		Result:        "truth",
		Null:          "detects",
		Errors:        []string{},
	},
}
