// Code generated by scripts/gen_catalog.rb from spec/functions/catalog.toml. DO NOT EDIT.
//
// Operator descriptor table (CLAUDE.md §5: the codegen "middle path"). DATA only — the
// parser, executor, and the Eq3/Lt3 evaluation logic that CONSUME it are hand-written
// (§5 forbids codegenning those). Regenerate with `rake codegen`; `rake verify` fails
// if this file is stale. Reasoning: ../../spec/design/codegen.md.

package abide

// OperatorDesc is one operator's metadata, mirroring a [[operator]] entry in catalog.toml.
// Symbol is "" for operators with no infix symbol (the IS [NOT] NULL tests).
type OperatorDesc struct {
	Name          string
	Symbol        string
	Kind          string
	Arity         int
	ArgFamilies   []string
	ArgResolution string
	Result        string
	Null          string
	Precedence    int
	Errors        []string
}

// Operators lists every operator in the catalog, in catalog order.
var Operators = []OperatorDesc{
	{
		Name:          "or",
		Symbol:        "",
		Kind:          "logical",
		Arity:         2,
		ArgFamilies:   []string{"boolean", "boolean"},
		ArgResolution: "none",
		Result:        "boolean",
		Null:          "kleene",
		Precedence:    10,
		Errors:        []string{},
	},
	{
		Name:          "and",
		Symbol:        "",
		Kind:          "logical",
		Arity:         2,
		ArgFamilies:   []string{"boolean", "boolean"},
		ArgResolution: "none",
		Result:        "boolean",
		Null:          "kleene",
		Precedence:    20,
		Errors:        []string{},
	},
	{
		Name:          "not",
		Symbol:        "",
		Kind:          "logical",
		Arity:         1,
		ArgFamilies:   []string{"boolean"},
		ArgResolution: "none",
		Result:        "boolean",
		Null:          "propagates",
		Precedence:    30,
		Errors:        []string{},
	},
	{
		Name:          "eq",
		Symbol:        "=",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "boolean",
		Null:          "propagates",
		Precedence:    35,
		Errors:        []string{},
	},
	{
		Name:          "lt",
		Symbol:        "<",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "boolean",
		Null:          "propagates",
		Precedence:    35,
		Errors:        []string{},
	},
	{
		Name:          "gt",
		Symbol:        ">",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "boolean",
		Null:          "propagates",
		Precedence:    35,
		Errors:        []string{},
	},
	{
		Name:          "le",
		Symbol:        "<=",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "boolean",
		Null:          "propagates",
		Precedence:    35,
		Errors:        []string{},
	},
	{
		Name:          "ge",
		Symbol:        ">=",
		Kind:          "comparison",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "boolean",
		Null:          "propagates",
		Precedence:    35,
		Errors:        []string{},
	},
	{
		Name:          "is_null",
		Symbol:        "",
		Kind:          "null_test",
		Arity:         1,
		ArgFamilies:   []string{"any"},
		ArgResolution: "none",
		Result:        "boolean",
		Null:          "detects",
		Precedence:    35,
		Errors:        []string{},
	},
	{
		Name:          "is_not_null",
		Symbol:        "",
		Kind:          "null_test",
		Arity:         1,
		ArgFamilies:   []string{"any"},
		ArgResolution: "none",
		Result:        "boolean",
		Null:          "detects",
		Precedence:    35,
		Errors:        []string{},
	},
	{
		Name:          "add",
		Symbol:        "+",
		Kind:          "arithmetic",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "promoted",
		Null:          "propagates",
		Precedence:    40,
		Errors:        []string{"22003"},
	},
	{
		Name:          "sub",
		Symbol:        "-",
		Kind:          "arithmetic",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "promoted",
		Null:          "propagates",
		Precedence:    40,
		Errors:        []string{"22003"},
	},
	{
		Name:          "mul",
		Symbol:        "*",
		Kind:          "arithmetic",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "promoted",
		Null:          "propagates",
		Precedence:    50,
		Errors:        []string{"22003"},
	},
	{
		Name:          "div",
		Symbol:        "/",
		Kind:          "arithmetic",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "promoted",
		Null:          "propagates",
		Precedence:    50,
		Errors:        []string{"22003", "22012"},
	},
	{
		Name:          "mod",
		Symbol:        "%",
		Kind:          "arithmetic",
		Arity:         2,
		ArgFamilies:   []string{"integer", "integer"},
		ArgResolution: "promote",
		Result:        "promoted",
		Null:          "propagates",
		Precedence:    50,
		Errors:        []string{"22003", "22012"},
	},
	{
		Name:          "neg",
		Symbol:        "-",
		Kind:          "arithmetic",
		Arity:         1,
		ArgFamilies:   []string{"integer"},
		ArgResolution: "none",
		Result:        "promoted",
		Null:          "propagates",
		Precedence:    60,
		Errors:        []string{"22003"},
	},
}
