// Code generated by scripts/gen_catalog.rb from spec/types/ranges.toml. DO NOT EDIT.
//
// Range-type descriptor table (CLAUDE.md §4/§5): the six built-in PostgreSQL range types
// as DATA. The recursive value codec / comparator / text-I/O / canonicalize rule that
// CONSUME it are hand-written per core (§5 forbids codegenning them; derived from the
// element type, byte-identical by construction). Regenerate with `rake codegen`; `rake
// verify` fails if stale. Reasoning: ../../spec/design/ranges.md.

package jed

// RangeDesc is one range type's metadata, mirroring a [[range]] entry in
// spec/types/ranges.toml. Element is a scalar id (the subtype the range is built over);
// Discrete marks an integer/date subtype stored in canonical [) form.
type RangeDesc struct {
	ID       string
	Element  string
	Aliases  []string
	Discrete bool
}

// Ranges lists every built-in range type, in ranges.toml order.
var Ranges = []RangeDesc{
	{
		ID:       "i32range",
		Element:  "i32",
		Aliases:  []string{"int4range"},
		Discrete: true,
	},
	{
		ID:       "i64range",
		Element:  "i64",
		Aliases:  []string{"int8range"},
		Discrete: true,
	},
	{
		ID:       "numrange",
		Element:  "decimal",
		Aliases:  []string{},
		Discrete: false,
	},
	{
		ID:       "tsrange",
		Element:  "timestamp",
		Aliases:  []string{},
		Discrete: false,
	},
	{
		ID:       "tstzrange",
		Element:  "timestamptz",
		Aliases:  []string{},
		Discrete: false,
	},
	{
		ID:       "daterange",
		Element:  "date",
		Aliases:  []string{},
		Discrete: true,
	},
}
