// Code generated by scripts/gen_errors.rb from spec/errors/registry.toml. DO NOT EDIT.
//
// SQLSTATE error codes (CLAUDE.md §5, §10: the codegen "middle path"). DATA only — the
// EngineError scaffolding that CONSUMES these (message assembly, Error rendering, the raise
// sites through the executor) is hand-written in errors.go (§5 forbids codegenning those).
// Regenerate with `rake codegen`; `rake verify` fails if this file is stale. Each variant's
// message template + rationale live in spec/errors/registry.toml. Reasoning:
// ../../spec/design/codegen.md.

package jed

// SqlState is a structured engine error's SQLSTATE. Its Code() string is the canonical 5-char
// code from spec/errors/registry.toml (cross-checked in tests). Declaration order is registry
// order and carries no meaning — the iota value is never serialized.
type SqlState int

const (
	// CardinalityViolation is 21000 — more than one row returned by a subquery used as an expression.
	CardinalityViolation SqlState = iota
	// DataException is 22000 — {detail}.
	DataException
	// NumericValueOutOfRange is 22003 — value out of range for type {type}.
	NumericValueOutOfRange
	// NullValueNotAllowed is 22004 — {detail}.
	NullValueNotAllowed
	// InvalidDatetimeFormat is 22007 — invalid input syntax for type {type}: {detail}.
	InvalidDatetimeFormat
	// DatetimeFieldOverflow is 22008 — date/time field value out of range: {detail}.
	DatetimeFieldOverflow
	// DivisionByZero is 22012 — division by zero.
	DivisionByZero
	// InvalidArgumentForNtile is 22014 — argument of ntile must be greater than zero.
	InvalidArgumentForNtile
	// InvalidArgumentForNthValue is 22016 — argument of nth_value must be greater than zero.
	InvalidArgumentForNthValue
	// SubstringError is 22011 — negative substring length not allowed.
	SubstringError
	// InvalidArgumentForWidthBucketFunction is 2201G — {detail}.
	InvalidArgumentForWidthBucketFunction
	// InvalidArgumentForLog is 2201E — {detail}.
	InvalidArgumentForLog
	// InvalidArgumentForPowerFunction is 2201F — {detail}.
	InvalidArgumentForPowerFunction
	// InvalidPrecedingOrFollowingSize is 22013 — frame starting or ending offset must not be negative.
	InvalidPrecedingOrFollowingSize
	// SequenceGeneratorLimitExceeded is 2200H — nextval: reached {bound} value of sequence {sequence}.
	SequenceGeneratorLimitExceeded
	// InvalidRowCountInLimitClause is 2201W — LIMIT must not be negative.
	InvalidRowCountInLimitClause
	// InvalidRowCountInOffsetClause is 2201X — OFFSET must not be negative.
	InvalidRowCountInOffsetClause
	// InvalidParameterValue is 22023 — invalid parameter value: {detail}.
	InvalidParameterValue
	// InvalidEscapeSequence is 22025 — LIKE pattern must not end with escape character.
	InvalidEscapeSequence
	// InvalidRegularExpression is 2201B — invalid regular expression: {detail}.
	InvalidRegularExpression
	// ArraySubscriptError is 2202E — {detail}.
	ArraySubscriptError
	// DuplicateJsonObjectKeyValue is 22030 — duplicate JSON object key value.
	DuplicateJsonObjectKeyValue
	// SqlJsonItemCannotBeCastToTargetType is 2203A — {detail}.
	SqlJsonItemCannotBeCastToTargetType
	// SqlJsonObjectNotFound is 2203C — {detail}.
	SqlJsonObjectNotFound
	// SqlJsonMemberNotFound is 2203F — {detail}.
	SqlJsonMemberNotFound
	// InvalidArgumentForSqlJsonDatetimeFunction is 22031 — {detail}.
	InvalidArgumentForSqlJsonDatetimeFunction
	// InvalidSqlJsonSubscript is 22033 — {detail}.
	InvalidSqlJsonSubscript
	// MoreThanOneSqlJsonItem is 22034 — {detail}.
	MoreThanOneSqlJsonItem
	// NoSqlJsonItem is 22035 — {detail}.
	NoSqlJsonItem
	// NonNumericSqlJsonItem is 22036 — {detail}.
	NonNumericSqlJsonItem
	// SingletonSqlJsonItemRequired is 22038 — {detail}.
	SingletonSqlJsonItemRequired
	// InvalidTextRepresentation is 22P02 — invalid input syntax for type {type}: {detail}.
	InvalidTextRepresentation
	// NotNullViolation is 23502 — null value in column {name} violates not-null constraint.
	NotNullViolation
	// UniqueViolation is 23505 — duplicate key value violates unique constraint: {name}.
	UniqueViolation
	// CheckViolation is 23514 — new row for relation {table} violates check constraint {name}.
	CheckViolation
	// ForeignKeyViolation is 23503 — insert or update on table {table} violates foreign key constraint {name}.
	ForeignKeyViolation
	// ExclusionViolation is 23P01 — conflicting key value violates exclusion constraint: {name}.
	ExclusionViolation
	// ActiveSqlTransaction is 25001 — there is already a transaction in progress.
	ActiveSqlTransaction
	// ReadOnlySqlTransaction is 25006 — cannot execute {statement} in a read-only transaction.
	ReadOnlySqlTransaction
	// InFailedSqlTransaction is 25P02 — current transaction is aborted, commands ignored until end of transaction block.
	InFailedSqlTransaction
	// DependentObjectsStillExist is 2BP01 — cannot drop type {name} because other objects depend on it: {detail}.
	DependentObjectsStillExist
	// SyntaxError is 42601 — syntax error: {detail}.
	SyntaxError
	// UndefinedTable is 42P01 — table does not exist: {name}.
	UndefinedTable
	// UndefinedColumn is 42703 — column does not exist: {name}.
	UndefinedColumn
	// AmbiguousColumn is 42702 — column reference {name} is ambiguous.
	AmbiguousColumn
	// UndefinedObject is 42704 — {kind} does not exist: {name}.
	UndefinedObject
	// InvalidColumnReference is 42P10 — for SELECT DISTINCT, ORDER BY expressions must appear in select list.
	InvalidColumnReference
	// DatatypeMismatch is 42804 — datatype mismatch: {detail}.
	DatatypeMismatch
	// InvalidForeignKey is 42830 — there is no unique constraint matching given keys for referenced table {name}.
	InvalidForeignKey
	// DuplicateColumn is 42701 — duplicate column name: {name}.
	DuplicateColumn
	// DuplicateAlias is 42712 — table name {name} specified more than once.
	DuplicateAlias
	// DuplicateTable is 42P07 — relation already exists: {name}.
	DuplicateTable
	// InvalidTableDefinition is 42P16 — invalid table definition: {detail}.
	InvalidTableDefinition
	// GroupingError is 42803 — column {name} must appear in the GROUP BY clause or be used in an aggregate function.
	GroupingError
	// UndefinedFunction is 42883 — function does not exist: {name}.
	UndefinedFunction
	// IndeterminateDatatype is 42P18 — could not determine data type of parameter ${index}.
	IndeterminateDatatype
	// InvalidRecursion is 42P19 — {detail}.
	InvalidRecursion
	// UndefinedParameter is 42P02 — there is no parameter ${index}.
	UndefinedParameter
	// WindowingError is 42P20 — {detail}.
	WindowingError
	// CollationMismatch is 42P21 — collation mismatch between explicit collations {left} and {right}.
	CollationMismatch
	// IndeterminateCollation is 42P22 — could not determine which collation to use for string comparison.
	IndeterminateCollation
	// DuplicateObject is 42710 — constraint {name} for relation {table} already exists.
	DuplicateObject
	// WrongObjectType is 42809 — {name} is not {kind}.
	WrongObjectType
	// NameTooLong is 42622 — identifier exceeds the maximum length of {max} bytes.
	NameTooLong
	// GeneratedAlways is 428C9 — {detail}.
	GeneratedAlways
	// InsufficientPrivilege is 42501 — permission denied for {object}.
	InsufficientPrivilege
	// FeatureNotSupported is 0A000 — feature not supported: {detail}.
	FeatureNotSupported
	// ProgramLimitExceeded is 54000 — SQL statement exceeds the maximum length of {max} bytes.
	ProgramLimitExceeded
	// StatementTooComplex is 54001 — statement too complex: nesting depth exceeds the maximum of {max}.
	StatementTooComplex
	// CostLimitExceeded is 54P01 — query exceeded the cost limit of {limit} (accrued {cost}).
	CostLimitExceeded
	// SessionCostLimitExceeded is 54P02 — session exceeded the lifetime cost limit of {limit} (accrued {cost}).
	SessionCostLimitExceeded
	// TempStorageLimitExceeded is 54P03 — temporary table storage exceeded the limit of {limit} bytes.
	TempStorageLimitExceeded
	// ObjectNotInPrerequisiteState is 55000 — {detail}.
	ObjectNotInPrerequisiteState
	// IoError is 58030 — I/O error: {detail}.
	IoError
	// UndefinedFile is 58P01 — database file does not exist: {path}.
	UndefinedFile
	// DuplicateFile is 58P02 — database file already exists: {path}.
	DuplicateFile
	// DataCorrupted is XX001 — on-disk database file is malformed: {detail}.
	DataCorrupted
	// CollationVersionMismatch is XX002 — collation version mismatch: {detail}.
	CollationVersionMismatch
)

// Code returns the canonical SQLSTATE string.
func (s SqlState) Code() string {
	switch s {
	case CardinalityViolation:
		return "21000"
	case DataException:
		return "22000"
	case NumericValueOutOfRange:
		return "22003"
	case NullValueNotAllowed:
		return "22004"
	case InvalidDatetimeFormat:
		return "22007"
	case DatetimeFieldOverflow:
		return "22008"
	case DivisionByZero:
		return "22012"
	case InvalidArgumentForNtile:
		return "22014"
	case InvalidArgumentForNthValue:
		return "22016"
	case SubstringError:
		return "22011"
	case InvalidArgumentForWidthBucketFunction:
		return "2201G"
	case InvalidArgumentForLog:
		return "2201E"
	case InvalidArgumentForPowerFunction:
		return "2201F"
	case InvalidPrecedingOrFollowingSize:
		return "22013"
	case SequenceGeneratorLimitExceeded:
		return "2200H"
	case InvalidRowCountInLimitClause:
		return "2201W"
	case InvalidRowCountInOffsetClause:
		return "2201X"
	case InvalidParameterValue:
		return "22023"
	case InvalidEscapeSequence:
		return "22025"
	case InvalidRegularExpression:
		return "2201B"
	case ArraySubscriptError:
		return "2202E"
	case DuplicateJsonObjectKeyValue:
		return "22030"
	case SqlJsonItemCannotBeCastToTargetType:
		return "2203A"
	case SqlJsonObjectNotFound:
		return "2203C"
	case SqlJsonMemberNotFound:
		return "2203F"
	case InvalidArgumentForSqlJsonDatetimeFunction:
		return "22031"
	case InvalidSqlJsonSubscript:
		return "22033"
	case MoreThanOneSqlJsonItem:
		return "22034"
	case NoSqlJsonItem:
		return "22035"
	case NonNumericSqlJsonItem:
		return "22036"
	case SingletonSqlJsonItemRequired:
		return "22038"
	case InvalidTextRepresentation:
		return "22P02"
	case NotNullViolation:
		return "23502"
	case UniqueViolation:
		return "23505"
	case CheckViolation:
		return "23514"
	case ForeignKeyViolation:
		return "23503"
	case ExclusionViolation:
		return "23P01"
	case ActiveSqlTransaction:
		return "25001"
	case ReadOnlySqlTransaction:
		return "25006"
	case InFailedSqlTransaction:
		return "25P02"
	case DependentObjectsStillExist:
		return "2BP01"
	case SyntaxError:
		return "42601"
	case UndefinedTable:
		return "42P01"
	case UndefinedColumn:
		return "42703"
	case AmbiguousColumn:
		return "42702"
	case UndefinedObject:
		return "42704"
	case InvalidColumnReference:
		return "42P10"
	case DatatypeMismatch:
		return "42804"
	case InvalidForeignKey:
		return "42830"
	case DuplicateColumn:
		return "42701"
	case DuplicateAlias:
		return "42712"
	case DuplicateTable:
		return "42P07"
	case InvalidTableDefinition:
		return "42P16"
	case GroupingError:
		return "42803"
	case UndefinedFunction:
		return "42883"
	case IndeterminateDatatype:
		return "42P18"
	case InvalidRecursion:
		return "42P19"
	case UndefinedParameter:
		return "42P02"
	case WindowingError:
		return "42P20"
	case CollationMismatch:
		return "42P21"
	case IndeterminateCollation:
		return "42P22"
	case DuplicateObject:
		return "42710"
	case WrongObjectType:
		return "42809"
	case NameTooLong:
		return "42622"
	case GeneratedAlways:
		return "428C9"
	case InsufficientPrivilege:
		return "42501"
	case FeatureNotSupported:
		return "0A000"
	case ProgramLimitExceeded:
		return "54000"
	case StatementTooComplex:
		return "54001"
	case CostLimitExceeded:
		return "54P01"
	case SessionCostLimitExceeded:
		return "54P02"
	case TempStorageLimitExceeded:
		return "54P03"
	case ObjectNotInPrerequisiteState:
		return "55000"
	case IoError:
		return "58030"
	case UndefinedFile:
		return "58P01"
	case DuplicateFile:
		return "58P02"
	case DataCorrupted:
		return "XX001"
	case CollationVersionMismatch:
		return "XX002"
	default:
		return "XX000"
	}
}

// ErrorDesc is one error's metadata, mirroring an [[error]] entry in registry.toml. The enum
// above is the type-safe code used at raise sites; Errors is the iterable data table the
// cross-check tests walk against the registry (the enum is not iterable).
type errorDesc struct {
	Code  string
	Name  string
	Class string
}

// Errors lists every error, in registry order.
var errorDescs = []errorDesc{
	{Code: "21000", Name: "cardinality_violation", Class: "cardinality violation"},
	{Code: "22000", Name: "data_exception", Class: "data exception"},
	{Code: "22003", Name: "numeric_value_out_of_range", Class: "data exception"},
	{Code: "22004", Name: "null_value_not_allowed", Class: "data exception"},
	{Code: "22007", Name: "invalid_datetime_format", Class: "data exception"},
	{Code: "22008", Name: "datetime_field_overflow", Class: "data exception"},
	{Code: "22012", Name: "division_by_zero", Class: "data exception"},
	{Code: "22014", Name: "invalid_argument_for_ntile", Class: "data exception"},
	{Code: "22016", Name: "invalid_argument_for_nth_value", Class: "data exception"},
	{Code: "22011", Name: "substring_error", Class: "data exception"},
	{Code: "2201G", Name: "invalid_argument_for_width_bucket_function", Class: "data exception"},
	{Code: "2201E", Name: "invalid_argument_for_log", Class: "data exception"},
	{Code: "2201F", Name: "invalid_argument_for_power_function", Class: "data exception"},
	{Code: "22013", Name: "invalid_preceding_or_following_size", Class: "data exception"},
	{Code: "2200H", Name: "sequence_generator_limit_exceeded", Class: "data exception"},
	{Code: "2201W", Name: "invalid_row_count_in_limit_clause", Class: "data exception"},
	{Code: "2201X", Name: "invalid_row_count_in_offset_clause", Class: "data exception"},
	{Code: "22023", Name: "invalid_parameter_value", Class: "data exception"},
	{Code: "22025", Name: "invalid_escape_sequence", Class: "data exception"},
	{Code: "2201B", Name: "invalid_regular_expression", Class: "data exception"},
	{Code: "2202E", Name: "array_subscript_error", Class: "data exception"},
	{Code: "22030", Name: "duplicate_json_object_key_value", Class: "data exception"},
	{Code: "2203A", Name: "sql_json_item_cannot_be_cast_to_target_type", Class: "data exception"},
	{Code: "2203C", Name: "sql_json_object_not_found", Class: "data exception"},
	{Code: "2203F", Name: "sql_json_member_not_found", Class: "data exception"},
	{Code: "22031", Name: "invalid_argument_for_sql_json_datetime_function", Class: "data exception"},
	{Code: "22033", Name: "invalid_sql_json_subscript", Class: "data exception"},
	{Code: "22034", Name: "more_than_one_sql_json_item", Class: "data exception"},
	{Code: "22035", Name: "no_sql_json_item", Class: "data exception"},
	{Code: "22036", Name: "non_numeric_sql_json_item", Class: "data exception"},
	{Code: "22038", Name: "singleton_sql_json_item_required", Class: "data exception"},
	{Code: "22P02", Name: "invalid_text_representation", Class: "data exception"},
	{Code: "23502", Name: "not_null_violation", Class: "integrity constraint violation"},
	{Code: "23505", Name: "unique_violation", Class: "integrity constraint violation"},
	{Code: "23514", Name: "check_violation", Class: "integrity constraint violation"},
	{Code: "23503", Name: "foreign_key_violation", Class: "integrity constraint violation"},
	{Code: "23P01", Name: "exclusion_violation", Class: "integrity constraint violation"},
	{Code: "25001", Name: "active_sql_transaction", Class: "invalid transaction state"},
	{Code: "25006", Name: "read_only_sql_transaction", Class: "invalid transaction state"},
	{Code: "25P02", Name: "in_failed_sql_transaction", Class: "invalid transaction state"},
	{Code: "2BP01", Name: "dependent_objects_still_exist", Class: "dependent objects still exist"},
	{Code: "42601", Name: "syntax_error", Class: "syntax error or access rule violation"},
	{Code: "42P01", Name: "undefined_table", Class: "syntax error or access rule violation"},
	{Code: "42703", Name: "undefined_column", Class: "syntax error or access rule violation"},
	{Code: "42702", Name: "ambiguous_column", Class: "syntax error or access rule violation"},
	{Code: "42704", Name: "undefined_object", Class: "syntax error or access rule violation"},
	{Code: "42P10", Name: "invalid_column_reference", Class: "syntax error or access rule violation"},
	{Code: "42804", Name: "datatype_mismatch", Class: "syntax error or access rule violation"},
	{Code: "42830", Name: "invalid_foreign_key", Class: "syntax error or access rule violation"},
	{Code: "42701", Name: "duplicate_column", Class: "syntax error or access rule violation"},
	{Code: "42712", Name: "duplicate_alias", Class: "syntax error or access rule violation"},
	{Code: "42P07", Name: "duplicate_table", Class: "syntax error or access rule violation"},
	{Code: "42P16", Name: "invalid_table_definition", Class: "syntax error or access rule violation"},
	{Code: "42803", Name: "grouping_error", Class: "syntax error or access rule violation"},
	{Code: "42883", Name: "undefined_function", Class: "syntax error or access rule violation"},
	{Code: "42P18", Name: "indeterminate_datatype", Class: "syntax error or access rule violation"},
	{Code: "42P19", Name: "invalid_recursion", Class: "syntax error or access rule violation"},
	{Code: "42P02", Name: "undefined_parameter", Class: "syntax error or access rule violation"},
	{Code: "42P20", Name: "windowing_error", Class: "syntax error or access rule violation"},
	{Code: "42P21", Name: "collation_mismatch", Class: "syntax error or access rule violation"},
	{Code: "42P22", Name: "indeterminate_collation", Class: "syntax error or access rule violation"},
	{Code: "42710", Name: "duplicate_object", Class: "syntax error or access rule violation"},
	{Code: "42809", Name: "wrong_object_type", Class: "syntax error or access rule violation"},
	{Code: "42622", Name: "name_too_long", Class: "syntax error or access rule violation"},
	{Code: "428C9", Name: "generated_always", Class: "syntax error or access rule violation"},
	{Code: "42501", Name: "insufficient_privilege", Class: "syntax error or access rule violation"},
	{Code: "0A000", Name: "feature_not_supported", Class: "feature not supported"},
	{Code: "54000", Name: "program_limit_exceeded", Class: "program limit exceeded"},
	{Code: "54001", Name: "statement_too_complex", Class: "program limit exceeded"},
	{Code: "54P01", Name: "cost_limit_exceeded", Class: "program limit exceeded"},
	{Code: "54P02", Name: "session_cost_limit_exceeded", Class: "program limit exceeded"},
	{Code: "54P03", Name: "temp_storage_limit_exceeded", Class: "program limit exceeded"},
	{Code: "55000", Name: "object_not_in_prerequisite_state", Class: "object not in prerequisite state"},
	{Code: "58030", Name: "io_error", Class: "system error"},
	{Code: "58P01", Name: "undefined_file", Class: "system error"},
	{Code: "58P02", Name: "duplicate_file", Class: "system error"},
	{Code: "XX001", Name: "data_corrupted", Class: "internal error"},
	{Code: "XX002", Name: "collation_version_mismatch", Class: "internal error"},
}
