#!/usr/bin/env ruby
# frozen_string_literal: true

# scripts/devenv.rb — this checkout's development environment variables.
#
#   rake dev:ports:ensure      allocate this checkout's port group if it has none (idempotent)
#   rake dev:ports:overwrite   deliberately move to a different group (stop services first)
#   rake dev:ports:show        print the allocation and the values derived from it
#
# TWO files, loaded together by mise (mise.toml [env]), because they have different owners:
#
#   .dev/ports.env     port-tamer's state file. NAME=<port> lines only — port-tamer rewrites it
#                      canonically from port-tamer.toml, and rejects the file outright if it holds
#                      anything else. Not ours to write.
#   .dev/derived.env   connection values this project owns for the checkout-local PostgreSQL
#                      cluster: PGHOST plus the fixed PGUSER / PGDATABASE defaults.
#
# PGHOST cannot be a static setting or a mise template: the socket directory depends on the
# checkout's path length (DevPaths.socket_dir — sun_path is capped at 104 bytes on macOS), so it
# has exactly one correct definition and scripts/devdb.rb starts the server on it. Deriving it here
# from that same source is what keeps the server's socket and the client's PGHOST identical by
# construction rather than by two implementations agreeing.
#
# PGHOST and PGPORT are a pair — one without the other names a real port on the wrong server, and
# libpq then hunts a socket that cannot exist. They land in different files, so every path that
# writes the allocation writes the derived file in the same breath, and `mise run dev` asserts the
# two agree with the cluster before starting anything.

require "fileutils"
require_relative "lib/dev_paths"

PORT_TAMER_CONFIG = File.join(DevPaths::ROOT, "port-tamer.toml")

# Run port-tamer, distinguishing "not installed" from "ran and refused". Ruby's `system` returns
# nil when the command cannot be executed at all and false when it ran and exited nonzero — a
# distinction worth keeping, because the two have completely different fixes. port-tamer is pinned
# in mise.toml, so it is on PATH inside `mise run` / `mise exec` and in an activated shell;
# anything else (a bare `ruby scripts/devenv.rb`) lands on the first branch.
def port_tamer(*args)
  ok = system("port-tamer", *args)
  abort <<~MSG if ok.nil?
    devenv: port-tamer not found. It is a project tool, pinned in mise.toml:
      mise install
  MSG
  ok
end

# One-time migration off the hand-rolled allocator this replaced. Its file held PORT_BASE and
# PGHOST alongside the ports, which port-tamer reads as invalid state and (correctly) refuses to
# replace silently. PORT_BASE identifies that file exactly, and it is generated, gitignored state
# rather than configuration, so the right move is to drop it and let port-tamer allocate.
#
# The old numbers cannot be carried over: they sat at base+1..base+5, and port-tamer puts the first
# port ON the aligned start. The cluster survives (its port is a command-line argument, not
# something initdb recorded), but a stack that is already up keeps the old port until restarted.
def migrate_legacy_state
  return unless File.exist?(DevPaths::PORTS_ENV)
  return unless File.read(DevPaths::PORTS_ENV).match?(/^PORT_BASE=/)

  File.delete(DevPaths::PORTS_ENV)
  warn "devenv: replaced the pre-port-tamer allocation in #{DevPaths::PORTS_ENV}."
  warn "devenv: this checkout's ports move — restart its stack (`process-compose down`, `mise run dev`)."
end

def allocate(overwrite:)
  FileUtils.mkdir_p(DevPaths::DEV_DIR) # port-tamer writes its state file, it does not create dirs
  migrate_legacy_state

  argv = ["allocate", "--state-file", DevPaths::PORTS_ENV, PORT_TAMER_CONFIG]
  argv.insert(1, "--overwrite") if overwrite

  # Exit 2 is port-tamer's "invalid arguments, configuration, or existing state". The one case a
  # user hits is a state file from an incompatible port-tamer.toml (entries reordered or inserted),
  # which is deliberately not silently replaced — name the way out.
  abort <<~MSG unless port_tamer(*argv)
    devenv: port-tamer could not allocate this checkout's ports (see the error above).
    If the saved allocation no longer matches port-tamer.toml, stop this checkout's services and
    replace it: `rake dev:ports:overwrite`.
  MSG
end

def pgport
  unless File.exist?(DevPaths::PORTS_ENV)
    abort "devenv: no port allocation — run `rake dev:ports:ensure` (#{DevPaths::PORTS_ENV} is missing)."
  end

  File.read(DevPaths::PORTS_ENV)[/^PGPORT=(\d+)$/, 1] ||
    abort("devenv: PGPORT missing from #{DevPaths::PORTS_ENV} — re-run `rake dev:ports:ensure`.")
end

def write_derived
  # Comments go on their OWN line: this file is read by mise's dotenv parser and by `source` in a
  # shell, and a trailing `VAR=value # note` is not portable across both.
  body = <<~ENV
    # Generated by scripts/devenv.rb from .dev/ports.env — DO NOT EDIT, and do not commit
    # (.dev/ is ignored). Regenerate with `rake dev:ports:ensure`.
    #
    # This checkout's PostgreSQL cluster connection defaults. PGHOST travels WITH the PGPORT that
    # .dev/ports.env assigns: never export one without the other. scripts/devdb.rb initializes the
    # fixed postgres bootstrap role and database on every platform.

    PGHOST=#{DevPaths.socket_dir(pgport)}
    PGUSER=postgres
    PGDATABASE=postgres
  ENV

  return if File.exist?(DevPaths::DERIVED_ENV) && File.read(DevPaths::DERIVED_ENV) == body

  FileUtils.mkdir_p(DevPaths::DEV_DIR)
  File.write(DevPaths::DERIVED_ENV, body)
end

def show
  port_tamer("status", "--state-file", DevPaths::PORTS_ENV, PORT_TAMER_CONFIG)
  puts
  puts "  PGHOST        #{DevPaths.socket_dir(pgport)}"
  puts "  PGUSER        postgres"
  puts "  PGDATABASE    postgres"
  puts
  puts "  #{DevPaths::PORTS_ENV}"
  puts "  #{DevPaths::DERIVED_ENV}"
end

case ARGV[0]
when "ensure"
  allocate(overwrite: false)
  write_derived
when "overwrite"
  allocate(overwrite: true)
  write_derived
when "show"
  show
else
  abort("usage: devenv.rb ensure|overwrite|show")
end
