#!/usr/bin/env ruby
# frozen_string_literal: true

# scripts/devports.rb — per-worktree TCP port allocation.
#
#   rake dev:ports:init     allocate a block if none exists
#   rake dev:ports:ensure   allocate, or re-allocate if the current block is in use elsewhere
#   rake dev:ports:show     print the allocation
#
# WHY. A git worktree is the native equivalent of a second devcontainer: several checkouts of this
# repo may be developed and served simultaneously on one machine. In a container each instance had
# its own network namespace, so every service could use the same well-known port; natively they
# share one, and two worktrees running `vite dev` would collide on 5173.
#
# The fix is not a registry or a reverse proxy: allocate a random BLOCK once per worktree, persist
# it in the (gitignored) .dev/ports.env, and reuse it. Two dormant worktrees may hold the same
# block — harmless until both run, which `ensure` detects by probing the ports and re-allocating.
# The operating system is the registry of allocations that currently matter.
#
# Ports are assigned by OFFSET from the base so the mapping is fixed and greppable, and the block
# is sized with room to grow: adding a service must never renumber the existing ones.
#
# NATIVE vs DEVCONTAINER. This exists for native development, where worktrees share one network
# stack. A devcontainer still has its own namespace, so it does not need an allocation, and its
# devcontainer.json forwards the HISTORICAL 5173/4173 — which is exactly what the vite/playwright
# configs fall back to when these variables are unset. Generating the file inside a container is
# therefore inert; only SOURCING it changes anything, and doing so binds ports the container is not
# forwarding. Inside a container, don't.

require "socket"
require "fileutils"

DEV_DIR = File.expand_path("../.dev", __dir__)
PORTS_ENV = File.join(DEV_DIR, "ports.env")

BLOCK_SIZE = 10

# offset => [variable, human-readable role]. Offset 0 is the base itself (never bound), so a
# reserved-but-unused offset can be claimed later without moving anything already in use.
ASSIGNMENTS = {
  1 => ["WEB_DEV_PORT",     "web dev server (vite dev, /web)"],
  2 => ["WEB_PREVIEW_PORT", "web preview / e2e static server (/web)"],
  3 => ["PGPORT",           "PostgreSQL oracle cluster"],
  4 => ["PC_PORT_NUM",      "process-compose control API"],
  5 => ["TS_BROWSER_PORT",  "TS core Browser/OPFS host e2e (vite dev, impl/ts)"],
}.freeze

# Well clear of the ephemeral ranges both platforms allocate from (Linux 32768-60999, macOS
# 49152-65535), so the OS never hands a client socket a port out of a worktree's block.
BASE_MIN = 16_000
BASE_MAX = 31_000

# Free = we can bind it on the loopback address. Probing the bind is the only honest test; parsing
# `lsof`/`ss` would miss a socket opened a millisecond later and differs per platform anyway.
def free?(port)
  TCPServer.new("127.0.0.1", port).close
  true
rescue Errno::EADDRINUSE, Errno::EACCES
  false
end

def ports_for(base) = ASSIGNMENTS.keys.map { |offset| base + offset }

def block_free?(base) = ports_for(base).all? { |p| free?(p) }

# Bases are aligned to the block size so two allocations can never partially overlap.
def pick_base
  candidates = (BASE_MIN..BASE_MAX).step(BLOCK_SIZE).to_a.shuffle
  candidates.find { |base| block_free?(base) } ||
    abort("devports: no free #{BLOCK_SIZE}-port block in #{BASE_MIN}..#{BASE_MAX}")
end

def read_allocation
  return nil unless File.exist?(PORTS_ENV)

  base = File.read(PORTS_ENV)[/^PORT_BASE=(\d+)$/, 1]
  base&.to_i
end

def write_allocation(base)
  FileUtils.mkdir_p(DEV_DIR)
  # Comments go on their OWN line: this file is read by shell `source`, by dotenv parsers, and by
  # process-compose, and a trailing `VAR=1 # note` is not portable across all three.
  body = +"# Generated by scripts/devports.rb — DO NOT EDIT, and do not commit (.dev/ is ignored).\n"
  body << "# This worktree's port block. Re-run `rake dev:ports:ensure` if a port is taken.\n"
  body << "# For NATIVE development. A devcontainer has its own network namespace and forwards the\n"
  body << "# default 5173/4173, which the configs use when these are unset — don't source this there.\n\n"
  body << "PORT_BASE=#{base}\n"
  ASSIGNMENTS.each do |offset, (var, role)|
    body << "\n# #{role}\n#{var}=#{base + offset}\n"
  end
  # Convenience URLs so a caller (or an agent) never has to reassemble them.
  body << "\n# Reachable URLs for the two HTTP services.\n"
  body << "WEB_DEV_URL=http://127.0.0.1:#{base + 1}\n"
  body << "WEB_PREVIEW_URL=http://127.0.0.1:#{base + 2}\n"
  File.write(PORTS_ENV, body)
  base
end

def show(base)
  puts
  puts "  #{File.basename(File.expand_path('..', __dir__))} — port block #{base}..#{base + BLOCK_SIZE - 1}"
  puts
  ASSIGNMENTS.each do |offset, (var, role)|
    port = base + offset
    puts format("  %-18s %-6d %-52s %s", var, port, role, free?(port) ? "" : "(in use)")
  end
  puts
  puts "  #{PORTS_ENV}"
end

case ARGV[0]
when "init"
  base = read_allocation
  if base
    puts "devports: allocation exists (PORT_BASE=#{base})"
  else
    base = write_allocation(pick_base)
    puts "devports: allocated PORT_BASE=#{base}"
  end
  show(base)
when "ensure"
  base = read_allocation
  if base.nil?
    base = write_allocation(pick_base)
    puts "devports: allocated PORT_BASE=#{base}"
  elsif !block_free?(base)
    taken = ports_for(base).reject { |p| free?(p) }
    old = base
    base = write_allocation(pick_base)
    puts "devports: block #{old} has ports in use (#{taken.join(', ')}) — reallocated PORT_BASE=#{base}"
  end
  puts PORTS_ENV
when "show"
  base = read_allocation or abort("devports: no allocation — run `rake dev:ports:init`")
  show(base)
else
  abort("usage: devports.rb init|ensure|show")
end
