#!/usr/bin/env ruby
# frozen_string_literal: true

# Extract jed's compact Unicode case-mapping source (`spec/collation/17.0.0/casing.txt`) from the raw
# Unicode Character Database files `UnicodeData.txt` + `SpecialCasing.txt` (spec/design/collation.md
# §16, spec/collation/README.md §5). This is the casing analogue of the committed `root.allkeys`
# collation source: a build-time, host-dependent extraction whose *output* is pinned (the committed
# `casing.txt` + the compiled property section in `unicode.jucd`), never trusted per-run — exactly
# `ExtractHostCollation`'s posture (the running engine never reads the UCD; it loads the bundle).
#
# It is NOT run in CI and depends on UCD files that are not committed (they are multi-MB). Run it by
# hand only on a Unicode version bump, pointing it at a downloaded UCD directory:
#
#   ruby scripts/extract_casing.rb /path/to/ucd        # default: /tmp/ucd
#   # then: cargo run --release --bin build_collation_bundle   (re-packs unicode.jucd)
#   #       cargo run --release --bin gen_collation_vectors    (re-pins the casing vectors)
#
# Output format (casing.txt, spec/collation/README.md §5 — parsed by `compile_casing`, collation.rs):
#   @version <unicode_version>
#   <CP> ; <UPPER> ; <LOWER> ; <TITLE>            # simple 1:1 mappings ('-' = identity = CP)
#   @special
#   <CP> ; <UPPER…> ; <LOWER…> ; <TITLE…>          # full (multi-CP) UNCONDITIONAL mappings ('-' = [CP])
#
# Only code points with a non-identity mapping are emitted, ascending by code point. Conditional /
# locale-specific SpecialCasing entries (Turkish dotted-I, Greek final-sigma) are SKIPPED — the first
# cut is unconditional only (collation.md §16). Simple mappings come from UnicodeData fields 12/13/14
# (Upper/Lower/Title); a code point may appear in BOTH sections (the special/full mapping wins at use).

UCD = ARGV[0] || "/tmp/ucd"
VERSION = "17.0.0" # the version the produced data is pinned to (collation.md §16; common cased code
# points are version-stable, so this matches the live oracle's casing for the letters the corpus checks)

OUT = File.expand_path("../spec/collation/17.0.0/casing.txt", __dir__)

def parse_cp(s)
  s.strip.empty? ? nil : Integer(s.strip, 16)
end

def parse_seq(s)
  s.strip.split(/\s+/).map { |t| Integer(t, 16) }
end

# --- simple case mappings (UnicodeData.txt) ----------------------------------------------------
# Fields (0-based): [0] code, [12] simple uppercase, [13] simple lowercase, [14] simple titlecase.
# Empty field == identity (the character maps to itself). Range markers (<…, First>/<…, Last>) carry
# no case mappings, so they fall out naturally.
simple = []
File.foreach(File.join(UCD, "UnicodeData.txt")) do |line|
  f = line.chomp.split(";", -1)
  next if f.length < 15

  cp = Integer(f[0], 16)
  up = parse_cp(f[12]) || cp
  lo = parse_cp(f[13]) || cp
  ti = parse_cp(f[14]) || cp
  next if up == cp && lo == cp && ti == cp

  simple << [cp, up, lo, ti]
end
simple.sort_by!(&:first)

# --- full (special) case mappings (SpecialCasing.txt) ------------------------------------------
# Format: <code>; <lower>; <title>; <upper>; (<condition>;)? # <comment>. We keep ONLY unconditional
# entries — a 5th data field (before the comment) is a language/context condition we skip (§16).
special = []
File.foreach(File.join(UCD, "SpecialCasing.txt")) do |line|
  body = line.split("#", 2).first.to_s
  parts = body.split(";").map(&:strip)
  parts.pop while !parts.empty? && parts.last.empty?
  next if parts.length != 4 # 5 ⇒ conditional (skip); <4 ⇒ blank/garbage

  cp = Integer(parts[0], 16)
  lower = parse_seq(parts[1])
  title = parse_seq(parts[2])
  upper = parse_seq(parts[3])
  special << [cp, upper, lower, title]
end
special.sort_by!(&:first)

# --- emit --------------------------------------------------------------------------------------
def fmt_cp(v) = format("%04X", v)

def fmt_simple_field(mapped, cp) = mapped == cp ? "-" : fmt_cp(mapped)

def fmt_seq_field(seq, cp) = seq == [cp] ? "-" : seq.map { |v| fmt_cp(v) }.join(" ")

File.open(OUT, "w") do |io|
  io.puts "# Unicode case mappings — UCD #{VERSION} (spec/design/collation.md §16, README §5)."
  io.puts "# GENERATED by scripts/extract_casing.rb from UnicodeData.txt + SpecialCasing.txt; the"
  io.puts "# compact, auditable source `compile_casing` (collation.rs) compiles into the JUCD bundle's"
  io.puts "# property section. The bare binary carries no casing data; a host loads this via the bundle."
  io.puts "# Simple: CP ; UPPER ; LOWER ; TITLE  ('-' = identity = CP). @special: full unconditional"
  io.puts "# mappings, CP ; UPPER… ; LOWER… ; TITLE… (space-separated, '-' = [CP]). Conditional /"
  io.puts "# locale entries (Turkish I, final sigma) are omitted — unconditional first cut (§16)."
  io.puts "# Licensed under the Unicode License v3 (https://www.unicode.org/license.txt)."
  io.puts
  io.puts "@version #{VERSION}"
  simple.each do |cp, up, lo, ti|
    io.puts "#{fmt_cp(cp)} ; #{fmt_simple_field(up, cp)} ; #{fmt_simple_field(lo, cp)} ; #{fmt_simple_field(ti, cp)}"
  end
  io.puts
  io.puts "@special"
  special.each do |cp, up, lo, ti|
    io.puts "#{fmt_cp(cp)} ; #{fmt_seq_field(up, cp)} ; #{fmt_seq_field(lo, cp)} ; #{fmt_seq_field(ti, cp)}"
  end
end

puts "wrote #{OUT}: #{simple.length} simple + #{special.length} special (unconditional) mappings"
