#!/usr/bin/env ruby
# frozen_string_literal: true

# Codegen "middle path" (CLAUDE.md §5): generate the per-language SqlState enum + its
# SQLSTATE code mapping from the canonical spec/errors/registry.toml. This emits the
# error-code DATA only — the EngineError scaffolding that CONSUMES it (message assembly,
# Display/Error rendering, the raise sites scattered through the executor) stays
# hand-written per core (§5 forbids codegenning the evaluator). Build-time only; no
# shipped core runs Ruby or parses TOML.
#
#   ruby scripts/gen_errors.rb            # (re)write the generated files
#   ruby scripts/gen_errors.rb --check    # fail if any checked-in file is stale
#
# Each variant carries its registry `template` as a one-line doc; the full rationale lives
# in spec/errors/registry.toml. The reasoning lives in spec/design/codegen.md — read it
# before editing this file.

require "bundler/setup"
require "toml-rb"

REPO = File.expand_path("..", __dir__)
REGISTRY = File.join(REPO, "spec", "errors", "registry.toml")

# (relative path, builder method) for each generated file.
TARGETS = [
  ["impl/rust/src/sqlstate.rs", :rust_file],
  ["impl/go/sqlstate.go",       :go_file],
  ["impl/ts/src/sqlstate.ts",   :ts_file],
].freeze

def fail!(msg)
  warn "FAIL: #{msg}"
  exit 1
end

# --- shared field access -----------------------------------------------------

def errors
  registry = TomlRB.load_file(REGISTRY)
  es = registry["error"] || []
  fail!("#{REGISTRY}: no [[error]] entries") if es.empty?
  es
end

# snake_case name -> PascalCase variant (Rust/Go). The cores already use this exact
# spelling (io_error -> IoError, active_sql_transaction -> ActiveSqlTransaction), so the
# generated variant names match the hand-written ones byte-for-byte.
def pascal(name) = name.split("_").map(&:capitalize).join

# --- Rust --------------------------------------------------------------------

def rust_variant(e)
  ["    /// #{e['code']} — #{e['template']}", "    #{pascal(e['name'])},"].join("\n")
end

def rust_arm(e) = "            SqlState::#{pascal(e['name'])} => \"#{e['code']}\","

def rust_desc(e)
  %(    ErrorDesc { code: "#{e['code']}", name: "#{e['name']}", class: "#{e['class']}" },)
end

def rust_file(es)
  <<~RS
    // @generated by scripts/gen_errors.rb from spec/errors/registry.toml — DO NOT EDIT.
    //
    // SQLSTATE error codes (CLAUDE.md §5, §10: the codegen "middle path"). DATA only — the
    // EngineError scaffolding that CONSUMES these (message assembly, Display, the raise sites
    // through the executor) is hand-written in error.rs (§5 forbids codegenning those).
    // Regenerate with `rake codegen`; `rake verify` fails if this file is stale. Each variant's
    // message template + rationale live in spec/errors/registry.toml. Reasoning:
    // ../../../spec/design/codegen.md.

    /// A structured engine error's SQLSTATE. The string value is the canonical 5-char code from
    /// spec/errors/registry.toml (cross-checked in tests). Declaration order is registry order
    /// and carries no meaning — the discriminant is never serialized.
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    pub enum SqlState {
    #{es.map { |e| rust_variant(e) }.join("\n")}
    }

    impl SqlState {
        /// The canonical 5-char SQLSTATE string (spec/errors/registry.toml).
        pub fn code(self) -> &'static str {
            match self {
    #{es.map { |e| rust_arm(e) }.join("\n")}
            }
        }
    }

    /// One error's metadata, mirroring an `[[error]]` entry in registry.toml. The enum above is
    /// the type-safe code used at raise sites; this slice is the iterable data table the
    /// cross-check tests walk against the registry (the enum is not iterable).
    pub struct ErrorDesc {
        pub code: &'static str,
        pub name: &'static str,
        pub class: &'static str,
    }

    /// Every error, in registry order.
    #[rustfmt::skip]
    pub const ERRORS: &[ErrorDesc] = &[
    #{es.map { |e| rust_desc(e) }.join("\n")}
    ];
  RS
end

# --- Go ----------------------------------------------------------------------

def go_str(s) = %("#{s}")

def go_const(e, first)
  decl = first ? "#{pascal(e['name'])} SqlState = iota" : pascal(e["name"])
  ["\t// #{pascal(e['name'])} is #{e['code']} — #{e['template']}.", "\t#{decl}"].join("\n")
end

def go_arm(e)
  ["\tcase #{pascal(e['name'])}:", "\t\treturn #{go_str(e['code'])}"].join("\n")
end

def go_desc(e)
  "\t{Code: #{go_str(e['code'])}, Name: #{go_str(e['name'])}, Class: #{go_str(e['class'])}},"
end

def go_file(es)
  consts = es.each_with_index.map { |e, i| go_const(e, i.zero?) }.join("\n")
  arms = es.map { |e| go_arm(e) }.join("\n")
  descs = es.map { |e| go_desc(e) }.join("\n")
  <<~GO
    // Code generated by scripts/gen_errors.rb from spec/errors/registry.toml. DO NOT EDIT.
    //
    // SQLSTATE error codes (CLAUDE.md §5, §10: the codegen "middle path"). DATA only — the
    // EngineError scaffolding that CONSUMES these (message assembly, Error rendering, the raise
    // sites through the executor) is hand-written in errors.go (§5 forbids codegenning those).
    // Regenerate with `rake codegen`; `rake verify` fails if this file is stale. Each variant's
    // message template + rationale live in spec/errors/registry.toml. Reasoning:
    // ../../spec/design/codegen.md.

    package jed

    // SqlState is a structured engine error's SQLSTATE. Its Code() string is the canonical 5-char
    // code from spec/errors/registry.toml (cross-checked in tests). Declaration order is registry
    // order and carries no meaning — the iota value is never serialized.
    type SqlState int

    const (
    #{consts}
    )

    // Code returns the canonical SQLSTATE string.
    func (s SqlState) Code() string {
    \tswitch s {
    #{arms}
    \tdefault:
    \t\treturn "XX000"
    \t}
    }

    // ErrorDesc is one error's metadata, mirroring an [[error]] entry in registry.toml. The enum
    // above is the type-safe code used at raise sites; Errors is the iterable data table the
    // cross-check tests walk against the registry (the enum is not iterable).
    type errorDesc struct {
    \tCode  string
    \tName  string
    \tClass string
    }

    // Errors lists every error, in registry order.
    var errorDescs = []errorDesc{
    #{descs}
    }
  GO
end

# --- TypeScript --------------------------------------------------------------

def ts_member(e, last)
  term = last ? ";" : ""
  %(  | "#{e['name']}"#{term} // #{e['code']} — #{e['template']})
end

def ts_code(e) = %(  #{e['name']}: "#{e['code']}",)

def ts_desc(e)
  %(  { code: "#{e['code']}", name: "#{e['name']}", class: "#{e['class']}" },)
end

def ts_file(es)
  members = es.each_with_index.map { |e, i| ts_member(e, i == es.length - 1) }.join("\n")
  codes = es.map { |e| ts_code(e) }.join("\n")
  descs = es.map { |e| ts_desc(e) }.join("\n")
  <<~TS
    // @generated by scripts/gen_errors.rb from spec/errors/registry.toml — DO NOT EDIT.
    //
    // SQLSTATE error codes (CLAUDE.md §5, §10: the codegen "middle path"). DATA only — the
    // EngineError scaffolding that CONSUMES these (message assembly, the raise sites through the
    // executor) is hand-written in errors.ts (§5 forbids codegenning those). Regenerate with
    // `rake codegen`; `rake verify` fails if this file is stale. Each variant's message template +
    // rationale live in spec/errors/registry.toml. Reasoning: ../../../spec/design/codegen.md.
    //
    // SqlState is a string-literal union (not a TS enum — the elidable subset forbids enums), and
    // the union member IS the canonical snake_case name from the registry.

    export type SqlState =
    #{members}

    const CODES: Record<SqlState, string> = {
    #{codes}
    };

    // sqlStateCode returns the canonical SQLSTATE string for a state.
    export function sqlStateCode(state: SqlState): string {
      return CODES[state];
    }

    // One error's metadata, mirroring an [[error]] entry in registry.toml. The union above is
    // the type-safe code (and CODES its O(1) lookup); ERRORS is the iterable data table the
    // cross-check tests walk against the registry.
    export interface ErrorDesc {
      code: string;
      name: string;
      class: string;
    }

    // Every error, in registry order.
    export const ERRORS: readonly ErrorDesc[] = [
    #{descs}
    ];
  TS
end

# --- driver ------------------------------------------------------------------

def main
  check = ARGV.include?("--check")
  es = errors
  stale = []

  TARGETS.each do |rel, builder|
    path = File.join(REPO, rel)
    content = send(builder, es)
    if check
      current = File.exist?(path) ? File.read(path) : nil
      stale << rel unless current == content
    else
      File.write(path, content)
      puts "wrote #{rel}"
    end
  end

  if check
    unless stale.empty?
      stale.each { |rel| warn "STALE: #{rel} — run 'rake codegen'" }
      exit 1
    end
    puts "OK: #{TARGETS.length} generated files current (#{es.length} error codes)"
  end
end

main
