#!/usr/bin/env ruby
# frozen_string_literal: true

# Codegen "middle path" (CLAUDE.md §5): generate per-language operator DESCRIPTOR
# tables from the canonical spec/functions/catalog.toml. This emits DATA only — the
# parser, executor, and the eq3/lt3 evaluation logic that CONSUME the descriptors are
# hand-written (§5 forbids codegenning those). Build-time only; no shipped core runs
# Ruby or parses TOML.
#
#   ruby scripts/gen_catalog.rb            # (re)write the generated files
#   ruby scripts/gen_catalog.rb --check    # fail if any checked-in file is stale
#
# The reasoning lives in spec/design/codegen.md — read it before editing this file.

require "bundler/setup"
require "toml-rb"

REPO = File.expand_path("..", __dir__)
CATALOG = File.join(REPO, "spec", "functions", "catalog.toml")

# (relative path, builder method) for each generated file.
TARGETS = [
  ["impl/rust/src/operators.rs", :rust_file],
  ["impl/go/operators.go",       :go_file],
  ["impl/ts/src/operators.ts",   :ts_file],
].freeze

def fail!(msg)
  warn "FAIL: #{msg}"
  exit 1
end

# --- shared field access -----------------------------------------------------

def operators
  catalog = TomlRB.load_file(CATALOG)
  ops = catalog["operator"] || []
  fail!("#{CATALOG}: no [[operator]] entries") if ops.empty?
  ops
end

# Aggregate functions (kind = "aggregate") — a separate descriptor table emitted
# alongside the operators. Aggregates are not operators (no symbol/precedence), so they
# get their own struct/field set. May be empty (the engine had none before this slice).
def aggregates
  catalog = TomlRB.load_file(CATALOG)
  catalog["aggregate"] || []
end

# Set-returning functions (kind = "set_returning") — a separate descriptor table again.
# An SRF expands its args into a row SET (generate_series), so it fits neither the operator
# nor the aggregate mold; it carries its own field set (surface/arity/arg_families/result/
# column/null/errors). May be empty.
def set_returning
  catalog = TomlRB.load_file(CATALOG)
  catalog["set_returning"] || []
end

# --- Rust --------------------------------------------------------------------

def rust_str(s) = %("#{s}")
def rust_slice(arr) = arr.empty? ? "&[]" : "&[#{arr.map { |x| rust_str(x) }.join(', ')}]"

def rust_entry(op)
  sym = op["symbol"] ? "Some(#{rust_str(op['symbol'])})" : "None"
  [
    "    OperatorDesc {",
    "        name: #{rust_str(op['name'])},",
    "        symbol: #{sym},",
    "        kind: #{rust_str(op['kind'])},",
    "        arity: #{op['arity']},",
    "        arg_families: #{rust_slice(op['arg_families'])},",
    "        arg_resolution: #{rust_str(op['arg_resolution'])},",
    "        result: #{rust_str(op['result'])},",
    "        null: #{rust_str(op['null'])},",
    "        precedence: #{op['precedence'] || 0},",
    "        errors: #{rust_slice(op['errors'])},",
    "        arg_names: #{rust_slice(op['arg_names'] || [])},",
    "        arg_defaults: #{rust_slice(op['arg_defaults'] || [])},",
    "    },",
  ].join("\n")
end

def rust_agg_entry(ag)
  [
    "    AggregateDesc {",
    "        name: #{rust_str(ag['name'])},",
    "        surface: #{rust_str(ag['surface'])},",
    "        arg: #{rust_str(ag['arg'])},",
    "        arg_families: #{rust_slice(ag['arg_families'] || [])},",
    "        result: #{rust_str(ag['result'])},",
    "        null: #{rust_str(ag['null'])},",
    "        errors: #{rust_slice(ag['errors'])},",
    "    },",
  ].join("\n")
end

def rust_srf_entry(sf)
  [
    "    SetReturningDesc {",
    "        name: #{rust_str(sf['name'])},",
    "        surface: #{rust_str(sf['surface'])},",
    "        arity: #{sf['arity']},",
    "        arg_families: #{rust_slice(sf['arg_families'] || [])},",
    "        arg_resolution: #{rust_str(sf['arg_resolution'])},",
    "        result: #{rust_str(sf['result'])},",
    "        column: #{rust_str(sf['column'])},",
    "        null: #{rust_str(sf['null'])},",
    "        errors: #{rust_slice(sf['errors'])},",
    "    },",
  ].join("\n")
end

def rust_file(ops, aggs, srfs)
  <<~RS
    // @generated by scripts/gen_catalog.rb from spec/functions/catalog.toml — DO NOT EDIT.
    //
    // Operator + aggregate descriptor tables (CLAUDE.md §5: the codegen "middle path").
    // This is DATA only — the parser, executor, and the eq3/lt3 evaluation logic that
    // CONSUME it are hand-written (§5 forbids codegenning those). Regenerate with
    // `rake codegen`; `rake verify` fails if this file is stale. Reasoning:
    // ../../../spec/design/codegen.md.

    /// One operator's metadata, mirroring a `[[operator]]` entry in catalog.toml.
    pub struct OperatorDesc {
        pub name: &'static str,
        pub symbol: Option<&'static str>,
        pub kind: &'static str,
        pub arity: u8,
        pub arg_families: &'static [&'static str],
        pub arg_resolution: &'static str,
        pub result: &'static str,
        pub null: &'static str,
        pub precedence: u8,
        pub errors: &'static [&'static str],
        /// Parameter names for PostgreSQL named notation (functions.md §11); empty = none.
        pub arg_names: &'static [&'static str],
        /// Integer-literal DEFAULTs for the trailing parameters; empty = none.
        pub arg_defaults: &'static [&'static str],
    }

    /// Every operator in the catalog, in catalog order.
    #[rustfmt::skip]
    pub const OPERATORS: &[OperatorDesc] = &[
    #{ops.map { |op| rust_entry(op) }.join("\n")}
    ];

    /// One aggregate function's metadata, mirroring an `[[aggregate]]` entry in
    /// catalog.toml. Aggregates are not operators (no symbol/precedence/arg_resolution);
    /// `arg` is "star" (COUNT(*)) or "expr"; `result` is a scalar id or a reserved
    /// widening id (sum_widen | same_as_input). See spec/design/aggregates.md.
    pub struct AggregateDesc {
        pub name: &'static str,
        pub surface: &'static str,
        pub arg: &'static str,
        pub arg_families: &'static [&'static str],
        pub result: &'static str,
        pub null: &'static str,
        pub errors: &'static [&'static str],
    }

    /// Every aggregate in the catalog, in catalog order.
    #[rustfmt::skip]
    pub const AGGREGATES: &[AggregateDesc] = &[
    #{aggs.map { |ag| rust_agg_entry(ag) }.join("\n")}
    ];

    /// One set-returning function's metadata, mirroring a `[[set_returning]]` entry in
    /// catalog.toml. An SRF expands its args into a row SET (not a scalar/aggregate value);
    /// `result` is a reserved set id (set_of_promoted), `column` is the fixed output column
    /// name, and `null` = "empty_on_null" (any NULL arg → zero rows). The uniqueness key is
    /// (name, arity). See spec/design/functions.md §10.
    pub struct SetReturningDesc {
        pub name: &'static str,
        pub surface: &'static str,
        pub arity: u8,
        pub arg_families: &'static [&'static str],
        pub arg_resolution: &'static str,
        pub result: &'static str,
        pub column: &'static str,
        pub null: &'static str,
        pub errors: &'static [&'static str],
    }

    /// Every set-returning function in the catalog, in catalog order.
    #[rustfmt::skip]
    pub const SET_RETURNING: &[SetReturningDesc] = &[
    #{srfs.map { |sf| rust_srf_entry(sf) }.join("\n")}
    ];
  RS
end

# --- Go ----------------------------------------------------------------------

def go_str(s) = %("#{s}")
def go_slice(arr) = arr.empty? ? "[]string{}" : "[]string{#{arr.map { |x| go_str(x) }.join(', ')}}"

def go_entry(op)
  fields = [
    ["Name",          go_str(op["name"])],
    ["Symbol",        go_str(op["symbol"] || "")],
    ["Kind",          go_str(op["kind"])],
    ["Arity",         op["arity"].to_s],
    ["ArgFamilies",   go_slice(op["arg_families"])],
    ["ArgResolution", go_str(op["arg_resolution"])],
    ["Result",        go_str(op["result"])],
    ["Null",          go_str(op["null"])],
    ["Precedence",    (op["precedence"] || 0).to_s],
    ["Errors",        go_slice(op["errors"])],
    ["ArgNames",      go_slice(op["arg_names"] || [])],
    ["ArgDefaults",   go_slice(op["arg_defaults"] || [])],
  ]
  w = fields.map { |k, _| k.length }.max
  lines = fields.map { |k, v| "\t\t#{k}:#{' ' * (w - k.length + 1)}#{v}," }
  "\t{\n#{lines.join("\n")}\n\t},"
end

def go_agg_entry(ag)
  fields = [
    ["Name",        go_str(ag["name"])],
    ["Surface",     go_str(ag["surface"])],
    ["Arg",         go_str(ag["arg"])],
    ["ArgFamilies", go_slice(ag["arg_families"] || [])],
    ["Result",      go_str(ag["result"])],
    ["Null",        go_str(ag["null"])],
    ["Errors",      go_slice(ag["errors"])],
  ]
  w = fields.map { |k, _| k.length }.max
  lines = fields.map { |k, v| "\t\t#{k}:#{' ' * (w - k.length + 1)}#{v}," }
  "\t{\n#{lines.join("\n")}\n\t},"
end

def go_srf_entry(sf)
  fields = [
    ["Name",          go_str(sf["name"])],
    ["Surface",       go_str(sf["surface"])],
    ["Arity",         sf["arity"].to_s],
    ["ArgFamilies",   go_slice(sf["arg_families"] || [])],
    ["ArgResolution", go_str(sf["arg_resolution"])],
    ["Result",        go_str(sf["result"])],
    ["Column",        go_str(sf["column"])],
    ["Null",          go_str(sf["null"])],
    ["Errors",        go_slice(sf["errors"])],
  ]
  w = fields.map { |k, _| k.length }.max
  lines = fields.map { |k, v| "\t\t#{k}:#{' ' * (w - k.length + 1)}#{v}," }
  "\t{\n#{lines.join("\n")}\n\t},"
end

def go_file(ops, aggs, srfs)
  <<~GO
    // Code generated by scripts/gen_catalog.rb from spec/functions/catalog.toml. DO NOT EDIT.
    //
    // Operator + aggregate descriptor tables (CLAUDE.md §5: the codegen "middle path").
    // DATA only — the parser, executor, and the Eq3/Lt3 evaluation logic that CONSUME it
    // are hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
    // `rake verify` fails if this file is stale. Reasoning: ../../spec/design/codegen.md.

    package jed

    // OperatorDesc is one operator's metadata, mirroring a [[operator]] entry in catalog.toml.
    // Symbol is "" for operators with no infix symbol (the IS [NOT] NULL tests).
    type OperatorDesc struct {
    \tName          string
    \tSymbol        string
    \tKind          string
    \tArity         int
    \tArgFamilies   []string
    \tArgResolution string
    \tResult        string
    \tNull          string
    \tPrecedence    int
    \tErrors        []string
    \t// ArgNames holds the parameter names for PostgreSQL named notation (functions.md §11);
    \t// empty = none. ArgDefaults holds integer-literal DEFAULTs for the trailing parameters.
    \tArgNames    []string
    \tArgDefaults []string
    }

    // Operators lists every operator in the catalog, in catalog order.
    var Operators = []OperatorDesc{
    #{ops.map { |op| go_entry(op) }.join("\n")}
    }

    // AggregateDesc is one aggregate function's metadata, mirroring an [[aggregate]] entry
    // in catalog.toml. Aggregates are not operators (no symbol/precedence/arg_resolution);
    // Arg is "star" (COUNT(*)) or "expr"; Result is a scalar id or a reserved widening id
    // (sum_widen | same_as_input). See spec/design/aggregates.md.
    type AggregateDesc struct {
    \tName        string
    \tSurface     string
    \tArg         string
    \tArgFamilies []string
    \tResult      string
    \tNull        string
    \tErrors      []string
    }

    // Aggregates lists every aggregate in the catalog, in catalog order.
    var Aggregates = []AggregateDesc{
    #{aggs.map { |ag| go_agg_entry(ag) }.join("\n")}
    }

    // SetReturningDesc is one set-returning function's metadata, mirroring a [[set_returning]]
    // entry in catalog.toml. An SRF expands its args into a row SET (not a scalar/aggregate
    // value); Result is a reserved set id (set_of_promoted), Column is the fixed output column
    // name, and Null = "empty_on_null" (any NULL arg -> zero rows). The uniqueness key is
    // (Name, Arity). See spec/design/functions.md §10.
    type SetReturningDesc struct {
    \tName          string
    \tSurface       string
    \tArity         int
    \tArgFamilies   []string
    \tArgResolution string
    \tResult        string
    \tColumn        string
    \tNull          string
    \tErrors        []string
    }

    // SetReturning lists every set-returning function in the catalog, in catalog order.
    var SetReturning = []SetReturningDesc{
    #{srfs.map { |sf| go_srf_entry(sf) }.join("\n")}
    }
  GO
end

# --- TypeScript --------------------------------------------------------------

def ts_str(s) = %("#{s}")
def ts_arr(arr) = "[#{arr.map { |x| ts_str(x) }.join(', ')}]"

def ts_entry(op)
  lines = ["  {"]
  lines << "    name: #{ts_str(op['name'])},"
  lines << "    symbol: #{ts_str(op['symbol'])}," if op["symbol"]
  lines << "    kind: #{ts_str(op['kind'])},"
  lines << "    arity: #{op['arity']},"
  lines << "    argFamilies: #{ts_arr(op['arg_families'])},"
  lines << "    argResolution: #{ts_str(op['arg_resolution'])},"
  lines << "    result: #{ts_str(op['result'])},"
  lines << "    null: #{ts_str(op['null'])},"
  lines << "    precedence: #{op['precedence'] || 0},"
  lines << "    errors: #{ts_arr(op['errors'])},"
  lines << "    argNames: #{ts_arr(op['arg_names'] || [])},"
  lines << "    argDefaults: #{ts_arr(op['arg_defaults'] || [])},"
  lines << "  },"
  lines.join("\n")
end

def ts_agg_entry(ag)
  lines = ["  {"]
  lines << "    name: #{ts_str(ag['name'])},"
  lines << "    surface: #{ts_str(ag['surface'])},"
  lines << "    arg: #{ts_str(ag['arg'])},"
  lines << "    argFamilies: #{ts_arr(ag['arg_families'] || [])},"
  lines << "    result: #{ts_str(ag['result'])},"
  lines << "    null: #{ts_str(ag['null'])},"
  lines << "    errors: #{ts_arr(ag['errors'])},"
  lines << "  },"
  lines.join("\n")
end

def ts_srf_entry(sf)
  lines = ["  {"]
  lines << "    name: #{ts_str(sf['name'])},"
  lines << "    surface: #{ts_str(sf['surface'])},"
  lines << "    arity: #{sf['arity']},"
  lines << "    argFamilies: #{ts_arr(sf['arg_families'] || [])},"
  lines << "    argResolution: #{ts_str(sf['arg_resolution'])},"
  lines << "    result: #{ts_str(sf['result'])},"
  lines << "    column: #{ts_str(sf['column'])},"
  lines << "    null: #{ts_str(sf['null'])},"
  lines << "    errors: #{ts_arr(sf['errors'])},"
  lines << "  },"
  lines.join("\n")
end

def ts_file(ops, aggs, srfs)
  <<~TS
    // @generated by scripts/gen_catalog.rb from spec/functions/catalog.toml — DO NOT EDIT.
    //
    // Operator + aggregate descriptor tables (CLAUDE.md §5: the codegen "middle path").
    // DATA only — the parser, executor, and the eq3/lt3 evaluation logic that CONSUME it
    // are hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
    // `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/codegen.md.

    // One operator's metadata, mirroring a [[operator]] entry in catalog.toml. `symbol` is
    // absent for operators with no infix symbol (the IS [NOT] NULL tests).
    export interface OperatorDesc {
      name: string;
      symbol?: string;
      kind: string;
      arity: number;
      argFamilies: readonly string[];
      argResolution: string;
      result: string;
      null: string;
      precedence: number;
      errors: readonly string[];
      // Parameter names for PostgreSQL named notation (functions.md §11); empty = none.
      argNames: readonly string[];
      // Integer-literal DEFAULTs for the trailing parameters; empty = none.
      argDefaults: readonly string[];
    }

    // Every operator in the catalog, in catalog order.
    export const OPERATORS: readonly OperatorDesc[] = [
    #{ops.map { |op| ts_entry(op) }.join("\n")}
    ];

    // One aggregate function's metadata, mirroring an [[aggregate]] entry in catalog.toml.
    // Aggregates are not operators (no symbol/precedence/argResolution); `arg` is "star"
    // (COUNT(*)) or "expr"; `result` is a scalar id or a reserved widening id (sum_widen |
    // same_as_input). See spec/design/aggregates.md.
    export interface AggregateDesc {
      name: string;
      surface: string;
      arg: string;
      argFamilies: readonly string[];
      result: string;
      null: string;
      errors: readonly string[];
    }

    // Every aggregate in the catalog, in catalog order.
    export const AGGREGATES: readonly AggregateDesc[] = [
    #{aggs.map { |ag| ts_agg_entry(ag) }.join("\n")}
    ];

    // One set-returning function's metadata, mirroring a [[set_returning]] entry in
    // catalog.toml. An SRF expands its args into a row SET (not a scalar/aggregate value);
    // `result` is a reserved set id (set_of_promoted), `column` is the fixed output column
    // name, and `null` = "empty_on_null" (any NULL arg → zero rows). The uniqueness key is
    // (name, arity). See spec/design/functions.md §10.
    export interface SetReturningDesc {
      name: string;
      surface: string;
      arity: number;
      argFamilies: readonly string[];
      argResolution: string;
      result: string;
      column: string;
      null: string;
      errors: readonly string[];
    }

    // Every set-returning function in the catalog, in catalog order.
    export const SET_RETURNING: readonly SetReturningDesc[] = [
    #{srfs.map { |sf| ts_srf_entry(sf) }.join("\n")}
    ];
  TS
end

# --- driver ------------------------------------------------------------------

def main
  check = ARGV.include?("--check")
  ops = operators
  aggs = aggregates
  srfs = set_returning
  stale = []

  TARGETS.each do |rel, builder|
    path = File.join(REPO, rel)
    content = send(builder, ops, aggs, srfs)
    if check
      current = File.exist?(path) ? File.read(path) : nil
      stale << rel unless current == content
    else
      File.write(path, content)
      puts "wrote #{rel}"
    end
  end

  if check
    unless stale.empty?
      stale.each { |rel| warn "STALE: #{rel} — run 'rake codegen'" }
      exit 1
    end
    puts "OK: #{TARGETS.length} generated files current (#{ops.length} operators, #{aggs.length} aggregates, #{srfs.length} set-returning)"
  end
end

main
