#!/usr/bin/env ruby
# frozen_string_literal: true

# Codegen "middle path" (CLAUDE.md §5): generate per-language operator DESCRIPTOR
# tables from the canonical spec/functions/catalog.toml. This emits DATA only — the
# parser, executor, and the eq3/lt3 evaluation logic that CONSUME the descriptors are
# hand-written (§5 forbids codegenning those). Build-time only; no shipped core runs
# Ruby or parses TOML.
#
#   ruby scripts/gen_catalog.rb            # (re)write the generated files
#   ruby scripts/gen_catalog.rb --check    # fail if any checked-in file is stale
#
# The reasoning lives in spec/design/codegen.md — read it before editing this file.

require "bundler/setup"
require "toml-rb"

REPO = File.expand_path("..", __dir__)
CATALOG = File.join(REPO, "spec", "functions", "catalog.toml")

# (relative path, builder method) for each generated file.
TARGETS = [
  ["impl/rust/src/operators.rs", :rust_file],
  ["impl/go/operators.go",       :go_file],
  ["impl/ts/src/operators.ts",   :ts_file],
].freeze

def fail!(msg)
  warn "FAIL: #{msg}"
  exit 1
end

# --- shared field access -----------------------------------------------------

def operators
  catalog = TomlRB.load_file(CATALOG)
  ops = catalog["operator"] || []
  fail!("#{CATALOG}: no [[operator]] entries") if ops.empty?
  ops
end

# --- Rust --------------------------------------------------------------------

def rust_str(s) = %("#{s}")
def rust_slice(arr) = arr.empty? ? "&[]" : "&[#{arr.map { |x| rust_str(x) }.join(', ')}]"

def rust_entry(op)
  sym = op["symbol"] ? "Some(#{rust_str(op['symbol'])})" : "None"
  [
    "    OperatorDesc {",
    "        name: #{rust_str(op['name'])},",
    "        symbol: #{sym},",
    "        kind: #{rust_str(op['kind'])},",
    "        arity: #{op['arity']},",
    "        arg_families: #{rust_slice(op['arg_families'])},",
    "        arg_resolution: #{rust_str(op['arg_resolution'])},",
    "        result: #{rust_str(op['result'])},",
    "        null: #{rust_str(op['null'])},",
    "        precedence: #{op['precedence'] || 0},",
    "        errors: #{rust_slice(op['errors'])},",
    "    },",
  ].join("\n")
end

def rust_file(ops)
  <<~RS
    // @generated by scripts/gen_catalog.rb from spec/functions/catalog.toml — DO NOT EDIT.
    //
    // Operator descriptor table (CLAUDE.md §5: the codegen "middle path"). This is DATA
    // only — the parser, executor, and the eq3/lt3 evaluation logic that CONSUME it are
    // hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
    // `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/codegen.md.

    /// One operator's metadata, mirroring a `[[operator]]` entry in catalog.toml.
    pub struct OperatorDesc {
        pub name: &'static str,
        pub symbol: Option<&'static str>,
        pub kind: &'static str,
        pub arity: u8,
        pub arg_families: &'static [&'static str],
        pub arg_resolution: &'static str,
        pub result: &'static str,
        pub null: &'static str,
        pub precedence: u8,
        pub errors: &'static [&'static str],
    }

    /// Every operator in the catalog, in catalog order.
    pub const OPERATORS: &[OperatorDesc] = &[
    #{ops.map { |op| rust_entry(op) }.join("\n")}
    ];
  RS
end

# --- Go ----------------------------------------------------------------------

def go_str(s) = %("#{s}")
def go_slice(arr) = arr.empty? ? "[]string{}" : "[]string{#{arr.map { |x| go_str(x) }.join(', ')}}"

def go_entry(op)
  fields = [
    ["Name",          go_str(op["name"])],
    ["Symbol",        go_str(op["symbol"] || "")],
    ["Kind",          go_str(op["kind"])],
    ["Arity",         op["arity"].to_s],
    ["ArgFamilies",   go_slice(op["arg_families"])],
    ["ArgResolution", go_str(op["arg_resolution"])],
    ["Result",        go_str(op["result"])],
    ["Null",          go_str(op["null"])],
    ["Precedence",    (op["precedence"] || 0).to_s],
    ["Errors",        go_slice(op["errors"])],
  ]
  w = fields.map { |k, _| k.length }.max
  lines = fields.map { |k, v| "\t\t#{k}:#{' ' * (w - k.length + 1)}#{v}," }
  "\t{\n#{lines.join("\n")}\n\t},"
end

def go_file(ops)
  <<~GO
    // Code generated by scripts/gen_catalog.rb from spec/functions/catalog.toml. DO NOT EDIT.
    //
    // Operator descriptor table (CLAUDE.md §5: the codegen "middle path"). DATA only — the
    // parser, executor, and the Eq3/Lt3 evaluation logic that CONSUME it are hand-written
    // (§5 forbids codegenning those). Regenerate with `rake codegen`; `rake verify` fails
    // if this file is stale. Reasoning: ../../spec/design/codegen.md.

    package jed

    // OperatorDesc is one operator's metadata, mirroring a [[operator]] entry in catalog.toml.
    // Symbol is "" for operators with no infix symbol (the IS [NOT] NULL tests).
    type OperatorDesc struct {
    \tName          string
    \tSymbol        string
    \tKind          string
    \tArity         int
    \tArgFamilies   []string
    \tArgResolution string
    \tResult        string
    \tNull          string
    \tPrecedence    int
    \tErrors        []string
    }

    // Operators lists every operator in the catalog, in catalog order.
    var Operators = []OperatorDesc{
    #{ops.map { |op| go_entry(op) }.join("\n")}
    }
  GO
end

# --- TypeScript --------------------------------------------------------------

def ts_str(s) = %("#{s}")
def ts_arr(arr) = "[#{arr.map { |x| ts_str(x) }.join(', ')}]"

def ts_entry(op)
  lines = ["  {"]
  lines << "    name: #{ts_str(op['name'])},"
  lines << "    symbol: #{ts_str(op['symbol'])}," if op["symbol"]
  lines << "    kind: #{ts_str(op['kind'])},"
  lines << "    arity: #{op['arity']},"
  lines << "    argFamilies: #{ts_arr(op['arg_families'])},"
  lines << "    argResolution: #{ts_str(op['arg_resolution'])},"
  lines << "    result: #{ts_str(op['result'])},"
  lines << "    null: #{ts_str(op['null'])},"
  lines << "    precedence: #{op['precedence'] || 0},"
  lines << "    errors: #{ts_arr(op['errors'])},"
  lines << "  },"
  lines.join("\n")
end

def ts_file(ops)
  <<~TS
    // @generated by scripts/gen_catalog.rb from spec/functions/catalog.toml — DO NOT EDIT.
    //
    // Operator descriptor table (CLAUDE.md §5: the codegen "middle path"). DATA only — the
    // parser, executor, and the eq3/lt3 evaluation logic that CONSUME it are hand-written
    // (§5 forbids codegenning those). Regenerate with `rake codegen`; `rake verify` fails
    // if this file is stale. Reasoning: ../../../spec/design/codegen.md.

    // One operator's metadata, mirroring a [[operator]] entry in catalog.toml. `symbol` is
    // absent for operators with no infix symbol (the IS [NOT] NULL tests).
    export interface OperatorDesc {
      name: string;
      symbol?: string;
      kind: string;
      arity: number;
      argFamilies: readonly string[];
      argResolution: string;
      result: string;
      null: string;
      precedence: number;
      errors: readonly string[];
    }

    // Every operator in the catalog, in catalog order.
    export const OPERATORS: readonly OperatorDesc[] = [
    #{ops.map { |op| ts_entry(op) }.join("\n")}
    ];
  TS
end

# --- driver ------------------------------------------------------------------

def main
  check = ARGV.include?("--check")
  ops = operators
  stale = []

  TARGETS.each do |rel, builder|
    path = File.join(REPO, rel)
    content = send(builder, ops)
    if check
      current = File.exist?(path) ? File.read(path) : nil
      stale << rel unless current == content
    else
      File.write(path, content)
      puts "wrote #{rel}"
    end
  end

  if check
    unless stale.empty?
      stale.each { |rel| warn "STALE: #{rel} — run 'rake codegen'" }
      exit 1
    end
    puts "OK: #{TARGETS.length} generated files current (#{ops.length} operators)"
  end
end

main
