#!/usr/bin/env ruby
# frozen_string_literal: true

# Codegen "middle path" (CLAUDE.md §5): generate per-language cost-schedule constants
# from the canonical spec/cost/schedule.toml. This emits DATA only — the accrual SITES
# (which executor / expression-evaluator / storage line fires which unit, and the cost
# counter threaded through them) are hand-written per core (§5 forbids codegenning the
# evaluator). Build-time only; no shipped core runs Ruby or parses TOML.
#
#   ruby scripts/gen_costs.rb            # (re)write the generated files
#   ruby scripts/gen_costs.rb --check    # fail if any checked-in file is stale
#
# The reasoning lives in spec/design/cost.md (and codegen.md) — read it before editing.

require "bundler/setup"
require "toml-rb"

REPO = File.expand_path("..", __dir__)
SCHEDULE = File.join(REPO, "spec", "cost", "schedule.toml")

# (relative path, builder method) for each generated file.
TARGETS = [
  ["impl/rust/src/costs.rs", :rust_file],
  ["impl/go/costs.go",       :go_file],
  ["impl/ts/src/costs.ts",   :ts_file],
].freeze

def fail!(msg)
  warn "FAIL: #{msg}"
  exit 1
end

# --- shared field access -----------------------------------------------------

def scalar_limit = TomlRB.load_file(SCHEDULE).fetch("limits").fetch("default_scalar_bytes")

# The logical query-memory size schedule (spec/design/memory.md §3).
def mem(key) = TomlRB.load_file(SCHEDULE).fetch("memory").fetch(key)

def units
  schedule = TomlRB.load_file(SCHEDULE)
  us = schedule["unit"] || []
  fail!("#{SCHEDULE}: no [[unit]] entries") if us.empty?
  us
end

# snake_case id -> PascalCase (Go) / camelCase (TS). Rust keeps the snake_case id.
def pascal(id) = id.split("_").map(&:capitalize).join
def camel(id)
  p = pascal(id)
  p[0].downcase + p[1..]
end

# --- Rust --------------------------------------------------------------------

def rust_file(us)
  fields = us.map { |u| "    pub #{u['id']}: i64," }.join("\n")
  values = us.map { |u| "    #{u['id']}: #{u['weight']}," }.join("\n")
  <<~RS
    // @generated by scripts/gen_costs.rb from spec/cost/schedule.toml — DO NOT EDIT.
    //
    // Cost unit schedule (CLAUDE.md §5, §13: the codegen "middle path"). DATA only — the
    // accrual sites that CONSUME these weights (executor / evaluator / storage reads) are
    // hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
    // `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/cost.md.

    pub const DEFAULT_SCALAR_BYTES: i64 = #{scalar_limit};

    /// Logical query-memory size schedule (spec/design/memory.md §3).
    pub const MEMORY_ROW: i64 = #{mem('row')};
    pub const MEMORY_VALUE: i64 = #{mem('value')};
    pub const MEMORY_ARRAY_DIM: i64 = #{mem('array_dim')};
    pub const MEMORY_DECIMAL_GROUP: i64 = #{mem('decimal_group')};

    /// The deterministic cost-unit weights, mirroring spec/cost/schedule.toml.
    pub struct CostSchedule {
    #{fields}
    }

    /// The canonical cost schedule — weights accrued per unit during query execution.
    pub const COSTS: CostSchedule = CostSchedule {
    #{values}
    };
  RS
end

# --- Go ----------------------------------------------------------------------

def go_file(us)
  names = us.map { |u| pascal(u["id"]) }
  field_w = names.map(&:length).max
  fields = names.map { |n| "\t#{n}#{' ' * (field_w - n.length + 1)}int64" }.join("\n")
  key_w = names.map { |n| n.length + 1 }.max # name + ":"
  values = us.each_with_index.map do |u, i|
    key = "#{names[i]}:"
    "\t#{key}#{' ' * (key_w - key.length + 1)}#{u['weight']},"
  end.join("\n")
  <<~GO
    // Code generated by scripts/gen_costs.rb from spec/cost/schedule.toml. DO NOT EDIT.
    //
    // Cost unit schedule (CLAUDE.md §5, §13: the codegen "middle path"). DATA only — the
    // accrual sites that CONSUME these weights (executor / evaluator / storage reads) are
    // hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
    // `rake verify` fails if this file is stale. Reasoning: ../../spec/design/cost.md.

    package jed

    const defaultScalarBytes int64 = #{scalar_limit}

    // Logical query-memory size schedule (spec/design/memory.md §3).
    const (
    	memoryRow          int64 = #{mem('row')}
    	memoryValue        int64 = #{mem('value')}
    	memoryArrayDim     int64 = #{mem('array_dim')}
    	memoryDecimalGroup int64 = #{mem('decimal_group')}
    )

    // CostSchedule holds the deterministic cost-unit weights, mirroring spec/cost/schedule.toml.
    type costSchedule struct {
    #{fields}
    }

    // Costs is the canonical cost schedule — weights accrued per unit during query execution.
    var costs = costSchedule{
    #{values}
    }
  GO
end

# --- TypeScript --------------------------------------------------------------

def ts_file(us)
  fields = us.map { |u| "  #{camel(u['id'])}: bigint;" }.join("\n")
  values = us.map { |u| "  #{camel(u['id'])}: #{u['weight']}n," }.join("\n")
  <<~TS
    // @generated by scripts/gen_costs.rb from spec/cost/schedule.toml — DO NOT EDIT.
    //
    // Cost unit schedule (CLAUDE.md §5, §13: the codegen "middle path"). DATA only — the
    // accrual sites that CONSUME these weights (executor / evaluator / storage reads) are
    // hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
    // `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/cost.md.

    export const DEFAULT_SCALAR_BYTES = #{scalar_limit}n;

    // Logical query-memory size schedule (spec/design/memory.md §3). Plain numbers: the
    // query-memory account is a live byte counter well inside 2^53.
    export const MEMORY_ROW = #{mem('row')};
    export const MEMORY_VALUE = #{mem('value')};
    export const MEMORY_ARRAY_DIM = #{mem('array_dim')};
    export const MEMORY_DECIMAL_GROUP = #{mem('decimal_group')};

    // The deterministic cost-unit weights, mirroring spec/cost/schedule.toml. Weights are
    // bigint for i64 parity with the Rust/Go cores (a number is f64 — CLAUDE.md §8).
    export interface CostSchedule {
    #{fields}
    }

    // The canonical cost schedule — weights accrued per unit during query execution.
    export const COSTS: CostSchedule = {
    #{values}
    };
  TS
end

# --- driver ------------------------------------------------------------------

def main
  check = ARGV.include?("--check")
  us = units
  stale = []

  TARGETS.each do |rel, builder|
    path = File.join(REPO, rel)
    content = send(builder, us)
    if check
      current = File.exist?(path) ? File.read(path) : nil
      stale << rel unless current == content
    else
      File.write(path, content)
      puts "wrote #{rel}"
    end
  end

  if check
    unless stale.empty?
      stale.each { |rel| warn "STALE: #{rel} — run 'rake codegen'" }
      exit 1
    end
    puts "OK: #{TARGETS.length} generated files current (#{us.length} cost units)"
  end
end

main
