#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate the mechanical half of the Path-B estimator contract: exact rational constants,
# access-method classifications, access ranks, and schedule-order unit ids/weights. Candidate
# traversal, selectivity folding, cost propagation, and selection remain hand-written per core.

require "bundler/setup"
require "open3"
require "toml-rb"

REPO = File.expand_path("..", __dir__)
ESTIMATOR = File.join(REPO, "spec", "cost", "estimator.toml")
SCHEDULE = File.join(REPO, "spec", "cost", "schedule.toml")
TARGETS = [
  ["impl/rust/src/estimator_constants.rs", :rust_file],
  ["impl/go/estimator_constants.go", :go_file],
  ["impl/ts/src/estimator_constants.ts", :ts_file],
].freeze

def pascal(id) = id.split("_").map(&:capitalize).join
def upper(id) = id.upcase

def inputs
  [TomlRB.load_file(ESTIMATOR), TomlRB.load_file(SCHEDULE).fetch("unit")]
end

def rust_file(data, units)
  fractions = data.fetch("selectivity").map do |s|
    <<~RS.chomp
      pub const SELECTIVITY_#{upper(s.fetch('id'))}: EstimatorFraction = EstimatorFraction {
          numerator: #{s.fetch('numerator')},
          denominator: #{s.fetch('denominator')},
      };
    RS
  end.join("\n")
  indices = units.each_with_index.map { |u, i| "pub const UNIT_#{upper(u.fetch('id'))}: usize = #{i};" }.join("\n")
  ids = units.map { |u| %Q[    "#{u.fetch('id')}",] }.join("\n")
  weights = units.map { |u| "    #{u.fetch('weight')}," }.join("\n")
  access = data.fetch("tie_break").fetch("access_path").map { |v| %Q[    "#{v}",] }.join("\n")
  methods = data.fetch("access_method").map do |k, v|
    %Q[pub const ACCESS_#{upper(k)}: &str = "#{v}";]
  end.join("\n")
  <<~RS
    // @generated by scripts/gen_estimator.rb from spec/cost/{estimator,schedule}.toml — DO NOT EDIT.
    // Mechanical constants only; estimator control flow remains hand-written in every core.

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct EstimatorFraction {
        pub numerator: i64,
        pub denominator: i64,
    }

    pub const MAX_ESTIMATE: i64 = #{data.fetch('max_estimate')};
    pub const DEFAULT_DISTINCT_VALUES: i64 = #{data.fetch('default_distinct_values')};
    pub const DEFAULT_SRF_ROWS: i64 = #{data.fetch('default_srf_rows')};
    pub const DEFAULT_VARIABLE_KEY_BYTES: i64 = #{data.fetch('default_variable_key_bytes')};
    pub const JOIN_DP_LIMIT: usize = #{data.fetch('join_dp_limit')};
    pub const STATISTICS_TARGET: usize = #{data.fetch('statistics_target')};
    pub const STATISTICS_SAMPLE_ROWS: usize = #{data.fetch('statistics_sample_rows')};
    pub const STATISTICS_KMV_HASHES: usize = #{data.fetch('statistics_kmv_hashes')};
    pub const STATISTICS_MCV_ENTRIES: usize = #{data.fetch('statistics_mcv_entries')};
    pub const STATISTICS_HISTOGRAM_BOUNDS: usize = #{data.fetch('statistics_histogram_bounds')};
    pub const STATISTICS_MAX_VALUE_BYTES: usize = #{data.fetch('statistics_max_value_bytes')};
    pub const STATISTICS_NDV_SCALE_NUMERATOR: i64 = #{data.fetch('statistics_ndv_scale_numerator')};
    pub const STATISTICS_NDV_SCALE_DENOMINATOR: i64 = #{data.fetch('statistics_ndv_scale_denominator')};

    #{fractions}

    #{methods}

    pub const ACCESS_PATH_ORDER: [&str; #{data.fetch('tie_break').fetch('access_path').length}] = [
    #{access}
    ];

    pub const ESTIMATOR_UNIT_COUNT: usize = #{units.length};
    #{indices}
    pub const ESTIMATOR_UNIT_IDS: [&str; ESTIMATOR_UNIT_COUNT] = [
    #{ids}
    ];
    #[rustfmt::skip]
    pub const ESTIMATOR_UNIT_WEIGHTS: [i64; ESTIMATOR_UNIT_COUNT] = [
    #{weights}
    ];
  RS
end

def go_file(data, units)
  fractions = data.fetch("selectivity").map do |s|
    "var selectivity#{pascal(s.fetch('id'))} = estimatorFraction{numerator: #{s.fetch('numerator')}, denominator: #{s.fetch('denominator')}}"
  end.join("\n")
  index_names = units.map { |u| "estimatorUnit#{pascal(u.fetch('id'))}" }
  index_width = index_names.map(&:length).max
  indices = index_names.each_with_index.map { |name, i| "\t%-#{index_width}s = #{i}" % name }.join("\n")
  ids = units.map { |u| %Q[\t"#{u.fetch('id')}",] }.join("\n")
  weights = units.map { |u| "\t#{u.fetch('weight')}," }.join("\n")
  access = data.fetch("tie_break").fetch("access_path").map { |v| %Q[\t"#{v}",] }.join("\n")
  methods = data.fetch("access_method").map do |k, v|
    %Q[const access#{pascal(k)} = "#{v}"]
  end.join("\n")
  source = <<~GO
    // Code generated by scripts/gen_estimator.rb from spec/cost/{estimator,schedule}.toml. DO NOT EDIT.
    // Mechanical constants only; estimator control flow remains hand-written in every core.

    package jed

    type estimatorFraction struct {
    \tnumerator   int64
    \tdenominator int64
    }

    const (
    \tmaxEstimate             int64 = #{data.fetch('max_estimate')}
    \tdefaultDistinctValues   int64 = #{data.fetch('default_distinct_values')}
    \tdefaultSRFRows          int64 = #{data.fetch('default_srf_rows')}
    \tdefaultVariableKeyBytes int64 = #{data.fetch('default_variable_key_bytes')}
    \tjoinDPLimit                   = #{data.fetch('join_dp_limit')}
    \tstatisticsTarget              = #{data.fetch('statistics_target')}
    \tstatisticsSampleRows          = #{data.fetch('statistics_sample_rows')}
    \tstatisticsKMVHashes           = #{data.fetch('statistics_kmv_hashes')}
    \tstatisticsMCVEntries          = #{data.fetch('statistics_mcv_entries')}
    \tstatisticsHistogramBounds     = #{data.fetch('statistics_histogram_bounds')}
    \tstatisticsMaxValueBytes       = #{data.fetch('statistics_max_value_bytes')}
    \tstatisticsNDVScaleNumerator   = #{data.fetch('statistics_ndv_scale_numerator')}
    \tstatisticsNDVScaleDenominator = #{data.fetch('statistics_ndv_scale_denominator')}
    )

    #{fractions}

    #{methods}

    var estimatorAccessPathOrder = [...]string{
    #{access}
    }

    const estimatorUnitCount = #{units.length}
    const (
    #{indices}
    )

    var estimatorUnitIDs = [...]string{
    #{ids}
    }
    var estimatorUnitWeights = [...]int64{
    #{weights}
    }
  GO
  formatted, error, status = Open3.capture3("gofumpt", stdin_data: source)
  raise "gofumpt generated estimator constants: #{error}" unless status.success?

  formatted
end

def ts_file(data, units)
  fractions = data.fetch("selectivity").map do |s|
    "export const SELECTIVITY_#{upper(s.fetch('id'))}: EstimatorFraction = { numerator: #{s.fetch('numerator')}n, denominator: #{s.fetch('denominator')}n };"
  end.join("\n")
  indices = units.each_with_index.map { |u, i| "export const UNIT_#{upper(u.fetch('id'))} = #{i};" }.join("\n")
  ids = units.map { |u| %Q[  "#{u.fetch('id')}",] }.join("\n")
  weights = units.map { |u| "  #{u.fetch('weight')}n," }.join("\n")
  access = data.fetch("tie_break").fetch("access_path").map { |v| %Q[  "#{v}",] }.join("\n")
  methods = data.fetch("access_method").map do |k, v|
    %Q[export const ACCESS_#{upper(k)} = "#{v}";]
  end.join("\n")
  <<~TS
    // @generated by scripts/gen_estimator.rb from spec/cost/{estimator,schedule}.toml — DO NOT EDIT.
    // Mechanical constants only; estimator control flow remains hand-written in every core.

    export type EstimatorFraction = { numerator: bigint; denominator: bigint };

    export const MAX_ESTIMATE = #{data.fetch('max_estimate')}n;
    export const DEFAULT_DISTINCT_VALUES = #{data.fetch('default_distinct_values')}n;
    export const DEFAULT_SRF_ROWS = #{data.fetch('default_srf_rows')}n;
    export const DEFAULT_VARIABLE_KEY_BYTES = #{data.fetch('default_variable_key_bytes')}n;
    export const JOIN_DP_LIMIT = #{data.fetch('join_dp_limit')};
    export const STATISTICS_TARGET = #{data.fetch('statistics_target')};
    export const STATISTICS_SAMPLE_ROWS = #{data.fetch('statistics_sample_rows')};
    export const STATISTICS_KMV_HASHES = #{data.fetch('statistics_kmv_hashes')};
    export const STATISTICS_MCV_ENTRIES = #{data.fetch('statistics_mcv_entries')};
    export const STATISTICS_HISTOGRAM_BOUNDS = #{data.fetch('statistics_histogram_bounds')};
    export const STATISTICS_MAX_VALUE_BYTES = #{data.fetch('statistics_max_value_bytes')};
    export const STATISTICS_NDV_SCALE_NUMERATOR = #{data.fetch('statistics_ndv_scale_numerator')}n;
    export const STATISTICS_NDV_SCALE_DENOMINATOR = #{data.fetch('statistics_ndv_scale_denominator')}n;

    #{fractions}

    #{methods}

    export const ESTIMATOR_ACCESS_PATH_ORDER = [
    #{access}
    ] as const;

    export const ESTIMATOR_UNIT_COUNT = #{units.length};
    #{indices}
    export const ESTIMATOR_UNIT_IDS = [
    #{ids}
    ] as const;
    export const ESTIMATOR_UNIT_WEIGHTS = [
    #{weights}
    ] as const;
  TS
end

def main
  check = ARGV.include?("--check")
  data, units = inputs
  stale = []
  TARGETS.each do |rel, builder|
    path = File.join(REPO, rel)
    content = send(builder, data, units)
    if check
      stale << rel unless File.exist?(path) && File.read(path) == content
    else
      File.write(path, content)
      puts "wrote #{rel}"
    end
  end
  unless stale.empty?
    stale.each { |rel| warn "STALE: #{rel} — run 'rake codegen'" }
    exit 1
  end
  puts "OK: #{TARGETS.length} generated estimator files current" if check
end

main
