# frozen_string_literal: true

# scripts/norec_gen.rb — SQLancer-style metamorphic test generator (CLAUDE.md §7, TODO.md
# Phase 8: "SQLancer-style metamorphic / generative testing"). This is the NoREC oracle
# (Non-optimizing Reference Engine Construction) specialized to jed's query pushdown.
#
# The relation: an OPTIMIZED query and a semantically-equivalent NON-optimizable rewrite must
# return identical rows. jed's planner pushes a predicate to a B-tree seek/range ONLY when the
# primary key appears as a BARE column (executor `detect_pk_bound`: it matches `RExpr::Column`,
# nothing else). So `id = K` is pushed down (point-lookup seek) while `id + 0 = K` — an
# arithmetic BinaryOp — is NOT, and full-scans. The two paths execute completely different code
# yet must agree. A pushdown bug shows up as the optimized query disagreeing with the scan.
#
# Why this is more than the differential cores (Rust/Go/TS run every test): those catch the
# cores DISAGREEING, but are blind to a bug ALL of them share. This metamorphic relation is an
# independent oracle — it can fail even when all three cores agree. And we still run it on every
# core, so it is metamorphic AND differential at once (the discussion's two axes composed).
#
# Determinism (CLAUDE.md §10): generation is SEEDED, so a discovered failure reduces to this
# exact deterministic .test, which then joins the corpus. The fuzzer is dev-time discovery; the
# emitted .test is the reproducible artifact. Expected rows are known BY CONSTRUCTION from the
# generated data — no oracle (PG or otherwise) is consulted to produce them.
#
#   ruby scripts/norec_gen.rb [seed]        # generate, run on the cores, report, clean up
#   ruby scripts/norec_gen.rb 7 --keep PATH # write the .test to PATH and leave it

require "open3"
require "fileutils"

REQUIRES = %w[
  ddl.create_table ddl.primary_key dml.insert dml.insert_multi_row query.select query.where_eq
  query.comparison_order query.point_lookup query.order_by query.logical_connectives
  expr.arithmetic expr.between expr.comparison_value types.int32
].freeze

# Each core ships a conformance binary that WALKS spec/conformance/suites and prints one
# `PASS|FAIL|SKIP <relpath>` line per file (identical format across cores). So we generate every
# seed's .test into the tree, then run each core ONCE — 3 harness runs total, not 3×N.
CORES = {
  "rust" => { dir: %w[impl rust], cmd: %w[cargo run --quiet --bin conformance] },
  "go" => { dir: %w[impl go], cmd: %w[go run ./cmd/conformance] },
  "ts" => { dir: %w[impl ts], cmd: %w[npm run --silent conformance] },
}.freeze

PAIRS_PER_SEED = 5 # keep in sync with generate(): 2 present + 1 absent + 2 ranges

# A metamorphic pair: the same predicate expressed pushdown-able and not. Both assert `exp`.
def pair(out, title, opt_pred, scan_pred, exp)
  out << "# #{title}"
  [["pushdown (bare pk -> B-tree seek)", opt_pred],
   ["full scan (id+0 defeats pushdown) — MUST match", scan_pred]].each do |note, pred|
    out << "# #{note}"
    out << "query II nosort"
    out << "SELECT id, v FROM t WHERE #{pred} ORDER BY id"
    out << "----"
    out.concat(exp)
    out << ""
  end
end

def generate(seed)
  rng = Random.new(seed)
  ids = (1..40).to_a.sample(12, random: rng).sort
  rows = ids.map { |id| [id, rng.rand(-100..100)] }
  block = ->(pred) { rows.select { |id, v| pred.call(id, v) }.flat_map { |id, v| [id.to_s, v.to_s] } }

  present = ids.sample(2, random: rng)
  absent = ((1..40).to_a - ids).sample(random: rng)
  lo, hi = ids.sample(2, random: rng).sort
  empty_lo = 41
  empty_hi = 50

  out = []
  out << "# Metamorphic NoREC pushdown test — GENERATED by scripts/norec_gen.rb (seed #{seed})."
  out << "# An optimized query and a non-optimizable rewrite must return identical rows, on every"
  out << "# core. Expected rows are known by construction; no oracle is consulted. See the script."
  out << "# requires: #{REQUIRES.join(', ')}"
  out << ""
  out << "statement ok"
  out << "CREATE TABLE t (id int32 PRIMARY KEY, v int32)"
  out << ""
  out << "statement ok"
  out << "INSERT INTO t VALUES #{rows.map { |id, v| "(#{id}, #{v})" }.join(', ')}"
  out << ""

  present.each do |k|
    pair(out, "point lookup id = #{k} (present)",
         "id = #{k}", "id + 0 = #{k}", block.call(->(id, _v) { id == k }))
  end
  pair(out, "point lookup id = #{absent} (absent -> empty)",
       "id = #{absent}", "id + 0 = #{absent}", block.call(->(id, _v) { id == absent }))
  pair(out, "range #{lo}..#{hi}",
       "id BETWEEN #{lo} AND #{hi}", "id + 0 BETWEEN #{lo} AND #{hi}",
       block.call(->(id, _v) { id >= lo && id <= hi }))
  pair(out, "range #{empty_lo}..#{empty_hi} (empty)",
       "id BETWEEN #{empty_lo} AND #{empty_hi}", "id + 0 BETWEEN #{empty_lo} AND #{empty_hi}",
       block.call(->(id, _v) { id >= empty_lo && id <= empty_hi }))

  out.join("\n") + "\n"
end

# Run one core's harness once; return {seed => "PASS"/"FAIL", ...} for our metamorphic files,
# plus the FAIL detail line per failing seed (for reporting).
def run_core(repo, core)
  out, = Open3.capture2e(*core[:cmd], chdir: File.join(repo, *core[:dir]))
  status = {}
  detail = {}
  out.each_line do |l|
    next unless (m = l.match(%r{^(PASS|FAIL|SKIP)\s+(metamorphic/_norec_seed(\d+)\.test)}))

    seed = m[3].to_i
    status[seed] = m[1]
    detail[seed] = l.strip if m[1] != "PASS"
  end
  [status, detail]
end

# --- argument parsing -------------------------------------------------------------------------
args = ARGV.dup
keep = !args.delete("--keep").nil?
sweep = (i = args.index("--sweep")) ? args[i + 1].to_i : nil
seeds_arg = (i = args.index("--seeds")) ? args[i + 1].split(",").map(&:to_i) : nil
cores_arg = (i = args.index("--cores")) ? args[i + 1].split(",") : nil
bare = args.find { |a| a =~ /\A\d+\z/ }

seeds = seeds_arg || (sweep ? (1..sweep).to_a : [bare ? bare.to_i : 1])
# A sweep is the full differential CI check (all three cores); a single seed defaults to the
# fast dev pair (Go + TS) unless cores are named explicitly.
cores = cores_arg || ((sweep || seeds_arg) ? CORES.keys : %w[go ts])
cores.each { |c| abort "unknown core #{c.inspect} (have: #{CORES.keys.join(', ')})" unless CORES[c] }

repo = File.expand_path("..", __dir__)
dir = File.join(repo, "spec/conformance/suites/metamorphic")

# --- generate every seed, run each core once, report a matrix -------------------------------
FileUtils.mkdir_p(dir)
seeds.each { |s| File.write(File.join(dir, "_norec_seed#{s}.test"), generate(s)) }
span = seeds.size == 1 ? "seed #{seeds.first}" : "#{seeds.size} seeds (#{seeds.first}..#{seeds.last})"
puts "NoREC metamorphic sweep — #{span}, #{PAIRS_PER_SEED} pairs each, cores: #{cores.join(', ')}"

failures = 0
begin
  cores.each do |name|
    status, detail = run_core(repo, CORES[name])
    missing = seeds.reject { |s| status.key?(s) }
    failed = seeds.select { |s| status[s] == "FAIL" }
    failures += failed.size + missing.size
    pass = seeds.size - failed.size - missing.size
    note = []
    note << "FAILED: #{failed.join(', ')}" unless failed.empty?
    note << "NOT RUN/SKIPPED: #{missing.join(', ')}" unless missing.empty?
    printf("  %-4s %2d/%-2d PASS%s\n", name, pass, seeds.size, note.empty? ? "" : "  — #{note.join('; ')}")
    failed.each { |s| puts "       #{detail[s]}" }
  end
ensure
  unless keep
    seeds.each { |s| FileUtils.rm_f(File.join(dir, "_norec_seed#{s}.test")) }
    Dir.rmdir(dir) if Dir.exist?(dir) && Dir.empty?(dir)
  end
end

checks = seeds.size * cores.size
if failures.zero?
  puts "\nsweep PASS — #{checks} checks (#{seeds.size} seeds × #{cores.size} cores), " \
       "#{seeds.size * PAIRS_PER_SEED} metamorphic pairs/core, all green."
  exit 0
else
  puts "\nsweep FAIL — #{failures}/#{checks} checks failed."
  exit 1
end
