#!/usr/bin/env ruby
# frozen_string_literal: true

# vendor_collations.rb — distribute the committed `.coll` artifacts (the collation tables the
# build-time pipeline produced, spec/design/collation.md §9) into each core that needs an in-tree
# copy to embed. In the reference-only model every core EMBEDS the identical `.coll` bytes
# (cross-core byte-identity, §9/§10) and reads them at startup; the database file only references a
# collation by name.
#
# Per-core delivery differs because the embed mechanisms do:
#   * Rust   — `include_bytes!` reads spec/ directly (accepts `../`), so it needs NO copy and is
#              always in sync with the source. Not handled here.
#   * Go      — `//go:embed` cannot reach outside its package tree → raw `.coll` copies in
#              impl/go/collationdata/.
#   * TS      — the core also runs in the browser (OPFS host) and must stay free of `node:fs`, so the
#              bytes are inlined base64 in a generated `.ts` module (no file read at runtime).
#
# `--check` is the CI drift gate (wired into `rake verify`). Source of truth: spec/collation/fixtures.
#
# Usage:
#   ruby scripts/vendor_collations.rb            # (re)write each core's embed payload
#   ruby scripts/vendor_collations.rb --check    # verify payloads match the source (exit 1 on drift)

require "fileutils"
require "digest"

# Strict, single-line base64 (RFC 4648) via core Array#pack — no `base64` gem (dropped from Ruby's
# default gems in 3.4) and so no Gemfile entry. Equivalent to Base64.strict_encode64.
def b64(bytes) = [bytes].pack("m0")

ROOT = File.expand_path("..", __dir__)
SRC  = File.join(ROOT, "spec/collation/fixtures")

# The real version-pinned vendored set (collation.md §9/§14): `unicode` = the CLDR-tailored DUCET root
# (UCA/UCD 17.0.0, spec/collation/17.0.0), `es` = root + the Spanish ñ tailoring. The embedder-chosen
# footprint tiers (§13) and the broader tailoring set (sv/da/de — needing the deferred LDML
# `[before]`/expansion features) are later slices. The `dev-*` fixtures are NOT vendored — they only
# drive the cross-core compiler/sort-key vectors. `stem => file` — the stem is the registry key the
# cores parse back to the artifact's own embedded name.
COLLATIONS = { "unicode" => "unicode.coll", "es" => "es.coll" }.freeze

GO_DIR = "impl/go/collationdata"          # raw `.coll` copies (//go:embed)
TS_MODULE = "impl/ts/src/collationdata/vendored.ts" # generated base64 module (browser-safe)

def src_bytes(file)
  path = File.join(SRC, file)
  abort "vendor_collations: missing source #{path}" unless File.exist?(path)
  File.binread(path)
end

# The TS module the build-time pipeline emits — the `.coll` bytes inlined as base64 so the TS core
# stays browser-safe (no node:fs). Keyed by fixture stem; collation.ts decodes + OpenCollations.
def ts_module
  lines = []
  lines << "// Code generated by scripts/vendor_collations.rb. DO NOT EDIT."
  lines << "// The collation tables VENDORED into the TS core (spec/design/collation.md §9): the"
  lines << "// .coll artifacts inlined as base64 so the core stays browser-safe (no node:fs). Synced"
  lines << "// from spec/collation/fixtures; `rake verify` checks drift."
  lines << ""
  lines << "export const VENDORED_COLL: Record<string, string> = {"
  COLLATIONS.each { |stem, file| lines << "  #{stem.inspect}: #{b64(src_bytes(file)).inspect}," }
  lines << "};"
  lines.join("\n") + "\n"
end

check = ARGV.include?("--check")
drift = []

# Go — raw `.coll` copies.
COLLATIONS.each_value do |file|
  dst = File.join(ROOT, GO_DIR, file)
  if check
    drift << File.join(GO_DIR, file) unless File.exist?(dst) && File.binread(dst) == src_bytes(file)
  else
    FileUtils.mkdir_p(File.join(ROOT, GO_DIR))
    File.binwrite(dst, src_bytes(file))
  end
end

# TS — generated base64 module.
ts_dst = File.join(ROOT, TS_MODULE)
if check
  drift << TS_MODULE unless File.exist?(ts_dst) && File.read(ts_dst) == ts_module
else
  FileUtils.mkdir_p(File.dirname(ts_dst))
  File.write(ts_dst, ts_module)
end

if check
  unless drift.empty?
    warn "vendored collations out of sync with spec/collation/fixtures:"
    drift.each { |f| warn "  #{f}" }
    warn "run: ruby scripts/vendor_collations.rb"
    exit 1
  end
  puts "vendored collations in sync (Go raw + TS module, #{COLLATIONS.size} collations)"
else
  puts "vendored #{COLLATIONS.size} collation(s): #{GO_DIR}/*.coll + #{TS_MODULE}"
end
