//! The catalog: table and column definitions (CLAUDE.md §4 strict static types).

use std::collections::HashMap;

use crate::ast::Expr;
use crate::types::{DecimalTypmod, ScalarType, Type};
use crate::value::Value;

/// A column definition: name, declared type, nullability, primary-key flag, default.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Column {
    pub name: String,
    /// The column's declared type — a built-in scalar or a user-defined composite
    /// (spec/design/composite.md). The open `Type` wrapper (CLAUDE.md §4): scalar-only call sites
    /// read `ty.scalar()`; the value codec / resolver branch on `Type::Composite`.
    pub ty: Type,
    /// The `numeric(p,s)` type modifier for a decimal column, or `None` for a non-decimal
    /// column OR an unconstrained `numeric` (spec/design/decimal.md §2). A constrained
    /// decimal column coerces stored values to this precision/scale.
    pub decimal: Option<DecimalTypmod>,
    /// The `varchar(n)` max-length type modifier for a `text` column, or `None` for a
    /// non-text column OR an unbounded `text` (spec/design/types.md §15). `n` is counted in
    /// code points; an over-length assignment traps `22001`. Persisted as a `u32` in the
    /// column entry's typmod slot when `type_code == 4` (format_version 22).
    pub varchar_len: Option<u32>,
    pub primary_key: bool,
    /// A PRIMARY KEY column is implicitly NOT NULL.
    pub not_null: bool,
    /// The column's **constant** `DEFAULT` value, pre-evaluated and type-coerced at CREATE
    /// TABLE, or `None` if it has no default or an *expression* default (`default_expr`).
    /// `Some(Value::Null)` is an explicit `DEFAULT NULL`. Applied for an omitted column or a
    /// `DEFAULT` keyword at INSERT (spec/design/constraints.md §2).
    pub default: Option<Value>,
    /// The column's **expression** `DEFAULT` (a non-constant default like `uuidv7()` or
    /// `1 + 1`), or `None` if it has no default or a *constant* default (`default`). Mutually
    /// exclusive with `default`. Stored as expression text (re-rendered verbatim at every
    /// commit, like a `CHECK` — spec/fileformat/format.md) plus the parsed expression the write
    /// paths resolve and evaluate per row (spec/design/constraints.md §2).
    pub default_expr: Option<DefaultExpr>,
    /// Whether the column is a `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY` column, and which
    /// kind (spec/design/sequences.md §13). `None` is a non-identity column. An identity column
    /// also carries `not_null` + a `default_expr` (`nextval` of its owned sequence); the kind gates
    /// whether an explicit INSERT/UPDATE value is accepted (`428C9`). Persisted as two column flag
    /// bits (format_version 15: bit 4 `is_identity`, bit 5 `identity_always`).
    pub identity: Option<IdentityKind>,
    /// The column's **effective** collation — `None` is `C` (byte / code-point order, the unchanged
    /// fast path), `Some(name)` a loaded non-`C` collation (spec/design/collation.md §1). Frozen at
    /// CREATE TABLE: an explicit `COLLATE "name"` clause, else the per-database default collation as
    /// of creation (PG-matching — a column's collation is fixed at creation, never re-derived). Only
    /// a `text` column may carry one. A column reference's *implicit* collation in the derivation
    /// (`42P22`); persisted as column flag bit 6 + a trailing name (format_version 17).
    pub collation: Option<String>,
}

/// The kind of an IDENTITY column (spec/design/sequences.md §13). `Always` (`GENERATED ALWAYS`)
/// rejects an explicit INSERT/UPDATE value (`428C9`) unless overridden; `ByDefault` (`GENERATED BY
/// DEFAULT`) accepts one, behaving like `serial`. Persisted as flag bit 5 `identity_always`
/// (set ⇒ `Always`, clear ⇒ `ByDefault`), meaningful only with bit 4 `is_identity`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum IdentityKind {
    Always,
    ByDefault,
}

/// A column's **expression** `DEFAULT` (spec/design/constraints.md §2): its persisted
/// expression text — written back verbatim at every commit so the catalog bytes are stable
/// (spec/fileformat/format.md "Check-expression text") — and the parsed expression the write
/// paths resolve (against an empty scope, no columns) and evaluate per inserted row. Modeled on
/// `CheckConstraint`.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct DefaultExpr {
    pub expr_text: String,
    pub expr: Expr,
}

/// One `CHECK` constraint: its (resolved, unique-per-table) name, its persisted expression
/// text — written back verbatim at every commit so the catalog bytes are stable
/// (spec/fileformat/format.md "Check-expression text") — and the parsed expression the
/// write paths resolve and evaluate per candidate row (spec/design/constraints.md §4).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct CheckConstraint {
    pub name: String,
    pub expr_text: String,
    pub expr: Expr,
}

/// The KIND of a secondary index (spec/design/gin.md): an ordered B-tree (the default) or a
/// GIN inverted index. Persisted as the v12 per-index `index_kind` byte
/// (spec/fileformat/format.md).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum IndexKind {
    /// An ordered B-tree over the key-column tuple — the original (and default) index.
    Btree = 0,
    /// A GIN inverted index: one entry per term extracted from the (array) column
    /// (spec/design/gin.md §4). This slice: a single integer-element array column (`array_ops`).
    Gin = 1,
    /// A GiST index — a bounding-predicate R-tree (spec/design/gist.md). GX1: the `range_ops`
    /// opclass over a single `range` column. The in-memory store holds one leaf-key entry per row
    /// (`encode_range_body(bound) ‖ storage_key`, gist.rs); the on-disk form is the persisted
    /// R-tree (page types 5/6, `format_version` 20 — GX1b). Never `unique`.
    Gist = 2,
}

/// One index key element (spec/design/indexes.md §1): a bare column (by ordinal into the
/// table's columns) or an **expression** over the table's columns (`lower(email)`), carrying
/// its persisted canonical text and the re-parsed (unresolved) AST — the write/plan paths
/// re-resolve it against the table per statement, exactly as a CHECK is re-resolved. Only a
/// B-tree index may carry an expression element (GIN/GiST are single column, this slice).
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum IndexKey {
    Column(usize),
    Expr(IndexKeyExpr),
}

/// An index expression key's persisted text + parsed AST (modeled on `CheckConstraint`).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct IndexKeyExpr {
    pub expr_text: String,
    pub expr: Expr,
}

impl IndexKey {
    /// The column ordinal if this is a plain column key, else `None` (an expression key).
    pub fn as_column(&self) -> Option<usize> {
        match self {
            IndexKey::Column(c) => Some(*c),
            IndexKey::Expr(_) => None,
        }
    }
}

/// One secondary index of a table (spec/design/indexes.md): its (relation-namespace) name
/// and its key elements in index-key order (columns and/or expressions, duplicates allowed —
/// PG). The index's B-tree lives in the snapshot's index-store map, keyed by the lowercased
/// name. A `unique` index enforces uniqueness over its key tuple (NULLS DISTINCT —
/// spec/design/indexes.md §8); it is what backs a `UNIQUE` constraint
/// (spec/design/constraints.md §5). `kind` selects ordered-B-tree vs GIN
/// (spec/design/gin.md); a GIN index is never `unique`.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct IndexDef {
    pub name: String,
    pub keys: Vec<IndexKey>,
    pub unique: bool,
    pub kind: IndexKind,
    /// A **partial** index's `WHERE predicate` (spec/design/indexes.md §9): only rows whose
    /// predicate is TRUE are indexed / constrained. `None` for an ordinary (full) index. Carries
    /// the persisted canonical text + the re-parsed (unresolved) AST — re-resolved against the
    /// table per statement, like an expression key ([`IndexKeyExpr`]). Partial indexes are B-tree
    /// only (a GIN/GiST index never carries one).
    pub predicate: Option<IndexKeyExpr>,
}

impl IndexDef {
    /// Whether every key element is a plain column (no expression key) — the common case, and
    /// the GIN/GiST invariant. Lets column-only code paths fast-check.
    pub fn all_columns(&self) -> bool {
        self.keys.iter().all(|k| matches!(k, IndexKey::Column(_)))
    }

    /// The key elements' column ordinals if every element is a plain column, else `None` (the
    /// index has at least one expression key). The many column-only consumers — the GIN/GiST
    /// entry builders, FK-target matching, introspection — use this; an expression key makes the
    /// index ineligible for those (an FK cannot target an expression index, etc.).
    pub fn column_ordinals(&self) -> Option<Vec<usize>> {
        self.keys.iter().map(IndexKey::as_column).collect()
    }

    /// The column ordinal of the first key element, assuming a single-column index — used by the
    /// GIN/GiST paths, which are always single-column plain-column indexes (this slice).
    pub fn first_column(&self) -> usize {
        self.keys[0]
            .as_column()
            .expect("GIN/GiST index key is a plain column")
    }
}

/// The persisted referential action for a foreign key's `ON DELETE` / `ON UPDATE`
/// (spec/design/constraints.md §6.6). Only `NoAction` (the default) and `Restrict` are
/// supported — they are identical in jed (no deferrable constraints). The write-actions
/// (CASCADE / SET NULL / SET DEFAULT) are rejected `0A000` at CREATE TABLE, so never reach here;
/// the on-disk encoding reserves codes for them (format.md).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FkAction {
    NoAction,
    Restrict,
}

/// One resolved `FOREIGN KEY` constraint of a table (spec/design/constraints.md §6): its
/// (per-table constraint-namespace) name, the referencing column ordinals into **this** table in
/// list order, the referenced (parent) table name, the referenced column ordinals into the
/// **parent** in list order (same length as `columns`), and the referential actions. An FK owns no
/// B-tree; enforcement probes the parent's PK store or a unique index (§6.4). Held in ascending
/// lowercased-name order on the table (the catalog's on-disk order and the child-side evaluation
/// order — §6.9).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct ForeignKeyConstraint {
    pub name: String,
    pub columns: Vec<usize>,
    pub ref_table: String,
    pub ref_columns: Vec<usize>,
    pub on_delete: FkAction,
    pub on_update: FkAction,
}

/// One element's operator in an `EXCLUDE` constraint (spec/design/gist.md §7) — the `WITH` operator
/// of a `(column WITH op)` pair. `Overlaps` is `&&` (a range column, `range_ops`); `Equal` is `=` (a
/// fixed-width keyable scalar, the in-core `btree_gist`). Both are **symmetric**, the property an
/// exclusion operator must have. Persisted as the v21 per-element strategy byte (format.md).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ExclusionOp {
    /// `&&` — range overlap.
    Overlaps,
    /// `=` — scalar equality.
    Equal,
}

/// One `(column, operator)` element of an `EXCLUDE` constraint — a member column ordinal into the
/// owning table and its `WITH` operator. The element order matches the backing GiST index's column
/// order (spec/design/gist.md §7/§8).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct ExclusionElement {
    pub column: usize,
    pub op: ExclusionOp,
}

/// One `EXCLUDE` constraint (spec/design/gist.md §7): its (relation-namespace) name, the backing
/// **GiST** index that enforces it (by name — the constraint *is* its index, the UNIQUE-is-its-index
/// model generalized from a single implicit `=` to an explicit operator list), and the
/// `(column, operator)` element vector the conjunction probe needs. Held in ascending
/// lowercased-name order on the table (the catalog's on-disk order). The NULL rule (§7) is enforced
/// at probe time: a row with a NULL in any excluded column never conflicts.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct ExclusionConstraint {
    pub name: String,
    /// The backing GiST index's name (equal to `name` for a GX3 constraint — it owns the index).
    pub index: String,
    pub elements: Vec<ExclusionElement>,
}

/// A user-defined **composite (row) type** (spec/design/composite.md): a named, ordered list of
/// typed fields, living in the database's type catalog (a database-level object, not per-table).
/// Created by `CREATE TYPE name AS (field type, …)`, referenced by name from a column's `Type`.
/// Recursive — a field's `ty` may itself be `Type::Composite` (a nested composite, persisted
/// by name; spec/fileformat/format.md *Composite-type entry*).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct CompositeType {
    /// The type name (original case — round-trips what the user typed); looked up case-insensitively.
    pub name: String,
    /// The fields in declaration order (≥ 1).
    pub fields: Vec<CompositeField>,
}

/// One field of a composite type: its name, type, and declared nullability.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct CompositeField {
    pub name: String,
    pub ty: Type,
    /// The decimal `numeric(p,s)` typmod when `ty` is `decimal`, else `None` (mirrors `Column`).
    pub decimal: Option<DecimalTypmod>,
    /// The `varchar(n)` max-length typmod when `ty` is `text`, else `None` (mirrors `Column`,
    /// spec/design/types.md §15).
    pub varchar_len: Option<u32>,
    /// Whether the field was declared `NOT NULL`.
    pub not_null: bool,
}

/// A **sequence** (spec/design/sequences.md): a named, persisted, monotonic i64 generator —
/// the third database-level catalog-object kind (after tables and composite types). The
/// definition fields (`increment`/`min_value`/`max_value`/`start`/`cache`/`cycle`) are immutable;
/// `last_value` + `is_called` are the mutable counter state a `nextval` advances. The whole struct
/// lives in the snapshot catalog, so the counter is transactional by construction (sequences.md §5).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct SequenceDef {
    /// The sequence name (original case; looked up case-insensitively).
    pub name: String,
    /// The step per `nextval` (non-zero). Positive = ascending, negative = descending.
    pub increment: i64,
    /// The inclusive lower bound.
    pub min_value: i64,
    /// The inclusive upper bound.
    pub max_value: i64,
    /// The first value `nextval` returns (on a fresh sequence, `last_value == start`).
    pub start: i64,
    /// The PostgreSQL `CACHE` size — stored for fidelity but behaves as 1 (sequences.md §7).
    pub cache: i64,
    /// Whether `nextval` wraps at a bound (`CYCLE`) instead of raising `2200H`.
    pub cycle: bool,
    /// The mutable counter: the most recent value produced (or `start` before the first call).
    pub last_value: i64,
    /// Whether `nextval` has been called: `false` ⇒ the next call returns `last_value` (= `start`)
    /// without incrementing; `true` ⇒ it adds `increment` (PostgreSQL's `is_called`).
    pub is_called: bool,
    /// The `OWNED BY` link for a sequence created by a `serial` column (spec/design/sequences.md
    /// §12) — `Some` records the owning table + column ordinal, `None` for a plain `CREATE
    /// SEQUENCE`. Persisted (format_version 13, the `has_owner` flag bit): it drives `DROP TABLE`
    /// auto-drop and the `DROP SEQUENCE` 2BP01. A plain `DEFAULT nextval('s')` creates **no** owner
    /// link (PG — sequences.md §10 decision 4).
    pub owned_by: Option<SeqOwner>,
}

/// The `OWNED BY` reference of a `serial`-created sequence (spec/design/sequences.md §12): the
/// owning table (original case) and the owning column's 0-based ordinal. Persisted on the sequence
/// catalog entry (format.md *Sequence entry*, v13).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct SeqOwner {
    pub table: String,
    pub column: u16,
}

/// A sequence's value data type (`AS smallint | integer | bigint`, spec/design/sequences.md §14).
/// Its **only** effect is on the bounds: it sets the default + validated MINVALUE/MAXVALUE. The
/// counter is always an `i64`, and the type is not persisted (it is reducible to the bounds), so this
/// is a parse/build-time concept only.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum SeqDataType {
    SmallInt,
    Integer,
    BigInt,
}

impl SeqDataType {
    /// The inclusive value range `[T_min, T_max]` of the type (the natural `i16`/`i32`/`i64` range).
    pub fn range(self) -> (i64, i64) {
        match self {
            SeqDataType::SmallInt => (i16::MIN as i64, i16::MAX as i64),
            SeqDataType::Integer => (i32::MIN as i64, i32::MAX as i64),
            SeqDataType::BigInt => (i64::MIN, i64::MAX),
        }
    }

    /// The PostgreSQL type name used in error messages (`smallint` / `integer` / `bigint`).
    pub fn pg_name(self) -> &'static str {
        match self {
            SeqDataType::SmallInt => "smallint",
            SeqDataType::Integer => "integer",
            SeqDataType::BigInt => "bigint",
        }
    }

    /// The type defaults for an ascending (`increment > 0`) vs descending sequence, before any
    /// explicit MIN/MAX/START override (PostgreSQL `init_params`): ascending ⇒ `[1, T_max]`,
    /// start = MIN; descending ⇒ `[T_min, -1]`, start = MAX.
    pub fn default_bounds(self, increment: i64) -> (i64, i64) {
        let (lo, hi) = self.range();
        if increment < 0 { (lo, -1) } else { (1, hi) }
    }

    /// Resolve an `AS <name>` type to a sequence data type, or `None` if the name is not an integer
    /// type (caller raises `22023` "sequence type must be smallint, integer, or bigint").
    pub fn from_type_name(name: &str) -> Option<SeqDataType> {
        Self::for_scalar(ScalarType::from_name(name)?)
    }

    /// The sequence data type matching a column's integer scalar (`serial`/identity auto-wiring): an
    /// `i16`/`i32`/`i64` column maps to `smallint`/`integer`/`bigint`; any other scalar → `None`.
    pub fn for_scalar(s: ScalarType) -> Option<SeqDataType> {
        match s {
            ScalarType::Int16 => Some(SeqDataType::SmallInt),
            ScalarType::Int32 => Some(SeqDataType::Integer),
            ScalarType::Int64 => Some(SeqDataType::BigInt),
            _ => None,
        }
    }
}

/// A table definition.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Table {
    pub name: String,
    pub columns: Vec<Column>,
    /// The primary-key member column ordinals in **key order** (which may differ from
    /// declaration order — constraints.md §3; the v5 catalog persists this list). Empty =
    /// no primary key (synthetic rowid keys). The per-column `primary_key` flag is derived
    /// membership convenience; this list is the authority for order.
    pub pk: Vec<usize>,
    /// The table's CHECK constraints in **evaluation order** — ascending byte order of the
    /// lowercased name (spec/design/constraints.md §4.4); the on-disk catalog stores them in
    /// this same order. Empty for an unchecked table.
    pub checks: Vec<CheckConstraint>,
    /// The table's secondary indexes in **ascending lowercased-name order** (the catalog's
    /// on-disk order and the planner's tie-break order — spec/design/indexes.md §5/§6).
    pub indexes: Vec<IndexDef>,
    /// The table's FOREIGN KEY constraints in **ascending lowercased-name order** (the catalog's
    /// on-disk order and the child-side evaluation order — spec/design/constraints.md §6.9).
    /// Empty for a table with none.
    pub foreign_keys: Vec<ForeignKeyConstraint>,
    /// The table's `EXCLUDE` constraints in **ascending lowercased-name order** (the catalog's
    /// on-disk order — spec/design/gist.md §7/§8). Each is backed by a GiST index in `indexes`.
    /// Empty for a table with none.
    pub exclusions: Vec<ExclusionConstraint>,
}

/// A fully-resolved storage/codec column type (spec/design/composite.md §4): a scalar, or a
/// composite resolved to the codec/coercion tree of its fields. Built **once** from a catalog
/// `Type` against the snapshot's composite-type definitions ([`resolve_col_type`]) and held by the
/// `TableStore`, so the value codec and store-coercion never re-walk the type catalog on every row.
/// Recursive — a composite field may itself be composite. The codec reads only the scalar / field
/// structure; the field `typmod` / `not_null` are consulted by store-coercion (executor).
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum ColType {
    Scalar(ScalarType),
    /// A composite type's resolved fields, in declaration order. `name` is the (original-case)
    /// type name, used in store-coercion error messages.
    Composite {
        name: String,
        fields: Vec<ColField>,
    },
    /// An array's resolved element type (spec/design/array.md §3). Structural — the element type
    /// is carried inline, recursively; v1 element types are scalars (composite/nested-array
    /// elements are deferred). The codec reads the element structure; store-coercion coerces each
    /// element to it.
    Array(Box<ColType>),
    /// A range's resolved element type (spec/design/ranges.md §3). Structural like array — the
    /// element is carried inline, but is always one of the six scalar subtypes (`i32`/`i64`/
    /// `decimal`/`timestamp`/`timestamptz`/`date`), never composite/array/nested-range. The codec
    /// reads the element scalar for the bound bodies; the descriptor (discreteness) is re-derived
    /// from the element via `range::range_for_element`.
    Range(Box<ColType>),
}

/// One resolved field of a [`ColType::Composite`] — its name, recursively-resolved type, the
/// decimal typmod (when the field is `decimal`), and declared nullability (mirrors `CompositeField`,
/// but with the type fully resolved for the codec/coercion path).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct ColField {
    pub name: String,
    pub ty: ColType,
    pub typmod: Option<DecimalTypmod>,
    /// The `varchar(n)` max-length typmod when `ty` is `text` (spec/design/types.md §15).
    pub varchar_len: Option<u32>,
    pub not_null: bool,
}

/// Resolve a catalog [`Type`] into a self-contained [`ColType`] against the database's composite
/// definitions (keyed by lowercased name, the `Snapshot.types` map). A composite reference is
/// looked up case-insensitively and recursively resolved; the lookup is guaranteed to succeed
/// because `validate_composite_types` (the two-pass load / `CREATE TYPE` gate) proved every
/// reference exists and the graph is acyclic before any store is built (spec/design/composite.md §3).
pub fn resolve_col_type(ty: &Type, types: &HashMap<String, CompositeType>) -> ColType {
    match ty {
        Type::Scalar(s) => ColType::Scalar(*s),
        Type::Composite(r) => {
            let def = types
                .get(&r.name.to_ascii_lowercase())
                .expect("composite type reference resolved by validate_composite_types");
            ColType::Composite {
                name: def.name.clone(),
                fields: def
                    .fields
                    .iter()
                    .map(|f| ColField {
                        name: f.name.clone(),
                        ty: resolve_col_type(&f.ty, types),
                        typmod: f.decimal,
                        varchar_len: f.varchar_len,
                        not_null: f.not_null,
                    })
                    .collect(),
            }
        }
        Type::Array(elem) => ColType::Array(Box::new(resolve_col_type(elem, types))),
        // A range column (spec/design/ranges.md §3): structural like array, the element resolved
        // inline. The element is always one of the six scalar subtypes, so the recursion bottoms
        // out at `ColType::Scalar` immediately.
        Type::Range(elem) => ColType::Range(Box::new(resolve_col_type(elem, types))),
    }
}

impl Table {
    /// Index of the named column (case-insensitive), if present.
    pub fn column_index(&self, name: &str) -> Option<usize> {
        self.columns
            .iter()
            .position(|c| c.name.eq_ignore_ascii_case(name))
    }

    /// The primary-key member columns' indices in KEY order (the explicit `pk` list — the
    /// v5 catalog persists key order independent of declaration order). Empty = the table
    /// has no primary key (synthetic rowid keys).
    pub fn pk_indices(&self) -> Vec<usize> {
        self.pk.clone()
    }

    /// The primary-key column's index iff the key is SINGLE-column. The PK pushdown
    /// (point lookup / range bound) recognizes single-column keys only — a composite-PK
    /// table full-scans this slice (spec/design/constraints.md §3) — so every pushdown
    /// site routes through this accessor and stays sound by construction.
    pub fn primary_key_index(&self) -> Option<usize> {
        match self.pk_indices().as_slice() {
            [i] => Some(*i),
            _ => None,
        }
    }
}
