// @generated by scripts/gen_costs.rb from spec/cost/schedule.toml — DO NOT EDIT.
//
// Cost unit schedule (CLAUDE.md §5, §13: the codegen "middle path"). DATA only — the
// accrual sites that CONSUME these weights (executor / evaluator / storage reads) are
// hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
// `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/cost.md.

/// The deterministic cost-unit weights, mirroring spec/cost/schedule.toml.
pub struct CostSchedule {
    pub storage_row_read: i64,
    pub page_read: i64,
    pub row_produced: i64,
    pub operator_eval: i64,
    pub aggregate_accumulate: i64,
}

/// The canonical cost schedule — weights accrued per unit during query execution.
pub const COSTS: CostSchedule = CostSchedule {
    storage_row_read: 1,
    page_read: 1,
    row_produced: 1,
    operator_eval: 1,
    aggregate_accumulate: 1,
};
