// @generated by scripts/gen_costs.rb from spec/cost/schedule.toml — DO NOT EDIT.
//
// Cost unit schedule (CLAUDE.md §5, §13: the codegen "middle path"). DATA only — the
// accrual sites that CONSUME these weights (executor / evaluator / storage reads) are
// hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
// `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/cost.md.

/// The deterministic cost-unit weights, mirroring spec/cost/schedule.toml.
pub struct CostSchedule {
    pub storage_row_read: i64,
    pub page_read: i64,
    pub value_compress: i64,
    pub value_decompress: i64,
    pub decimal_work: i64,
    pub row_produced: i64,
    pub operator_eval: i64,
    pub aggregate_accumulate: i64,
    pub cte_scan_row: i64,
    pub generated_row: i64,
    pub sequence_advance: i64,
    pub gin_entry: i64,
    pub collate: i64,
    pub timezone: i64,
    pub regex_compile: i64,
    pub regex_step: i64,
}

/// The canonical cost schedule — weights accrued per unit during query execution.
pub const COSTS: CostSchedule = CostSchedule {
    storage_row_read: 1,
    page_read: 1,
    value_compress: 1,
    value_decompress: 1,
    decimal_work: 1,
    row_produced: 1,
    operator_eval: 1,
    aggregate_accumulate: 1,
    cte_scan_row: 1,
    generated_row: 1,
    sequence_advance: 1,
    gin_entry: 1,
    collate: 1,
    timezone: 1,
    regex_compile: 1,
    regex_step: 1,
};
