// @generated by scripts/gen_estimator.rb from spec/cost/{estimator,schedule}.toml — DO NOT EDIT.
// Mechanical constants only; estimator control flow remains hand-written in every core.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EstimatorFraction {
    pub numerator: i64,
    pub denominator: i64,
}

pub const MAX_ESTIMATE: i64 = 9223372036854775807;
pub const DEFAULT_DISTINCT_VALUES: i64 = 200;
pub const DEFAULT_SRF_ROWS: i64 = 1000;
pub const DEFAULT_VARIABLE_KEY_BYTES: i64 = 1;
pub const JOIN_DP_LIMIT: usize = 8;

pub const SELECTIVITY_EQUALITY: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 200,
};
pub const SELECTIVITY_INEQUALITY: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 3,
};
pub const SELECTIVITY_PAIRED_RANGE: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 200,
};
pub const SELECTIVITY_NULL_TEST: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 200,
};
pub const SELECTIVITY_MATCH: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 200,
};
pub const SELECTIVITY_MATCHING: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 100,
};
pub const SELECTIVITY_BOOLEAN: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 2,
};
pub const SELECTIVITY_OPAQUE: EstimatorFraction = EstimatorFraction {
    numerator: 1,
    denominator: 3,
};

pub const ACCESS_GIST_EQUAL: &str = "equality";
pub const ACCESS_GIST_RANGE: &str = "matching";
pub const ACCESS_GIN_CONTAINS: &str = "matching";
pub const ACCESS_GIN_OVERLAPS: &str = "matching";
pub const ACCESS_GIN_MEMBER: &str = "matching";
pub const ACCESS_GIN_EQUAL: &str = "matching";
pub const ACCESS_UNSUPPORTED: &str = "opaque";

pub const ACCESS_PATH_ORDER: [&str; 7] = [
    "pk",
    "btree",
    "gist",
    "gin",
    "pk_interval",
    "index_interval",
    "full",
];

pub const ESTIMATOR_UNIT_COUNT: usize = 23;
pub const UNIT_STORAGE_ROW_READ: usize = 0;
pub const UNIT_PAGE_READ: usize = 1;
pub const UNIT_CONSTRAINT_CHECK: usize = 2;
pub const UNIT_VALUE_COMPRESS: usize = 3;
pub const UNIT_VALUE_DECOMPRESS: usize = 4;
pub const UNIT_DECIMAL_WORK: usize = 5;
pub const UNIT_ROW_PRODUCED: usize = 6;
pub const UNIT_OPERATOR_EVAL: usize = 7;
pub const UNIT_HASH_BUILD: usize = 8;
pub const UNIT_HASH_PROBE: usize = 9;
pub const UNIT_AGGREGATE_ACCUMULATE: usize = 10;
pub const UNIT_CTE_SCAN_ROW: usize = 11;
pub const UNIT_GENERATED_ROW: usize = 12;
pub const UNIT_SEQUENCE_ADVANCE: usize = 13;
pub const UNIT_GIN_ENTRY: usize = 14;
pub const UNIT_GIST_DESCENT: usize = 15;
pub const UNIT_COLLATE: usize = 16;
pub const UNIT_TIMEZONE: usize = 17;
pub const UNIT_REGEX_COMPILE: usize = 18;
pub const UNIT_REGEX_STEP: usize = 19;
pub const UNIT_WINDOW_RESULT: usize = 20;
pub const UNIT_VARLEN_COMPARE: usize = 21;
pub const UNIT_WINDOW_FRAME_STEP: usize = 22;
pub const ESTIMATOR_UNIT_IDS: [&str; ESTIMATOR_UNIT_COUNT] = [
    "storage_row_read",
    "page_read",
    "constraint_check",
    "value_compress",
    "value_decompress",
    "decimal_work",
    "row_produced",
    "operator_eval",
    "hash_build",
    "hash_probe",
    "aggregate_accumulate",
    "cte_scan_row",
    "generated_row",
    "sequence_advance",
    "gin_entry",
    "gist_descent",
    "collate",
    "timezone",
    "regex_compile",
    "regex_step",
    "window_result",
    "varlen_compare",
    "window_frame_step",
];
#[rustfmt::skip]
pub const ESTIMATOR_UNIT_WEIGHTS: [i64; ESTIMATOR_UNIT_COUNT] = [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
];
