// @generated by scripts/gen_catalog.rb from spec/functions/catalog.toml — DO NOT EDIT.
//
// Operator descriptor table (CLAUDE.md §5: the codegen "middle path"). This is DATA
// only — the parser, executor, and the eq3/lt3 evaluation logic that CONSUME it are
// hand-written (§5 forbids codegenning those). Regenerate with `rake codegen`;
// `rake verify` fails if this file is stale. Reasoning: ../../../spec/design/codegen.md.

/// One operator's metadata, mirroring a `[[operator]]` entry in catalog.toml.
pub struct OperatorDesc {
    pub name: &'static str,
    pub symbol: Option<&'static str>,
    pub kind: &'static str,
    pub arity: u8,
    pub arg_families: &'static [&'static str],
    pub arg_resolution: &'static str,
    pub result: &'static str,
    pub null: &'static str,
    pub errors: &'static [&'static str],
}

/// Every operator in the catalog, in catalog order.
pub const OPERATORS: &[OperatorDesc] = &[
    OperatorDesc {
        name: "eq",
        symbol: Some("="),
        kind: "comparison",
        arity: 2,
        arg_families: &["integer", "integer"],
        arg_resolution: "promote",
        result: "truth",
        null: "propagates",
        errors: &[],
    },
    OperatorDesc {
        name: "lt",
        symbol: Some("<"),
        kind: "comparison",
        arity: 2,
        arg_families: &["integer", "integer"],
        arg_resolution: "promote",
        result: "truth",
        null: "propagates",
        errors: &[],
    },
    OperatorDesc {
        name: "gt",
        symbol: Some(">"),
        kind: "comparison",
        arity: 2,
        arg_families: &["integer", "integer"],
        arg_resolution: "promote",
        result: "truth",
        null: "propagates",
        errors: &[],
    },
    OperatorDesc {
        name: "le",
        symbol: Some("<="),
        kind: "comparison",
        arity: 2,
        arg_families: &["integer", "integer"],
        arg_resolution: "promote",
        result: "truth",
        null: "propagates",
        errors: &[],
    },
    OperatorDesc {
        name: "ge",
        symbol: Some(">="),
        kind: "comparison",
        arity: 2,
        arg_families: &["integer", "integer"],
        arg_resolution: "promote",
        result: "truth",
        null: "propagates",
        errors: &[],
    },
    OperatorDesc {
        name: "is_null",
        symbol: None,
        kind: "null_test",
        arity: 1,
        arg_families: &["any"],
        arg_resolution: "none",
        result: "truth",
        null: "detects",
        errors: &[],
    },
    OperatorDesc {
        name: "is_not_null",
        symbol: None,
        kind: "null_test",
        arity: 1,
        arg_families: &["any"],
        arg_resolution: "none",
        result: "truth",
        null: "detects",
        errors: &[],
    },
];
