// @generated by scripts/gen_errors.rb from spec/errors/registry.toml — DO NOT EDIT.
//
// SQLSTATE error codes (CLAUDE.md §5, §10: the codegen "middle path"). DATA only — the
// EngineError scaffolding that CONSUMES these (message assembly, Display, the raise sites
// through the executor) is hand-written in error.rs (§5 forbids codegenning those).
// Regenerate with `rake codegen`; `rake verify` fails if this file is stale. Each variant's
// message template + rationale live in spec/errors/registry.toml. Reasoning:
// ../../../spec/design/codegen.md.

/// A structured engine error's SQLSTATE. The string value is the canonical 5-char code from
/// spec/errors/registry.toml (cross-checked in tests). Declaration order is registry order
/// and carries no meaning — the discriminant is never serialized.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum SqlState {
    /// 21000 — more than one row returned by a subquery used as an expression
    CardinalityViolation,
    /// 22000 — {detail}
    DataException,
    /// 22003 — value out of range for type {type}
    NumericValueOutOfRange,
    /// 22004 — {detail}
    NullValueNotAllowed,
    /// 22007 — invalid input syntax for type {type}: {detail}
    InvalidDatetimeFormat,
    /// 22008 — date/time field value out of range: {detail}
    DatetimeFieldOverflow,
    /// 22012 — division by zero
    DivisionByZero,
    /// 2200H — nextval: reached {bound} value of sequence {sequence}
    SequenceGeneratorLimitExceeded,
    /// 2201W — LIMIT must not be negative
    InvalidRowCountInLimitClause,
    /// 2201X — OFFSET must not be negative
    InvalidRowCountInOffsetClause,
    /// 22023 — invalid parameter value: {detail}
    InvalidParameterValue,
    /// 22025 — LIKE pattern must not end with escape character
    InvalidEscapeSequence,
    /// 2201B — invalid regular expression: {detail}
    InvalidRegularExpression,
    /// 2202E — {detail}
    ArraySubscriptError,
    /// 22P02 — invalid input syntax for type {type}: {detail}
    InvalidTextRepresentation,
    /// 23502 — null value in column {name} violates not-null constraint
    NotNullViolation,
    /// 23505 — duplicate key value violates unique constraint: {name}
    UniqueViolation,
    /// 23514 — new row for relation {table} violates check constraint {name}
    CheckViolation,
    /// 23503 — insert or update on table {table} violates foreign key constraint {name}
    ForeignKeyViolation,
    /// 25001 — there is already a transaction in progress
    ActiveSqlTransaction,
    /// 25006 — cannot execute {statement} in a read-only transaction
    ReadOnlySqlTransaction,
    /// 25P02 — current transaction is aborted, commands ignored until end of transaction block
    InFailedSqlTransaction,
    /// 2BP01 — cannot drop type {name} because other objects depend on it: {detail}
    DependentObjectsStillExist,
    /// 42601 — syntax error: {detail}
    SyntaxError,
    /// 42P01 — table does not exist: {name}
    UndefinedTable,
    /// 42703 — column does not exist: {name}
    UndefinedColumn,
    /// 42702 — column reference {name} is ambiguous
    AmbiguousColumn,
    /// 42704 — {kind} does not exist: {name}
    UndefinedObject,
    /// 42P10 — for SELECT DISTINCT, ORDER BY expressions must appear in select list
    InvalidColumnReference,
    /// 42804 — datatype mismatch: {detail}
    DatatypeMismatch,
    /// 42830 — there is no unique constraint matching given keys for referenced table {name}
    InvalidForeignKey,
    /// 42701 — duplicate column name: {name}
    DuplicateColumn,
    /// 42712 — table name {name} specified more than once
    DuplicateAlias,
    /// 42P07 — relation already exists: {name}
    DuplicateTable,
    /// 42P16 — invalid table definition: {detail}
    InvalidTableDefinition,
    /// 42803 — column {name} must appear in the GROUP BY clause or be used in an aggregate function
    GroupingError,
    /// 42883 — function does not exist: {name}
    UndefinedFunction,
    /// 42P18 — could not determine data type of parameter ${index}
    IndeterminateDatatype,
    /// 42P19 — {detail}
    InvalidRecursion,
    /// 42P02 — there is no parameter ${index}
    UndefinedParameter,
    /// 42P21 — collation mismatch between explicit collations {left} and {right}
    CollationMismatch,
    /// 42P22 — could not determine which collation to use for string comparison
    IndeterminateCollation,
    /// 42710 — constraint {name} for relation {table} already exists
    DuplicateObject,
    /// 42809 — {name} is not {kind}
    WrongObjectType,
    /// 42622 — identifier exceeds the maximum length of {max} bytes
    NameTooLong,
    /// 428C9 — {detail}
    GeneratedAlways,
    /// 42501 — permission denied for {object}
    InsufficientPrivilege,
    /// 0A000 — feature not supported: {detail}
    FeatureNotSupported,
    /// 54000 — SQL statement exceeds the maximum length of {max} bytes
    ProgramLimitExceeded,
    /// 54001 — statement too complex: nesting depth exceeds the maximum of {max}
    StatementTooComplex,
    /// 54P01 — query exceeded the cost limit of {limit} (accrued {cost})
    CostLimitExceeded,
    /// 54P02 — session exceeded the lifetime cost limit of {limit} (accrued {cost})
    SessionCostLimitExceeded,
    /// 54P03 — temporary table storage exceeded the limit of {limit} bytes
    TempStorageLimitExceeded,
    /// 55000 — {detail}
    ObjectNotInPrerequisiteState,
    /// 58030 — I/O error: {detail}
    IoError,
    /// 58P01 — database file does not exist: {path}
    UndefinedFile,
    /// 58P02 — database file already exists: {path}
    DuplicateFile,
    /// XX001 — on-disk database file is malformed: {detail}
    DataCorrupted,
    /// XX002 — collation version mismatch: {detail}
    CollationVersionMismatch,
}

impl SqlState {
    /// The canonical 5-char SQLSTATE string (spec/errors/registry.toml).
    pub fn code(self) -> &'static str {
        match self {
            SqlState::CardinalityViolation => "21000",
            SqlState::DataException => "22000",
            SqlState::NumericValueOutOfRange => "22003",
            SqlState::NullValueNotAllowed => "22004",
            SqlState::InvalidDatetimeFormat => "22007",
            SqlState::DatetimeFieldOverflow => "22008",
            SqlState::DivisionByZero => "22012",
            SqlState::SequenceGeneratorLimitExceeded => "2200H",
            SqlState::InvalidRowCountInLimitClause => "2201W",
            SqlState::InvalidRowCountInOffsetClause => "2201X",
            SqlState::InvalidParameterValue => "22023",
            SqlState::InvalidEscapeSequence => "22025",
            SqlState::InvalidRegularExpression => "2201B",
            SqlState::ArraySubscriptError => "2202E",
            SqlState::InvalidTextRepresentation => "22P02",
            SqlState::NotNullViolation => "23502",
            SqlState::UniqueViolation => "23505",
            SqlState::CheckViolation => "23514",
            SqlState::ForeignKeyViolation => "23503",
            SqlState::ActiveSqlTransaction => "25001",
            SqlState::ReadOnlySqlTransaction => "25006",
            SqlState::InFailedSqlTransaction => "25P02",
            SqlState::DependentObjectsStillExist => "2BP01",
            SqlState::SyntaxError => "42601",
            SqlState::UndefinedTable => "42P01",
            SqlState::UndefinedColumn => "42703",
            SqlState::AmbiguousColumn => "42702",
            SqlState::UndefinedObject => "42704",
            SqlState::InvalidColumnReference => "42P10",
            SqlState::DatatypeMismatch => "42804",
            SqlState::InvalidForeignKey => "42830",
            SqlState::DuplicateColumn => "42701",
            SqlState::DuplicateAlias => "42712",
            SqlState::DuplicateTable => "42P07",
            SqlState::InvalidTableDefinition => "42P16",
            SqlState::GroupingError => "42803",
            SqlState::UndefinedFunction => "42883",
            SqlState::IndeterminateDatatype => "42P18",
            SqlState::InvalidRecursion => "42P19",
            SqlState::UndefinedParameter => "42P02",
            SqlState::CollationMismatch => "42P21",
            SqlState::IndeterminateCollation => "42P22",
            SqlState::DuplicateObject => "42710",
            SqlState::WrongObjectType => "42809",
            SqlState::NameTooLong => "42622",
            SqlState::GeneratedAlways => "428C9",
            SqlState::InsufficientPrivilege => "42501",
            SqlState::FeatureNotSupported => "0A000",
            SqlState::ProgramLimitExceeded => "54000",
            SqlState::StatementTooComplex => "54001",
            SqlState::CostLimitExceeded => "54P01",
            SqlState::SessionCostLimitExceeded => "54P02",
            SqlState::TempStorageLimitExceeded => "54P03",
            SqlState::ObjectNotInPrerequisiteState => "55000",
            SqlState::IoError => "58030",
            SqlState::UndefinedFile => "58P01",
            SqlState::DuplicateFile => "58P02",
            SqlState::DataCorrupted => "XX001",
            SqlState::CollationVersionMismatch => "XX002",
        }
    }
}

/// One error's metadata, mirroring an `[[error]]` entry in registry.toml. The enum above is
/// the type-safe code used at raise sites; this slice is the iterable data table the
/// cross-check tests walk against the registry (the enum is not iterable).
pub struct ErrorDesc {
    pub code: &'static str,
    pub name: &'static str,
    pub class: &'static str,
}

/// Every error, in registry order.
#[rustfmt::skip]
pub const ERRORS: &[ErrorDesc] = &[
    ErrorDesc { code: "21000", name: "cardinality_violation", class: "cardinality violation" },
    ErrorDesc { code: "22000", name: "data_exception", class: "data exception" },
    ErrorDesc { code: "22003", name: "numeric_value_out_of_range", class: "data exception" },
    ErrorDesc { code: "22004", name: "null_value_not_allowed", class: "data exception" },
    ErrorDesc { code: "22007", name: "invalid_datetime_format", class: "data exception" },
    ErrorDesc { code: "22008", name: "datetime_field_overflow", class: "data exception" },
    ErrorDesc { code: "22012", name: "division_by_zero", class: "data exception" },
    ErrorDesc { code: "2200H", name: "sequence_generator_limit_exceeded", class: "data exception" },
    ErrorDesc { code: "2201W", name: "invalid_row_count_in_limit_clause", class: "data exception" },
    ErrorDesc { code: "2201X", name: "invalid_row_count_in_offset_clause", class: "data exception" },
    ErrorDesc { code: "22023", name: "invalid_parameter_value", class: "data exception" },
    ErrorDesc { code: "22025", name: "invalid_escape_sequence", class: "data exception" },
    ErrorDesc { code: "2201B", name: "invalid_regular_expression", class: "data exception" },
    ErrorDesc { code: "2202E", name: "array_subscript_error", class: "data exception" },
    ErrorDesc { code: "22P02", name: "invalid_text_representation", class: "data exception" },
    ErrorDesc { code: "23502", name: "not_null_violation", class: "integrity constraint violation" },
    ErrorDesc { code: "23505", name: "unique_violation", class: "integrity constraint violation" },
    ErrorDesc { code: "23514", name: "check_violation", class: "integrity constraint violation" },
    ErrorDesc { code: "23503", name: "foreign_key_violation", class: "integrity constraint violation" },
    ErrorDesc { code: "25001", name: "active_sql_transaction", class: "invalid transaction state" },
    ErrorDesc { code: "25006", name: "read_only_sql_transaction", class: "invalid transaction state" },
    ErrorDesc { code: "25P02", name: "in_failed_sql_transaction", class: "invalid transaction state" },
    ErrorDesc { code: "2BP01", name: "dependent_objects_still_exist", class: "dependent objects still exist" },
    ErrorDesc { code: "42601", name: "syntax_error", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P01", name: "undefined_table", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42703", name: "undefined_column", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42702", name: "ambiguous_column", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42704", name: "undefined_object", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P10", name: "invalid_column_reference", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42804", name: "datatype_mismatch", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42830", name: "invalid_foreign_key", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42701", name: "duplicate_column", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42712", name: "duplicate_alias", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P07", name: "duplicate_table", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P16", name: "invalid_table_definition", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42803", name: "grouping_error", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42883", name: "undefined_function", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P18", name: "indeterminate_datatype", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P19", name: "invalid_recursion", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P02", name: "undefined_parameter", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P21", name: "collation_mismatch", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42P22", name: "indeterminate_collation", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42710", name: "duplicate_object", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42809", name: "wrong_object_type", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42622", name: "name_too_long", class: "syntax error or access rule violation" },
    ErrorDesc { code: "428C9", name: "generated_always", class: "syntax error or access rule violation" },
    ErrorDesc { code: "42501", name: "insufficient_privilege", class: "syntax error or access rule violation" },
    ErrorDesc { code: "0A000", name: "feature_not_supported", class: "feature not supported" },
    ErrorDesc { code: "54000", name: "program_limit_exceeded", class: "program limit exceeded" },
    ErrorDesc { code: "54001", name: "statement_too_complex", class: "program limit exceeded" },
    ErrorDesc { code: "54P01", name: "cost_limit_exceeded", class: "program limit exceeded" },
    ErrorDesc { code: "54P02", name: "session_cost_limit_exceeded", class: "program limit exceeded" },
    ErrorDesc { code: "54P03", name: "temp_storage_limit_exceeded", class: "program limit exceeded" },
    ErrorDesc { code: "55000", name: "object_not_in_prerequisite_state", class: "object not in prerequisite state" },
    ErrorDesc { code: "58030", name: "io_error", class: "system error" },
    ErrorDesc { code: "58P01", name: "undefined_file", class: "system error" },
    ErrorDesc { code: "58P02", name: "duplicate_file", class: "system error" },
    ErrorDesc { code: "XX001", name: "data_corrupted", class: "internal error" },
    ErrorDesc { code: "XX002", name: "collation_version_mismatch", class: "internal error" },
];
