//! IDENTITY columns (spec/design/sequences.md §13) — the per-core unit tests for what the PG-clean
//! oracle corpus cannot express (CLAUDE.md §10): the **on-disk persistence** of the ALWAYS/BY
//! DEFAULT distinction (the `428C9` gate still fires after a close/open) and the auto-named owned
//! sequence auto-drop. The PG-agreeing behavior (auto-numbering, OVERRIDING SYSTEM/USER, 428C9, the
//! 42601 conflicts, the 22023 type gate, and — since S5, §14 — the owned sequence following the
//! column type) lives in suites/ddl/identity.test + suites/ddl/sequence_as_type.test.

use std::path::PathBuf;

use jed::value::Value;
use jed::{DatabaseOptions, Engine, Outcome, execute};

fn tmp(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(name)
}

fn one_int(db: &mut Engine, sql: &str) -> Option<i64> {
    match execute(db, sql).unwrap() {
        Outcome::Query { rows, .. } => match &rows[0][0] {
            Value::Int(n) => Some(*n),
            Value::Null => None,
            v => panic!("expected int/null, got {v:?}"),
        },
        o => panic!("expected a query, got {o:?}"),
    }
}

fn err_code(db: &mut Engine, sql: &str) -> String {
    execute(db, sql).unwrap_err().state.code().to_string()
}

/// An IDENTITY column desugars to an integer column, NOT NULL, with a `nextval` default backed by an
/// auto-created OWNED sequence named `<table>_<col>_seq` (same machinery as `serial`, sequences.md
/// §13). Two columns — one ALWAYS, one BY DEFAULT — each get their own owned sequence.
#[test]
fn identity_desugars_to_owned_sequences() {
    let mut db = Engine::new();
    execute(
        &mut db,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, \
         n int GENERATED BY DEFAULT AS IDENTITY, v text)",
    )
    .unwrap();
    match execute(
        &mut db,
        "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id, n",
    )
    .unwrap()
    {
        Outcome::Query { rows, .. } => {
            assert_eq!(rows[0], vec![Value::Int(1), Value::Int(1)]);
            assert_eq!(rows[1], vec![Value::Int(2), Value::Int(2)]);
        }
        o => panic!("expected a query, got {o:?}"),
    }
    // The owned sequences exist under PG's derived names and keep advancing.
    assert_eq!(one_int(&mut db, "SELECT nextval('t_id_seq')"), Some(3));
    assert_eq!(one_int(&mut db, "SELECT nextval('t_n_seq')"), Some(3));
}

/// The ALWAYS/BY DEFAULT distinction persists (format_version 15, the two column flag bits): after
/// create + commit + reopen, the ALWAYS column still rejects an explicit value (`428C9`) and the
/// BY DEFAULT column still accepts one — proving the bits round-tripped through the catalog bytes.
#[test]
fn identity_kind_survives_reopen() {
    let path = tmp("identity_reopen.jed");
    let _ = std::fs::remove_file(&path);
    {
        let mut db = Engine::create(&path, DatabaseOptions::default()).unwrap();
        execute(
            &mut db,
            "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, \
             n int GENERATED BY DEFAULT AS IDENTITY, v text)",
        )
        .unwrap();
        execute(&mut db, "INSERT INTO t (v) VALUES ('a')").unwrap();
        db.commit().unwrap();
    }
    {
        let mut db = Engine::open(&path).unwrap();
        // ALWAYS still rejects an explicit value (the bit round-tripped).
        assert_eq!(
            err_code(&mut db, "INSERT INTO t (id, v) VALUES (5, 'x')"),
            "428C9"
        );
        // ...but OVERRIDING SYSTEM VALUE still lets it through.
        execute(
            &mut db,
            "INSERT INTO t (id, v) OVERRIDING SYSTEM VALUE VALUES (5, 'x')",
        )
        .unwrap();
        // BY DEFAULT still accepts an explicit value with no override.
        execute(&mut db, "INSERT INTO t (n, v) VALUES (9, 'y')").unwrap();
        // The owner link round-tripped too: still 2BP01 to drop the sequence directly.
        assert_eq!(err_code(&mut db, "DROP SEQUENCE t_id_seq"), "2BP01");
        db.commit().unwrap();
    }
    let _ = std::fs::remove_file(&path);
}

/// DROP TABLE auto-drops every IDENTITY column's owned sequence (the `OWNED BY` link, sequences.md
/// §13/§12.3), exactly as for `serial`.
#[test]
fn identity_owned_sequences_auto_drop() {
    let mut db = Engine::new();
    execute(
        &mut db,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, n bigint GENERATED BY DEFAULT AS IDENTITY)",
    )
    .unwrap();
    assert_eq!(err_code(&mut db, "DROP SEQUENCE t_id_seq"), "2BP01");
    execute(&mut db, "DROP TABLE t").unwrap();
    assert_eq!(err_code(&mut db, "SELECT nextval('t_id_seq')"), "42P01");
    assert_eq!(err_code(&mut db, "SELECT nextval('t_n_seq')"), "42P01");
}

/// S5 (§14): an IDENTITY column's owned sequence follows the **column type** — a `smallint GENERATED
/// … AS IDENTITY` gets an `AS smallint` sequence bounded to `[1, 32767]` (matching PG; the prior
/// bigint-flavored divergence is closed). Introspects the auto-created sequence via its derived name:
/// `setval` past 32767 is `22003`, and `nextval` at the boundary traps `2200H` — the sequence itself
/// is now bounded (the corpus pins the boundary too, but the auto-name wiring stays a per-core check).
#[test]
fn identity_owned_sequence_follows_column_type() {
    let mut db = Engine::new();
    execute(
        &mut db,
        "CREATE TABLE t (id smallint GENERATED ALWAYS AS IDENTITY, v text)",
    )
    .unwrap();
    // The owned sequence is AS smallint: setval past the i16 max is out of bounds (22003).
    assert_eq!(
        err_code(&mut db, "SELECT setval('t_id_seq', 40000)"),
        "22003"
    );
    // At the boundary, the next value overflows the sequence (2200H) — not the column (the i16
    // sequence stops here, exactly as PG).
    execute(&mut db, "SELECT setval('t_id_seq', 32767)").unwrap();
    assert_eq!(err_code(&mut db, "SELECT nextval('t_id_seq')"), "2200H");
}

/// The identity sequence options `( … )` tune the owned sequence (a per-core check that the option
/// set threads through the desugaring — the values themselves are PG-clean and also in the corpus).
#[test]
fn identity_with_sequence_options() {
    let mut db = Engine::new();
    execute(
        &mut db,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 5), v text)",
    )
    .unwrap();
    match execute(
        &mut db,
        "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id",
    )
    .unwrap()
    {
        Outcome::Query { rows, .. } => {
            assert_eq!(rows[0][0], Value::Int(100));
            assert_eq!(rows[1][0], Value::Int(105));
        }
        o => panic!("expected a query, got {o:?}"),
    }
}
