//! IDENTITY columns (spec/design/sequences.md §13) — the per-core unit tests for what the PG-clean
//! oracle corpus cannot express (CLAUDE.md §10): the **on-disk persistence** of the ALWAYS/BY
//! DEFAULT distinction (the `428C9` gate still fires after a close/open), the auto-named owned
//! sequence introspection, and the **bigint-flavored owned sequence** divergence (decision 11). The
//! PG-agreeing behavior (auto-numbering, OVERRIDING SYSTEM/USER, 428C9, the 42601 conflicts, the
//! 22023 type gate) lives in suites/ddl/identity.test.

use std::path::PathBuf;

use jed::value::Value;
use jed::{Database, DatabaseOptions, Outcome, execute};

fn tmp(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(name)
}

fn one_int(db: &mut Database, sql: &str) -> Option<i64> {
    match execute(db, sql).unwrap() {
        Outcome::Query { rows, .. } => match &rows[0][0] {
            Value::Int(n) => Some(*n),
            Value::Null => None,
            v => panic!("expected int/null, got {v:?}"),
        },
        o => panic!("expected a query, got {o:?}"),
    }
}

fn err_code(db: &mut Database, sql: &str) -> String {
    execute(db, sql).unwrap_err().state.code().to_string()
}

/// An IDENTITY column desugars to an integer column, NOT NULL, with a `nextval` default backed by an
/// auto-created OWNED sequence named `<table>_<col>_seq` (same machinery as `serial`, sequences.md
/// §13). Two columns — one ALWAYS, one BY DEFAULT — each get their own owned sequence.
#[test]
fn identity_desugars_to_owned_sequences() {
    let mut db = Database::new();
    execute(
        &mut db,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, \
         n int GENERATED BY DEFAULT AS IDENTITY, v text)",
    )
    .unwrap();
    match execute(
        &mut db,
        "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id, n",
    )
    .unwrap()
    {
        Outcome::Query { rows, .. } => {
            assert_eq!(rows[0], vec![Value::Int(1), Value::Int(1)]);
            assert_eq!(rows[1], vec![Value::Int(2), Value::Int(2)]);
        }
        o => panic!("expected a query, got {o:?}"),
    }
    // The owned sequences exist under PG's derived names and keep advancing.
    assert_eq!(one_int(&mut db, "SELECT nextval('t_id_seq')"), Some(3));
    assert_eq!(one_int(&mut db, "SELECT nextval('t_n_seq')"), Some(3));
}

/// The ALWAYS/BY DEFAULT distinction persists (format_version 15, the two column flag bits): after
/// create + commit + reopen, the ALWAYS column still rejects an explicit value (`428C9`) and the
/// BY DEFAULT column still accepts one — proving the bits round-tripped through the catalog bytes.
#[test]
fn identity_kind_survives_reopen() {
    let path = tmp("identity_reopen.jed");
    let _ = std::fs::remove_file(&path);
    {
        let mut db = Database::create(&path, DatabaseOptions::default()).unwrap();
        execute(
            &mut db,
            "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, \
             n int GENERATED BY DEFAULT AS IDENTITY, v text)",
        )
        .unwrap();
        execute(&mut db, "INSERT INTO t (v) VALUES ('a')").unwrap();
        db.commit().unwrap();
    }
    {
        let mut db = Database::open(&path).unwrap();
        // ALWAYS still rejects an explicit value (the bit round-tripped).
        assert_eq!(
            err_code(&mut db, "INSERT INTO t (id, v) VALUES (5, 'x')"),
            "428C9"
        );
        // ...but OVERRIDING SYSTEM VALUE still lets it through.
        execute(
            &mut db,
            "INSERT INTO t (id, v) OVERRIDING SYSTEM VALUE VALUES (5, 'x')",
        )
        .unwrap();
        // BY DEFAULT still accepts an explicit value with no override.
        execute(&mut db, "INSERT INTO t (n, v) VALUES (9, 'y')").unwrap();
        // The owner link round-tripped too: still 2BP01 to drop the sequence directly.
        assert_eq!(err_code(&mut db, "DROP SEQUENCE t_id_seq"), "2BP01");
        db.commit().unwrap();
    }
    let _ = std::fs::remove_file(&path);
}

/// DROP TABLE auto-drops every IDENTITY column's owned sequence (the `OWNED BY` link, sequences.md
/// §13/§12.3), exactly as for `serial`.
#[test]
fn identity_owned_sequences_auto_drop() {
    let mut db = Database::new();
    execute(
        &mut db,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, n bigint GENERATED BY DEFAULT AS IDENTITY)",
    )
    .unwrap();
    assert_eq!(err_code(&mut db, "DROP SEQUENCE t_id_seq"), "2BP01");
    execute(&mut db, "DROP TABLE t").unwrap();
    assert_eq!(err_code(&mut db, "SELECT nextval('t_id_seq')"), "42P01");
    assert_eq!(err_code(&mut db, "SELECT nextval('t_n_seq')"), "42P01");
}

/// DIVERGENCE (decision 11): an IDENTITY column's owned sequence is **bigint-flavored** regardless of
/// the column width — a `smallint GENERATED … AS IDENTITY` gets a default i64 sequence (MAXVALUE
/// 2^63-1), not PG's smallint sequence (MAXVALUE 32767). Advancing the *sequence* past 32767 succeeds
/// in jed where PG would raise 2200H; the narrower *column* type only bounds stored values (22003 at
/// INSERT). This is the `AS type` deferral, ledgered — so it stays in a per-core test, not the corpus.
#[test]
fn identity_owned_sequence_is_bigint_flavored() {
    let mut db = Database::new();
    execute(
        &mut db,
        "CREATE TABLE t (id smallint GENERATED ALWAYS AS IDENTITY, v text)",
    )
    .unwrap();
    // Drive the owned sequence past the i16 max directly — jed allows it (bigint sequence); PG's
    // smallint identity sequence would 2200H here.
    execute(&mut db, "SELECT setval('t_id_seq', 40000)").unwrap();
    assert_eq!(one_int(&mut db, "SELECT nextval('t_id_seq')"), Some(40001));
    // The column type still bounds a stored value: an INSERT pulling 40001 traps 22003 (the column
    // is i16), the documented divergence point (PG's 2200H lives at the sequence instead).
    assert_eq!(err_code(&mut db, "INSERT INTO t (v) VALUES ('a')"), "22003");
}

/// The identity sequence options `( … )` tune the owned sequence (a per-core check that the option
/// set threads through the desugaring — the values themselves are PG-clean and also in the corpus).
#[test]
fn identity_with_sequence_options() {
    let mut db = Database::new();
    execute(
        &mut db,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 5), v text)",
    )
    .unwrap();
    match execute(
        &mut db,
        "INSERT INTO t (v) VALUES ('a'), ('b') RETURNING id",
    )
    .unwrap()
    {
        Outcome::Query { rows, .. } => {
            assert_eq!(rows[0][0], Value::Int(100));
            assert_eq!(rows[1][0], Value::Int(105));
        }
        o => panic!("expected a query, got {o:?}"),
    }
}
